"""BioAgent pipeline implementation. Generated by consolidating the original modules."""
from __future__ import annotations

# --- original module: __init__.py ---
"""BacFunc: eggNOG-mapper gene-level functional annotation."""


__version__ = "0.2.0"

__all__ = ["__version__"]

# --- original module: errors.py ---
"""BacFunc exception hierarchy."""



class BacargError(RuntimeError):
    """Base class for user-facing pipeline failures."""


class ConfigurationError(BacargError):
    """Raised when deployment configuration is invalid."""


class DatabaseConfigurationError(ConfigurationError):
    """Raised when a required database is unavailable or invalid."""


class InputValidationError(BacargError):
    """Raised when sequence input is unsafe or malformed."""


class ExternalToolError(BacargError):
    """Raised when an external command fails."""


class ParseError(BacargError):
    """Raised when an external data file cannot be parsed safely."""

# --- original module: manifest.py ---
"""Run provenance helpers."""


import hashlib
import platform
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable


def utc_now() -> str:
    """Return an ISO-8601 UTC timestamp."""
    return datetime.now(timezone.utc).isoformat()


def sha256_file(path: Path) -> str:
    """Stream a file SHA-256 without loading it into memory."""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def input_records(paths: Iterable[Path]) -> list[dict[str, Any]]:
    """Collect stable input provenance."""
    records: list[dict[str, Any]] = []
    for path in paths:
        stat = path.stat()
        records.append(
            {
                "name": path.name,
                "size": stat.st_size,
                "sha256": sha256_file(path),
            }
        )
    return records


def runtime_record() -> dict[str, str]:
    """Return Python and operating-system provenance."""
    return {
        "python_version": platform.python_version(),
        "python_implementation": platform.python_implementation(),
        "platform": platform.platform(),
        "executable_name": Path(sys.executable).name,
    }


def database_manifest(path: Path | None, warnings: list[str]) -> dict[str, Any] | None:
    """Record a deployment manifest or a warning-backed file summary."""
    if path is None:
        warnings.append("Database manifest is not configured; strict provenance is unavailable.")
        return None
    if not path.is_file():
        warnings.append(f"Database manifest is missing: {path.name}")
        return None
    import json

    try:
        with path.open("r", encoding="utf-8") as handle:
            payload = json.load(handle)
    except (OSError, json.JSONDecodeError) as exc:
        warnings.append(f"Database manifest could not be read: {exc}")
        return None
    return payload if isinstance(payload, dict) else {"content": payload}

# --- original module: outputs.py ---
"""Atomic deterministic result writers."""


import csv
import json
import os
import tempfile
from pathlib import Path
from typing import Iterable, Mapping, Sequence


def _temporary(path: Path) -> tuple[int, Path]:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    return descriptor, Path(name)


def write_json(path: Path, payload: object) -> None:
    """Atomically write stable UTF-8 JSON."""
    descriptor, temporary = _temporary(path)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            json.dump(payload, handle, ensure_ascii=False, indent=2, sort_keys=True)
            handle.write("\n")
        temporary.replace(path)
    except Exception:
        temporary.unlink(missing_ok=True)
        raise


def write_tsv(
    path: Path, rows: Iterable[Mapping[str, object]], fields: Sequence[str]
) -> None:
    """Atomically write a TSV with an explicit stable column order."""
    descriptor, temporary = _temporary(path)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="") as handle:
            writer = csv.DictWriter(
                handle, fieldnames=list(fields), delimiter="\t", lineterminator="\n"
            )
            writer.writeheader()
            for row in rows:
                writer.writerow({field: row.get(field, "") for field in fields})
        temporary.replace(path)
    except Exception:
        temporary.unlink(missing_ok=True)
        raise


def write_jsonl(path: Path, rows: Iterable[Mapping[str, object]]) -> None:
    """Atomically write deterministic JSON Lines."""
    descriptor, temporary = _temporary(path)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            for row in rows:
                handle.write(json.dumps(dict(row), ensure_ascii=False, sort_keys=True))
                handle.write("\n")
        temporary.replace(path)
    except Exception:
        temporary.unlink(missing_ok=True)
        raise

# --- original module: versions.py ---
"""Small, bounded external-tool version probes for provenance."""


import subprocess
from typing import Sequence


def probe_version(executable: object, prefix_options: Sequence[object] = ()) -> str:
    """Return the first version line, or an explicit unavailable marker."""
    try:
        completed = subprocess.run(
            [str(executable), *[str(item) for item in prefix_options], "--version"],
            stdin=subprocess.DEVNULL,
            capture_output=True,
            text=True,
            shell=False,
            check=False,
            timeout=15,
        )
    except (OSError, subprocess.SubprocessError):
        return "unavailable"
    if completed.returncode != 0:
        return "unavailable"
    lines = [
        line.strip()
        for line in (completed.stdout + "\n" + completed.stderr).splitlines()
        if line.strip()
    ]
    return lines[0][:500] if lines else "unavailable"

# --- original module: command.py ---
"""Safe external command execution with auditable argument boundaries."""


import json
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, Optional, Sequence



@dataclass
class CommandRunner:
    """Execute or plan subprocess calls without a shell."""

    dry_run: bool = False
    commands: list[list[str]] = field(default_factory=list)

    def run(
        self,
        command: Sequence[object],
        *,
        tool: str,
        log_path: Path,
        stdout_path: Optional[Path] = None,
    ) -> int:
        """Run one command and stream output directly to files."""
        args = [str(part) for part in command]
        if not args:
            raise ExternalToolError(f"{tool} command is empty.")
        self.commands.append(args)
        log_path.parent.mkdir(parents=True, exist_ok=True)
        with log_path.open("a", encoding="utf-8", newline="\n") as log:
            log.write(f"START {tool}\n")
            log.write("COMMAND " + json.dumps(args, ensure_ascii=False) + "\n")
            if self.dry_run:
                log.write(f"END {tool} dry-run\n")
                return 0
            output_handle = None
            try:
                if stdout_path is not None:
                    stdout_path.parent.mkdir(parents=True, exist_ok=True)
                    output_handle = stdout_path.open("w", encoding="utf-8", newline="\n")
                completed = subprocess.run(
                    args,
                    stdin=subprocess.DEVNULL,
                    stdout=output_handle if output_handle is not None else log,
                    stderr=log,
                    check=False,
                    shell=False,
                    text=True,
                )
            except OSError as exc:
                log.write(f"ERROR {exc}\n")
                raise ExternalToolError(
                    f"{tool} could not be started; see log: {log_path}"
                ) from exc
            finally:
                if output_handle is not None:
                    output_handle.close()
            log.write(f"EXIT_CODE {completed.returncode}\n")
            log.write(f"END {tool}\n")
        if completed.returncode != 0:
            raise ExternalToolError(
                f"{tool} failed with exit code {completed.returncode}; see log: {log_path}"
            )
        return completed.returncode


def render_commands(commands: Iterable[Sequence[str]]) -> list[list[str]]:
    """Return JSON-safe command argument lists."""
    return [[str(part) for part in command] for command in commands]

# --- original module: config.py ---
"""BacFunc configuration discovery and path resolution."""


import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, MutableMapping, Optional

import yaml



PROJECT_NAME = "bacfunc"
CONFIG_ENV = "BACFUNC_CONFIG"
_ENV_PATTERN = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}")


@dataclass(frozen=True)
class PipelineConfig:
    """Expanded configuration and resolved CPU count."""

    data: Mapping[str, Any]
    source: Path
    threads: int

    def value(self, *keys: str, required: bool = True) -> Any:
        current: Any = self.data
        for key in keys:
            if not isinstance(current, Mapping) or key not in current:
                if required:
                    raise ConfigurationError(
                        f"Missing configuration value: {'.'.join(keys)}"
                    )
                return None
            current = current[key]
        return current

    def section(self, name: str) -> Mapping[str, Any]:
        value = self.value(name)
        if not isinstance(value, Mapping):
            raise ConfigurationError(f"Configuration section '{name}' must be a mapping.")
        return value

    def eggnog_path(self, key: str, required: bool = True) -> Optional[Path]:
        value = self.value("databases", "eggnog", key, required=required)
        if value in (None, ""):
            if required:
                if key == "data_dir":
                    raise DatabaseConfigurationError(
                        "eggNOG database path is not configured. "
                        "Set BACFUNC_EGGNOG_DATA_DIR or databases.eggnog.data_dir."
                    )
                raise DatabaseConfigurationError(f"eggNOG {key} is not configured.")
            return None
        return Path(str(value))


def _expand_string(value: str) -> str:
    missing = sorted({name for name in _ENV_PATTERN.findall(value) if name not in os.environ})
    if missing:
        raise ConfigurationError(
            "Unset environment variable(s) in configuration: " + ", ".join(missing)
        )
    expanded = _ENV_PATTERN.sub(lambda match: os.environ[match.group(1)], value)
    if _ENV_PATTERN.search(expanded):
        raise ConfigurationError(f"Unexpanded environment variable in value: {value}")
    return os.path.expanduser(expanded)


def _expand(value: Any) -> Any:
    if isinstance(value, str):
        return _expand_string(value)
    if isinstance(value, list):
        return [_expand(item) for item in value]
    if isinstance(value, Mapping):
        return {key: _expand(item) for key, item in value.items()}
    return value


def discover_config(explicit: Optional[Path] = None, cwd: Optional[Path] = None) -> Path:
    """Apply CLI, environment, CWD, project, and package-default precedence."""
    project_root = Path(__file__).resolve().parents[1]
    package_default = Path(__file__).resolve().parent / "default_config.yaml"
    if explicit is not None:
        candidates = [Path(explicit)]
    elif os.environ.get(CONFIG_ENV):
        candidates = [Path(_expand_string(os.environ[CONFIG_ENV]))]
    else:
        candidates = [(cwd or Path.cwd()) / "config.yaml", project_root / "config.yaml", package_default]
    for candidate in candidates:
        path = Path(os.path.expanduser(str(candidate))).resolve()
        if path.is_file():
            return path
        if explicit is not None or os.environ.get(CONFIG_ENV):
            raise ConfigurationError(f"Configuration file does not exist: {path}")
    raise ConfigurationError("No configuration file was found.")


def _read(path: Path) -> dict[str, Any]:
    try:
        with path.open("r", encoding="utf-8") as handle:
            data = yaml.safe_load(handle) or {}
    except OSError as exc:
        raise ConfigurationError(f"Cannot read configuration file: {path}") from exc
    except yaml.YAMLError as exc:
        raise ConfigurationError(f"Invalid YAML configuration: {path}: {exc}") from exc
    if not isinstance(data, dict):
        raise ConfigurationError(f"Configuration root must be a mapping: {path}")
    return data


def _set_database_environment(data: MutableMapping[str, Any]) -> None:
    databases = data.setdefault("databases", {})
    if not isinstance(databases, MutableMapping):
        raise ConfigurationError("Configuration section 'databases' must be a mapping.")
    eggnog = databases.setdefault("eggnog", {})
    if not isinstance(eggnog, MutableMapping):
        raise ConfigurationError("databases.eggnog must be a mapping.")
    if os.environ.get("BACFUNC_EGGNOG_DATA_DIR"):
        eggnog["data_dir"] = os.environ["BACFUNC_EGGNOG_DATA_DIR"]
    if os.environ.get("BACFUNC_EGGNOG_MANIFEST"):
        eggnog["manifest"] = os.environ["BACFUNC_EGGNOG_MANIFEST"]


def _resolve_paths(data: MutableMapping[str, Any], source: Path) -> None:
    eggnog = data.setdefault("databases", {}).setdefault("eggnog", {})
    for key in ("data_dir", "manifest"):
        value = eggnog.get(key)
        if value in (None, ""):
            continue
        path = Path(str(value))
        if not path.is_absolute():
            path = source.parent / path
        eggnog[key] = str(path.resolve())


def _validate(data: Mapping[str, Any]) -> int:
    pipeline = data.get("pipeline", {})
    if pipeline.get("sample_type") != "metagenome":
        raise ConfigurationError("pipeline.sample_type must be 'metagenome'.")
    raw_threads = pipeline.get("threads", "auto")
    if raw_threads == "auto":
        threads = max(1, os.cpu_count() or 1)
    else:
        try:
            threads = int(raw_threads)
        except (TypeError, ValueError) as exc:
            raise ConfigurationError("pipeline.threads must be 'auto' or an integer.") from exc
        if threads < 1:
            raise ConfigurationError("pipeline.threads must be at least 1.")
    tools = data.get("tools", {})
    assembler_options = [str(item) for item in tools.get("assembler", {}).get("options", [])]
    if any(item.lstrip("-").lower() == "isolate" for item in assembler_options):
        raise ConfigurationError("Metagenome assembly must not enable isolate mode.")
    prokka_options = [str(item) for item in tools.get("prokka", {}).get("options", [])]
    if "--metagenome" not in prokka_options:
        raise ConfigurationError("Prokka configuration must include --metagenome.")
    eggnog = tools.get("eggnog", {})
    if str(eggnog.get("version")) != "2.1.15":
        raise ConfigurationError("tools.eggnog.version must be 2.1.15.")
    if str(eggnog.get("search_mode")).lower() != "diamond":
        raise ConfigurationError("tools.eggnog.search_mode must be diamond.")
    options = [str(item) for item in eggnog.get("options", [])]
    if "--itype" not in options or "proteins" not in options:
        raise ConfigurationError("eggNOG options must declare --itype proteins.")
    return threads


def load_config(explicit: Optional[Path] = None, cwd: Optional[Path] = None) -> PipelineConfig:
    """Load, expand, normalize, and validate configuration."""
    source = discover_config(explicit, cwd)
    data = _read(source)
    _set_database_environment(data)
    data = _expand(data)
    _resolve_paths(data, source)
    threads = _validate(data)
    data.setdefault("pipeline", {})["resolved_threads"] = threads
    return PipelineConfig(data=data, source=source, threads=threads)

# --- original module: input.py ---
"""Content-based sequence detection, sample grouping, and input safety checks."""


import gzip
import io
import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator, Literal, Sequence, TextIO



SUPPORTED_SUFFIXES = (
    ".fa", ".fna", ".fasta", ".fas", ".fq", ".fastq",
    ".fa.gz", ".fna.gz", ".fasta.gz", ".fas.gz", ".fq.gz", ".fastq.gz",
)
_SAFE_SAMPLE = re.compile(r"[^A-Za-z0-9._-]+")
_MATE_PATTERN = re.compile(
    r"^(?P<sample>.*?)(?:(?:[._-]R?)(?P<separated>[12])|R(?P<compact>[12]))"
    r"(?:[._-]?001)?$",
    re.IGNORECASE,
)
InputType = Literal["reads", "genome"]
AnalysisMode = Literal["reads", "genome", "assemble"]


@dataclass(frozen=True)
class InputSet:
    """Validated sequence inputs."""

    files: tuple[Path, ...]
    kind: str
    paired: bool
    compressed: tuple[bool, ...]
    sample_id: str
    input_type: InputType
    analysis_mode: AnalysisMode


def is_gzip(path: Path) -> bool:
    """Detect gzip by magic bytes rather than filename."""
    with path.open("rb") as handle:
        return handle.read(2) == b"\x1f\x8b"


def open_sequence_text(path: Path) -> TextIO:
    """Open plain or gzip-compressed sequence text as UTF-8."""
    raw = path.open("rb")
    try:
        if raw.read(2) == b"\x1f\x8b":
            raw.seek(0)
            binary = gzip.GzipFile(fileobj=raw)
            return io.TextIOWrapper(binary, encoding="utf-8", newline=None)
        raw.seek(0)
        return io.TextIOWrapper(raw, encoding="utf-8", newline=None)
    except Exception:
        raw.close()
        raise


def _nonblank(lines: Iterator[str]) -> Iterator[str]:
    for line in lines:
        value = line.rstrip("\r\n")
        if value.strip():
            yield value


def _validate_fasta(first: str, lines: Iterator[str], path: Path) -> None:
    records = 0
    has_sequence = False
    for line in (item for item in (first, *()) if item):
        if not line.startswith(">") or not line[1:].strip():
            raise InputValidationError(f"Invalid FASTA header in {path}")
        records += 1
    for line in lines:
        value = line.rstrip("\r\n")
        if not value.strip():
            continue
        if value.startswith(">"):
            if not has_sequence:
                raise InputValidationError(f"FASTA record has no sequence in {path}")
            if not value[1:].strip():
                raise InputValidationError(f"Invalid FASTA header in {path}")
            records += 1
            has_sequence = False
        else:
            if value.startswith("@") or re.search(r"\s", value):
                raise InputValidationError(f"Invalid or mixed FASTA content in {path}")
            has_sequence = True
    if records == 0 or not has_sequence:
        raise InputValidationError(f"FASTA contains no sequence records: {path}")


def _validate_fastq(first: str, lines: Iterator[str], path: Path) -> None:
    if not first.startswith("@") or not first[1:].strip():
        raise InputValidationError(f"Invalid FASTQ header in {path}")
    pending: list[str] = [first]
    record_count = 0
    for line in lines:
        pending.append(line.rstrip("\r\n"))
        if len(pending) == 4:
            header, sequence, plus, quality = pending
            if not header.startswith("@") or not header[1:].strip():
                raise InputValidationError(f"Invalid FASTQ header in {path}")
            if not sequence or re.search(r"\s", sequence):
                raise InputValidationError(f"Invalid FASTQ sequence in {path}")
            if not plus.startswith("+"):
                raise InputValidationError(f"Invalid FASTQ separator in {path}")
            if len(sequence) != len(quality):
                raise InputValidationError(f"FASTQ sequence/quality length mismatch in {path}")
            record_count += 1
            pending = []
    if pending:
        raise InputValidationError(f"Incomplete FASTQ record in {path}")
    if record_count == 0:
        raise InputValidationError(f"FASTQ contains no records: {path}")


def detect_sequence_format(path: Path) -> str:
    """Return ``fasta`` or ``fastq`` after validating file content."""
    path = Path(path)
    if not path.exists():
        raise InputValidationError(f"Input file does not exist: {path}")
    if not path.is_file():
        raise InputValidationError(f"Input path is not a file: {path}")
    if not os.access(path, os.R_OK):
        raise InputValidationError(f"Input file is not readable: {path}")
    try:
        with open_sequence_text(path) as handle:
            iterator = iter(handle)
            first = next(_nonblank(iterator), None)
            if first is None:
                raise InputValidationError(f"Input file is empty: {path}")
            if first.startswith(">"):
                _validate_fasta(first, iterator, path)
                return "fasta"
            if first.startswith("@"):
                _validate_fastq(first, iterator, path)
                return "fastq"
    except (gzip.BadGzipFile, UnicodeError, OSError) as exc:
        raise InputValidationError(f"Cannot read sequence content from {path}: {exc}") from exc
    raise InputValidationError(f"Input is neither valid FASTA nor FASTQ: {path}")


def sanitize_sample_id(value: str) -> str:
    """Return a filesystem-safe, stable sample identifier."""
    cleaned = _SAFE_SAMPLE.sub("_", value.strip()).strip("._-")
    cleaned = re.sub(r"_+", "_", cleaned)
    if not cleaned:
        cleaned = "sample"
    return cleaned[:100]


def _derived_sample(files: Sequence[Path]) -> str:
    names = []
    for path in files:
        name = path.name
        if name.lower().endswith(".gz"):
            name = name[:-3]
        name = re.sub(r"\.(?:fa|fna|fasta|fas|fq|fastq)$", "", name, flags=re.I)
        name = re.sub(r"([._-])R?[12]$", "", name, flags=re.I)
        names.append(name)
    if len(names) == 2:
        first = _mate_key(files[0])
        second = _mate_key(files[1])
        if first is not None and second is not None and first[0].casefold() == second[0].casefold():
            return sanitize_sample_id(first[0] or "sample")
        common = os.path.commonprefix(names).rstrip("._-")
        return sanitize_sample_id(common or names[0])
    return sanitize_sample_id(names[0])


def _sequence_stem(path: Path) -> str:
    name = path.name
    if name.lower().endswith(".gz"):
        name = name[:-3]
    return re.sub(r"\.(?:fa|fna|fasta|fas|fq|fastq)$", "", name, flags=re.I)


def _mate_key(path: Path) -> tuple[str, int] | None:
    match = _MATE_PATTERN.fullmatch(_sequence_stem(path))
    if match is None:
        return None
    mate = match.group("separated") or match.group("compact")
    sample = match.group("sample").rstrip("._-")
    return sample, int(mate)


def _validate_pair(files: Sequence[Path]) -> None:
    if len(files) != 2:
        return
    first = _mate_key(files[0])
    second = _mate_key(files[1])
    if first is None or second is None:
        raise InputValidationError(
            "Two FASTQ files require recognizable R1/R2 (or _1/_2) mate names; "
            "use separate runs for unrelated single-end samples."
        )
    if (
        first[0].casefold() != second[0].casefold()
        or first[1] != 1
        or second[1] != 2
    ):
        raise InputValidationError(
            "FASTQ pair must be an ordered R1/R2 pair with the same sample stem."
        )


def _resolve_contract(
    sequence_kind: str, input_type: str, analysis_mode: str
) -> tuple[InputType, AnalysisMode]:
    if input_type not in {"auto", "reads", "genome"}:
        raise InputValidationError("input_type must be one of: auto, reads, genome.")
    if analysis_mode not in {"auto", "reads", "genome", "assemble"}:
        raise InputValidationError(
            "analysis_mode must be one of: auto, reads, genome, assemble."
        )
    detected_type: InputType = "reads" if sequence_kind == "fastq" else "genome"
    resolved_type: InputType = (
        detected_type if input_type == "auto" else input_type  # type: ignore[assignment]
    )
    if resolved_type != detected_type:
        raise InputValidationError(
            f"Explicit input_type '{resolved_type}' does not match detected "
            f"{sequence_kind.upper()} content ({detected_type})."
        )
    if analysis_mode == "auto":
        resolved_mode: AnalysisMode = (
            "assemble" if resolved_type == "reads" else "genome"
        )
    else:
        resolved_mode = analysis_mode  # type: ignore[assignment]
    allowed_modes = {"reads", "assemble"} if resolved_type == "reads" else {"genome"}
    if resolved_mode not in allowed_modes:
        raise InputValidationError(
            f"input_type '{resolved_type}' does not support analysis_mode "
            f"'{resolved_mode}'."
        )
    return resolved_type, resolved_mode


def validate_inputs(
    files: Sequence[Path],
    output: Path,
    sample_id: str | None = None,
    *,
    input_type: str = "auto",
    analysis_mode: str = "auto",
) -> InputSet:
    """Validate count, identity, content type, and output safety."""
    if not files:
        raise InputValidationError("Provide one FASTA/FASTQ file or a paired FASTQ pair.")
    if len(files) > 2:
        raise InputValidationError("At most two input files are accepted.")
    resolved = tuple(Path(item).expanduser().resolve() for item in files)
    if len(set(resolved)) != len(resolved):
        raise InputValidationError("Duplicate input files are not allowed.")
    kinds = tuple(detect_sequence_format(path) for path in resolved)
    if len(set(kinds)) != 1:
        raise InputValidationError("Mixed FASTA and FASTQ input is not allowed.")
    if kinds[0] == "fasta" and len(resolved) != 1:
        raise InputValidationError("FASTA mode accepts exactly one assembled metagenome.")
    if kinds[0] == "fastq":
        _validate_pair(resolved)
    resolved_type, resolved_mode = _resolve_contract(
        kinds[0], input_type, analysis_mode
    )
    output_resolved = Path(output).expanduser().resolve()
    if output_resolved.exists() and not output_resolved.is_dir():
        raise InputValidationError(f"Output path is an existing file: {output_resolved}")
    for path in resolved:
        if output_resolved == path or output_resolved in path.parents:
            raise InputValidationError(
                f"Output directory would contain or overwrite an input file: {output_resolved}"
            )
    return InputSet(
        files=resolved,
        kind=kinds[0],
        paired=kinds[0] == "fastq" and len(resolved) == 2,
        compressed=tuple(is_gzip(path) for path in resolved),
        sample_id=sanitize_sample_id(sample_id) if sample_id else _derived_sample(resolved),
        input_type=resolved_type,
        analysis_mode=resolved_mode,
    )


def discover_samples(
    files: Sequence[Path],
    output: Path,
    *,
    input_directory: Path | None = None,
    sample_id: str | None = None,
    input_type: str = "auto",
    analysis_mode: str = "auto",
) -> list[InputSet]:
    """Discover independent FASTA samples and strict FASTQ singletons/pairs."""
    if files and input_directory is not None:
        raise InputValidationError("Use either input files or input_directory, not both.")
    candidates = [Path(item) for item in files]
    if input_directory is not None:
        directory = Path(input_directory).expanduser().resolve()
        if not directory.is_dir():
            raise InputValidationError(f"Input directory does not exist: {directory}")
        output_resolved = Path(output).expanduser().resolve()
        if directory == output_resolved or directory in output_resolved.parents:
            raise InputValidationError(
                "Output directory must not be inside the input directory."
            )
        candidates = sorted(
            (
                item
                for item in directory.iterdir()
                if item.is_file()
                and any(item.name.lower().endswith(suffix) for suffix in SUPPORTED_SUFFIXES)
            ),
            key=lambda item: item.name.casefold(),
        )
    if not candidates:
        raise InputValidationError("No supported FASTA/FASTQ input files were found.")
    resolved = [item.expanduser().resolve() for item in candidates]
    if len(set(resolved)) != len(resolved):
        raise InputValidationError("Duplicate input files are not allowed.")
    detected = {path: detect_sequence_format(path) for path in resolved}
    groups: list[list[Path]] = []
    groups.extend([[path] for path in resolved if detected[path] == "fasta"])
    paired: dict[str, dict[int, Path]] = {}
    for path in (item for item in resolved if detected[item] == "fastq"):
        key = _mate_key(path)
        if key is None:
            groups.append([path])
            continue
        stem, mate = key
        normalized = stem.casefold()
        slots = paired.setdefault(normalized, {})
        if mate in slots:
            raise InputValidationError(
                f"Duplicate R{mate} FASTQ files for sample stem '{stem or 'sample'}'."
            )
        slots[mate] = path
    for stem, slots in sorted(paired.items()):
        if set(slots) == {1}:
            groups.append([slots[1]])
            continue
        if set(slots) != {1, 2}:
            raise InputValidationError(
                f"FASTQ sample stem '{stem or 'sample'}' has R2 without R1."
            )
        groups.append([slots[1], slots[2]])
    groups.sort(key=lambda group: tuple(path.name.casefold() for path in group))
    if sample_id is not None and len(groups) != 1:
        raise InputValidationError(
            "--sample-id can only be used when exactly one sample is discovered."
        )
    samples = [
        validate_inputs(
            group,
            output,
            sample_id=sample_id,
            input_type=input_type,
            analysis_mode=analysis_mode,
        )
        for group in groups
    ]
    identifiers = [item.sample_id.casefold() for item in samples]
    if len(set(identifiers)) != len(identifiers):
        raise InputValidationError(
            "Discovered sample IDs are not unique; rename inputs or run samples "
            "separately with explicit --sample-id values."
        )
    return samples

# --- original module: runner_bridge.py ---
"""Small helpers for Agent runtime YAML inputs."""


from pathlib import Path
from typing import Any

import yaml



def read_runtime(path: Path, mode: str = "auto") -> tuple[list[Path], Path, str | None]:
    """Translate an Agent runtime YAML into explicit CLI-equivalent values."""
    with path.open("r", encoding="utf-8") as handle:
        data: Any = yaml.safe_load(handle) or {}
    if not isinstance(data, dict):
        raise ConfigurationError("Runner runtime YAML must be a mapping.")
    base = path.resolve().parent
    inputs = data.get("inputs", {})
    outputs = data.get("outputs", {})
    if not isinstance(inputs, dict) or not isinstance(outputs, dict):
        raise ConfigurationError("Runner inputs and outputs must be mappings.")
    if mode == "fasta":
        raw_files = [inputs.get("assembly")]
    elif mode == "fastq":
        raw_files = [inputs.get("read1"), inputs.get("read2")]
    else:
        raw = inputs.get("sequences")
        raw_files = raw if isinstance(raw, list) else [raw]
    files = [
        (base / str(item)).resolve() if not Path(str(item)).is_absolute() else Path(str(item)).resolve()
        for item in raw_files
        if item
    ]
    raw_output = outputs.get("directory") or data.get("output")
    if not raw_output:
        raise ConfigurationError("Runner runtime YAML is missing outputs.directory.")
    output = Path(str(raw_output))
    if not output.is_absolute():
        output = base / output
    return files, output.resolve(), data.get("sample_id")

# --- original module: assembly.py ---
"""Trimmomatic and metagenome assembly orchestration."""


import shutil
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping, Sequence



@dataclass(frozen=True)
class AssemblyResult:
    """Assembly path and preprocessing provenance."""

    path: Path
    source: str
    trimmed_reads: tuple[Path, ...]
    unpaired_reads: tuple[Path, ...]



@dataclass(frozen=True)
class ReadPreparation:
    """Trimmed reads and discarded mate outputs."""

    trimmed_reads: tuple[Path, ...]
    unpaired_reads: tuple[Path, ...]

def trimmomatic_command(
    reads: Sequence[Path], output_dir: Path, config: PipelineConfig
) -> tuple[list[str], tuple[Path, ...], tuple[Path, ...]]:
    """Build single- or paired-end Trimmomatic arguments."""
    tool = config.value("tools", "trimmomatic")
    executable = str(tool["executable"])
    options = [str(item) for item in tool.get("options", [])]
    if len(reads) == 1:
        trimmed = output_dir / "trimmed.fastq.gz"
        command = [
            executable, *[str(item) for item in tool.get("prefix_options", [])],
            "SE", "-threads", str(config.threads), str(reads[0]), str(trimmed), *options,
        ]
        return command, (trimmed,), ()
    if len(reads) == 2:
        paired1 = output_dir / "trimmed_R1.fastq.gz"
        unpaired1 = output_dir / "unpaired_R1.fastq.gz"
        paired2 = output_dir / "trimmed_R2.fastq.gz"
        unpaired2 = output_dir / "unpaired_R2.fastq.gz"
        command = [
            executable, *[str(item) for item in tool.get("prefix_options", [])],
            "PE", "-threads", str(config.threads), str(reads[0]), str(reads[1]),
            str(paired1), str(unpaired1), str(paired2), str(unpaired2), *options,
        ]
        return command, (paired1, paired2), (unpaired1, unpaired2)
    raise ValueError("Trimmomatic requires one read or an explicit R1/R2 pair.")



def prepare_reads(
    inputs: InputSet,
    work_dir: Path,
    config: PipelineConfig,
    runner: CommandRunner,
) -> ReadPreparation:
    """Quality-trim FASTQ reads without assembling them."""
    if inputs.kind != "fastq":
        raise ValueError("Direct reads analysis requires FASTQ input.")
    trim_dir = work_dir / "trimmed"
    trim_dir.mkdir(parents=True, exist_ok=True)
    command, trimmed, unpaired = trimmomatic_command(inputs.files, trim_dir, config)
    runner.run(
        command,
        tool="Trimmomatic",
        log_path=work_dir.parent / "logs" / "trimmomatic.log",
    )
    if not runner.dry_run:
        for path in trimmed:
            if not path.is_file() or path.stat().st_size == 0:
                raise ExternalToolError(
                    f"Trimmomatic completed without a non-empty output: {path}"
                )
    return ReadPreparation(tuple(trimmed), tuple(unpaired))

def assembler_command(
    trimmed: Sequence[Path],
    unpaired: Sequence[Path],
    output_dir: Path,
    config: PipelineConfig,
) -> list[str]:
    """Build a metaSPAdes command without isolate-mode assumptions."""
    tool = config.value("tools", "assembler")
    options = [str(item) for item in tool.get("options", [])]
    if any(item.lstrip("-").lower() == "isolate" for item in options):
        raise ValueError("Assembler options must not enable isolate mode.")
    command = [
        str(tool["executable"]), *[str(item) for item in tool.get("prefix_options", [])],
        *options, "-t", str(config.threads),
    ]
    memory = tool.get("memory_gb")
    if memory not in (None, ""):
        command.extend(["-m", str(memory)])
    command.extend(["-o", str(output_dir)])
    if len(trimmed) == 2:
        command.extend(["-1", str(trimmed[0]), "-2", str(trimmed[1])])
        if tool.get("include_unpaired", False):
            for index, path in enumerate(unpaired, start=1):
                command.extend([f"--s{index}", str(path)])
    else:
        command.extend(["-s", str(trimmed[0])])
    return command


def _copy_plain_fasta(source: Path, target: Path) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", newline="\n", delete=False, dir=target.parent
    ) as temporary:
        temporary_path = Path(temporary.name)
        with open_sequence_text(source) as handle:
            shutil.copyfileobj(handle, temporary)
    temporary_path.replace(target)


def prepare_assembly(
    inputs: InputSet,
    work_dir: Path,
    config: PipelineConfig,
    runner: CommandRunner,
) -> AssemblyResult:
    """Use supplied contigs or build a metagenome assembly from reads."""
    assembly_dir = work_dir / "assembly"
    assembly_dir.mkdir(parents=True, exist_ok=True)
    if inputs.kind == "fasta":
        assembly = assembly_dir / "assembly.fasta"
        _copy_plain_fasta(inputs.files[0], assembly)
        return AssemblyResult(assembly, "supplied", (), ())
    trim_dir = work_dir / "trimmed"
    trim_dir.mkdir(parents=True, exist_ok=True)
    trim_command, trimmed, unpaired = trimmomatic_command(inputs.files, trim_dir, config)
    runner.run(
        trim_command, tool="Trimmomatic", log_path=work_dir.parent / "logs" / "trimmomatic.log"
    )
    spades_dir = assembly_dir / "metaspades"
    command = assembler_command(trimmed, unpaired, spades_dir, config)
    runner.run(
        command, tool="metaSPAdes", log_path=work_dir.parent / "logs" / "metaspades.log"
    )
    assembly = spades_dir / "contigs.fasta"
    if not runner.dry_run and (not assembly.is_file() or assembly.stat().st_size == 0):
        raise ExternalToolError(
            f"metaSPAdes completed without a non-empty contigs.fasta: {assembly}"
        )
    return AssemblyResult(assembly, "metaspades", tuple(trimmed), tuple(unpaired))

# --- original module: eggnog.py ---
"""eggNOG database validation, command construction, and dynamic parsing."""


import csv
import os
import re
import sqlite3
from pathlib import Path
from typing import Any, Iterable, Mapping



REQUIRED_DATABASE_FILES = (
    "eggnog.db",
    "eggnog.taxa.db",
    "eggnog.taxa.db.traverse.pkl",
    "eggnog_proteins.dmnd",
)
TERM_COLUMNS = {
    "GOs": "GO",
    "COG_category": "COG_CATEGORY",
    "eggNOG_OGs": "EGGNOG_OG",
    "EC": "EC",
    "KEGG_ko": "KEGG_KO",
    "KEGG_Pathway": "KEGG_PATHWAY",
    "KEGG_Module": "KEGG_MODULE",
    "KEGG_Reaction": "KEGG_REACTION",
    "KEGG_rclass": "KEGG_RCLASS",
    "BRITE": "BRITE",
    "KEGG_TC": "KEGG_TC",
    "CAZy": "CAZY",
    "BiGG_Reaction": "BIGG_REACTION",
    "PFAMs": "PFAM",
}
TERM_FIELDS = ["sample_id", "gene_id", "namespace", "term_id", "term_name", "source_column"]


def validate_database_path(data_dir: Path) -> dict[str, Any]:
    """Read-only eggNOG v5 preflight including SQLite validation."""
    data_dir = data_dir.expanduser().resolve()
    if not data_dir.is_dir():
        raise DatabaseConfigurationError(f"eggNOG data directory does not exist: {data_dir}")
    files: dict[str, dict[str, Any]] = {}
    for name in REQUIRED_DATABASE_FILES:
        path = data_dir / name
        if not path.is_file():
            raise DatabaseConfigurationError(f"Required eggNOG database file is missing: {path}")
        if path.stat().st_size == 0 or not os.access(path, os.R_OK):
            raise DatabaseConfigurationError(f"eggNOG database file is empty or unreadable: {path}")
        stat = path.stat()
        files[name] = {
            "size": stat.st_size,
            "modified_time": stat.st_mtime,
        }
    database = data_dir / "eggnog.db"
    detected_version = "unknown"
    try:
        connection = sqlite3.connect(f"{database.resolve().as_uri()}?mode=ro", uri=True)
        try:
            connection.execute("SELECT name FROM sqlite_master LIMIT 1").fetchone()
            tables = {
                str(row[0])
                for row in connection.execute(
                    "SELECT name FROM sqlite_master WHERE type='table'"
                ).fetchall()
            }
            for table in ("version", "metadata", "eggnog_version"):
                if table not in tables:
                    continue
                columns = [
                    str(row[1])
                    for row in connection.execute(f'PRAGMA table_info("{table}")').fetchall()
                ]
                version_column = next(
                    (item for item in columns if "version" in item.lower()), None
                )
                if version_column:
                    row = connection.execute(
                        f'SELECT "{version_column}" FROM "{table}" LIMIT 1'
                    ).fetchone()
                    if row and row[0] not in (None, ""):
                        detected_version = str(row[0])
                        break
        finally:
            connection.close()
    except sqlite3.DatabaseError as exc:
        raise DatabaseConfigurationError(f"eggnog.db is not a valid readable SQLite database: {exc}") from exc
    return {
        "name": "eggNOG",
        "expected_major_version": "5",
        "detected_version": detected_version,
        "files": files,
    }


def eggnog_command(
    proteins: Path, output_dir: Path, prefix: str, config: PipelineConfig
) -> list[str]:
    """Build the pinned DIAMOND-mode eggNOG-mapper command."""
    tool = config.value("tools", "eggnog")
    return [
        str(tool["executable"]),
        *[str(item) for item in tool.get("prefix_options", [])],
        "-i", str(proteins),
        *[str(item) for item in tool.get("options", [])],
        "-m", str(tool["search_mode"]),
        "--data_dir", str(config.eggnog_path("data_dir")),
        "--cpu", str(config.threads),
        "--output", prefix,
        "--output_dir", str(output_dir),
    ]


def run_eggnog(
    proteins: Path,
    raw_dir: Path,
    sample_id: str,
    config: PipelineConfig,
    runner: CommandRunner,
    warnings: list[str],
) -> Path:
    """Run eggNOG-mapper and record optional-file availability."""
    runner.run(
        eggnog_command(proteins, raw_dir, sample_id, config),
        tool="eggNOG-mapper",
        log_path=raw_dir.parent / "logs" / "eggnog.log",
    )
    annotations = raw_dir / f"{sample_id}.emapper.annotations"
    if not runner.dry_run:
        if not annotations.is_file() or annotations.stat().st_size == 0:
            raise ParseError(f"eggNOG annotations are missing or empty: {annotations}")
        for suffix in ("seed_orthologs", "hits"):
            optional = raw_dir / f"{sample_id}.emapper.{suffix}"
            if not optional.is_file():
                warnings.append(
                    f"Optional eggNOG-mapper output was not generated: {optional.name}"
                )
    return annotations


def parse_annotations(path: Path) -> tuple[list[str], list[dict[str, str]]]:
    """Parse a dynamic ``#query`` header and preserve every source column."""
    header: list[str] | None = None
    data_lines: list[str] = []
    try:
        with path.open("r", encoding="utf-8-sig") as handle:
            for raw in handle:
                line = raw.rstrip("\r\n")
                if not line:
                    continue
                if line.startswith("##"):
                    continue
                if line.startswith("#"):
                    candidate = line[1:].split("\t")
                    if candidate and candidate[0].strip().lower() == "query":
                        header = [item.strip() for item in candidate]
                    continue
                data_lines.append(line)
    except OSError as exc:
        raise ParseError(f"Cannot read eggNOG annotations: {path}") from exc
    if header is None:
        raise ParseError(f"eggNOG annotations have no #query header: {path}")
    reader = csv.DictReader(data_lines, fieldnames=header, delimiter="\t")
    rows = [
        {field: str(row.get(field, "") or "") for field in header}
        for row in reader
    ]
    return header, rows


def _terms(value: str, namespace: str) -> Iterable[str]:
    value = value.strip()
    if not value or value == "-":
        return ()
    if namespace == "COG_CATEGORY":
        return tuple(char for char in value if char.isalnum())
    return tuple(
        item.strip()
        for item in re.split(r"[,;]", value)
        if item.strip() and item.strip() != "-"
    )


def expand_terms(
    rows: Iterable[Mapping[str, str]], sample_id: str
) -> list[dict[str, str]]:
    """Expand supported namespaces into a deterministic, deduplicated long table."""
    terms: dict[tuple[str, str, str, str], dict[str, str]] = {}
    for row in rows:
        gene_id = str(row.get("query", ""))
        for source, namespace in TERM_COLUMNS.items():
            for term in _terms(str(row.get(source, "")), namespace):
                key = (gene_id, namespace, term, source)
                terms[key] = {
                    "sample_id": sample_id,
                    "gene_id": gene_id,
                    "namespace": namespace,
                    "term_id": term,
                    "term_name": "",
                    "source_column": source,
                }
    return [
        terms[key]
        for key in sorted(terms, key=lambda item: (item[0], item[1], item[2], item[3]))
    ]

# --- original module: prokka.py ---
"""Metagenome-aware Prokka orchestration."""


import shutil
from dataclasses import dataclass
from pathlib import Path



@dataclass(frozen=True)
class ProkkaResult:
    """Required Prokka outputs."""

    faa: Path
    ffn: Path
    gff: Path
    tsv: Path
    txt: Path


def prokka_command(
    assembly: Path, output_dir: Path, prefix: str, config: PipelineConfig
) -> list[str]:
    """Build a configured Prokka command and enforce metagenome mode."""
    tool = config.value("tools", "prokka")
    options = [str(item) for item in tool.get("options", [])]
    if "--metagenome" not in options:
        raise ValueError("Prokka options must include --metagenome.")
    return [
        str(tool["executable"]), *[str(item) for item in tool.get("prefix_options", [])],
        *options, "--cpus", str(config.threads), "--outdir", str(output_dir),
        "--prefix", prefix, str(assembly),
    ]


def run_prokka(
    assembly: Path,
    work_dir: Path,
    raw_dir: Path,
    sample_id: str,
    config: PipelineConfig,
    runner: CommandRunner,
) -> ProkkaResult:
    """Run Prokka, validate outputs, and retain them under raw/prokka."""
    output_dir = work_dir / "prokka"
    runner.run(
        prokka_command(assembly, output_dir, sample_id, config),
        tool="Prokka",
        log_path=work_dir.parent / "logs" / "prokka.log",
    )
    result = ProkkaResult(
        faa=output_dir / f"{sample_id}.faa",
        ffn=output_dir / f"{sample_id}.ffn",
        gff=output_dir / f"{sample_id}.gff",
        tsv=output_dir / f"{sample_id}.tsv",
        txt=output_dir / f"{sample_id}.txt",
    )
    if not runner.dry_run:
        for path in result.__dict__.values():
            if not path.is_file() or path.stat().st_size == 0:
                raise ExternalToolError(f"Prokka required output is missing or empty: {path}")
        retained = raw_dir / "prokka"
        retained.mkdir(parents=True, exist_ok=True)
        for path in result.__dict__.values():
            shutil.copy2(path, retained / path.name)
    return result

# --- original module: qc.py ---
"""Assembly and gene-prediction quality metrics."""


from pathlib import Path
from typing import Iterator, Sequence



def iter_fasta(path: Path) -> Iterator[tuple[str, str]]:
    """Yield validated FASTA identifiers and sequences."""
    identifier: str | None = None
    pieces: list[str] = []
    with open_sequence_text(path) as handle:
        for raw in handle:
            line = raw.strip()
            if not line:
                continue
            if line.startswith(">"):
                if identifier is not None:
                    yield identifier, "".join(pieces)
                identifier = line[1:].split()[0]
                pieces = []
            elif identifier is None:
                raise InputValidationError(f"Sequence before FASTA header in {path}")
            else:
                pieces.append(line)
    if identifier is not None:
        yield identifier, "".join(pieces)



def fastq_qc(paths: Sequence[Path]) -> dict[str, float | int]:
    """Count reads and bases in validated plain or gzip FASTQ files."""
    read_count = 0
    base_count = 0
    for path in paths:
        file_lines = 0
        with open_sequence_text(path) as handle:
            for file_lines, raw in enumerate(handle, start=1):
                if file_lines % 4 == 2:
                    sequence = raw.strip()
                    if not sequence:
                        raise InputValidationError(f"Empty FASTQ sequence in {path}")
                    read_count += 1
                    base_count += len(sequence)
        if file_lines % 4:
            raise InputValidationError(f"Incomplete FASTQ record in {path}")
    return {
        "file_count": len(paths),
        "read_count": read_count,
        "base_count": base_count,
        "mean_read_length": round(base_count / read_count, 3) if read_count else 0.0,
    }

def assembly_qc(path: Path) -> dict[str, float | int]:
    """Calculate deterministic contig count, length, N50, and GC metrics."""
    lengths: list[int] = []
    gc = 0
    total = 0
    for _, sequence in iter_fasta(path):
        length = len(sequence)
        if length:
            lengths.append(length)
            total += length
            gc += sum(1 for base in sequence.upper() if base in {"G", "C"})
    if not lengths:
        raise InputValidationError(f"Assembly contains no non-empty contigs: {path}")
    threshold = total / 2
    cumulative = 0
    n50 = 0
    for length in sorted(lengths, reverse=True):
        cumulative += length
        if cumulative >= threshold:
            n50 = length
            break
    return {
        "contig_count": len(lengths),
        "total_length": total,
        "min_contig_length": min(lengths),
        "max_contig_length": max(lengths),
        "n50": n50,
        "gc_percent": round((gc / total) * 100, 6),
    }


def count_fasta_records(path: Path) -> int:
    """Count non-empty FASTA records."""
    return sum(1 for _ in iter_fasta(path))

# --- original module: read_search.py ---
"""Direct translated-search functional annotation for quality-controlled reads."""


import re
from pathlib import Path
from typing import Any, Mapping, Sequence



DIAMOND_COLUMNS = (
    "qseqid", "sseqid", "pident", "length", "qlen", "slen", "evalue", "bitscore"
)
READ_ANNOTATION_FIELDS = (
    "accession", "supporting_reads", "mean_pct_identity",
    "mean_query_coverage", "mean_bitscore",
)


def fastq_to_fasta(reads: Sequence[Path], target: Path) -> Path:
    """Convert trimmed FASTQ files to one FASTA with collision-free query IDs."""
    target.parent.mkdir(parents=True, exist_ok=True)
    with target.open("w", encoding="utf-8", newline="\n") as output:
        for file_index, path in enumerate(reads, start=1):
            with open_sequence_text(path) as handle:
                record: list[str] = []
                record_number = 0
                for raw in handle:
                    record.append(raw.rstrip("\r\n"))
                    if len(record) != 4:
                        continue
                    header, sequence, plus, quality = record
                    if (
                        not header.startswith("@")
                        or not plus.startswith("+")
                        or not sequence
                        or len(sequence) != len(quality)
                    ):
                        raise ParseError(f"Malformed trimmed FASTQ record in {path}")
                    record_number += 1
                    original = re.sub(r"[^A-Za-z0-9_.:-]+", "_", header[1:].split()[0])
                    query = f"R{file_index}_{record_number}_{original or 'read'}"
                    output.write(f">{query}\n{sequence}\n")
                    record = []
                if record:
                    raise ParseError(f"Incomplete trimmed FASTQ record in {path}")
    return target


def diamond_command(query: Path, output: Path, config: PipelineConfig) -> list[str]:
    """Build DIAMOND blastx against the deployed eggNOG protein database."""
    tool = config.value("tools", "reads_search")
    database = config.eggnog_path("data_dir") / "eggnog_proteins.dmnd"
    return [
        str(tool["executable"]),
        *[str(item) for item in tool.get("prefix_options", [])],
        "blastx",
        "--db", str(database),
        "--query", str(query),
        "--out", str(output),
        "--outfmt", "6", *DIAMOND_COLUMNS,
        "--max-target-seqs", "1",
        "--threads", str(config.threads),
        "--evalue", str(tool["evalue"]),
        "--id", str(tool["min_identity"]),
        "--query-cover", str(tool["min_query_coverage"]),
        *[str(item) for item in tool.get("options", [])],
    ]


def run_diamond(
    query: Path, output: Path, config: PipelineConfig, runner: CommandRunner
) -> Path:
    """Run the translated search and require its output file to exist."""
    runner.run(
        diamond_command(query, output, config),
        tool="DIAMOND blastx",
        log_path=output.parent.parent / "logs" / "diamond.log",
    )
    if not runner.dry_run and not output.is_file():
        raise ExternalToolError(f"DIAMOND completed without its result file: {output}")
    return output


def parse_diamond(path: Path) -> dict[str, dict[str, Any]]:
    """Parse the best hit for each uniquely named read and validate every field."""
    hits: dict[str, dict[str, Any]] = {}
    try:
        handle = path.open("r", encoding="utf-8-sig")
    except OSError as exc:
        raise ParseError(f"Cannot read DIAMOND output: {path}") from exc
    with handle:
        for line_number, raw in enumerate(handle, start=1):
            if not raw.strip():
                continue
            fields = raw.rstrip("\r\n").split("\t")
            if len(fields) != len(DIAMOND_COLUMNS):
                raise ParseError(
                    f"DIAMOND line {line_number} has {len(fields)} columns; "
                    f"expected {len(DIAMOND_COLUMNS)}."
                )
            row = dict(zip(DIAMOND_COLUMNS, fields))
            try:
                length = int(row["length"])
                query_length = int(row["qlen"])
                identity = float(row["pident"])
                evalue = float(row["evalue"])
                bitscore = float(row["bitscore"])
            except ValueError as exc:
                raise ParseError(f"DIAMOND line {line_number} has invalid numeric data.") from exc
            if length <= 0 or query_length <= 0:
                raise ParseError(f"DIAMOND line {line_number} has invalid sequence lengths.")
            hits[row["qseqid"]] = {
                "subject": row["sseqid"],
                "identity": identity,
                "query_coverage": min(100.0, 100.0 * length * 3 / query_length),
                "evalue": evalue,
                "bitscore": bitscore,
            }
    return hits


def write_seed_orthologs(
    path: Path, hits: Mapping[str, Mapping[str, Any]]
) -> Path:
    """Write eggNOG-mapper's required four-column seed-ortholog table."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        for query in sorted(hits):
            hit = hits[query]
            handle.write(
                f"{query}\t{hit['subject']}\t{hit['evalue']}\t{hit['bitscore']}\n"
            )
    return path


def annotation_command(
    seed_table: Path, output_dir: Path, prefix: str, config: PipelineConfig
) -> list[str]:
    """Build eggNOG-mapper's documented no-search annotation command."""
    tool = config.value("tools", "eggnog")
    return [
        str(tool["executable"]),
        *[str(item) for item in tool.get("prefix_options", [])],
        "-m", "no_search",
        "--annotate_hits_table", str(seed_table),
        "--data_dir", str(config.eggnog_path("data_dir")),
        "--cpu", str(config.threads),
        "--output", prefix,
        "--output_dir", str(output_dir),
        "--override",
    ]


def run_annotation(
    seed_table: Path,
    output_dir: Path,
    prefix: str,
    config: PipelineConfig,
    runner: CommandRunner,
) -> Path:
    """Annotate DIAMOND seed orthologs with the deployed eggNOG metadata."""
    runner.run(
        annotation_command(seed_table, output_dir, prefix, config),
        tool="eggNOG-mapper annotation",
        log_path=output_dir.parent / "logs" / "eggnog_reads.log",
    )
    annotations = output_dir / f"{prefix}.emapper.annotations"
    if not runner.dry_run and (not annotations.is_file() or annotations.stat().st_size == 0):
        raise ExternalToolError(
            f"eggNOG-mapper completed without annotations: {annotations}"
        )
    return annotations


def aggregate_annotations(
    header: Sequence[str],
    rows: Sequence[Mapping[str, str]],
    hits: Mapping[str, Mapping[str, Any]],
) -> tuple[list[str], list[dict[str, Any]]]:
    """Aggregate read annotations by real eggNOG seed-ortholog accession."""
    grouped: dict[str, dict[str, Any]] = {}
    for source in rows:
        read_id = str(source.get("query", ""))
        hit = hits.get(read_id, {})
        accession = str(source.get("seed_ortholog", "") or hit.get("subject", ""))
        if not accession:
            raise ParseError(f"eggNOG read annotation has no seed ortholog: {read_id}")
        item = grouped.setdefault(
            accession,
            {
                "row": {field: str(source.get(field, "")) for field in header},
                "reads": set(),
                "identities": [],
                "coverages": [],
                "bitscores": [],
            },
        )
        for field in header:
            if not item["row"].get(field) and source.get(field):
                item["row"][field] = str(source[field])
        item["reads"].add(read_id)
        if hit:
            item["identities"].append(float(hit["identity"]))
            item["coverages"].append(float(hit["query_coverage"]))
            item["bitscores"].append(float(hit["bitscore"]))
    output: list[dict[str, Any]] = []
    for accession, item in sorted(grouped.items()):
        row = item["row"]
        row["query"] = accession
        row["accession"] = accession
        row["supporting_reads"] = len(item["reads"])
        row["mean_pct_identity"] = (
            round(sum(item["identities"]) / len(item["identities"]), 3)
            if item["identities"] else ""
        )
        row["mean_query_coverage"] = (
            round(sum(item["coverages"]) / len(item["coverages"]), 3)
            if item["coverages"] else ""
        )
        row["mean_bitscore"] = (
            round(sum(item["bitscores"]) / len(item["bitscores"]), 3)
            if item["bitscores"] else ""
        )
        output.append(row)
    output_header = list(header)
    for field in READ_ANNOTATION_FIELDS:
        if field not in output_header:
            output_header.append(field)
    return output_header, output

# --- original module: doctor.py ---
"""Read-only BacFunc deployment diagnostics."""


import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any



def _item(level: str, name: str, message: str) -> dict[str, str]:
    return {"level": level, "name": name, "message": message}


def _executable(executable: str, prefix_options: list[str]) -> tuple[bool, str]:
    located = shutil.which(executable)
    if located is None and Path(executable).is_file():
        located = str(Path(executable).resolve())
    if located is None:
        return False, f"not found: {executable}"
    try:
        completed = subprocess.run(
            [located, *prefix_options, "--version"],
            stdin=subprocess.DEVNULL,
            capture_output=True,
            text=True,
            check=False,
            shell=False,
            timeout=10,
        )
        lines = (completed.stdout or completed.stderr).strip().splitlines()
        detail = lines[0][:300] if lines else "version output unavailable"
    except (OSError, subprocess.SubprocessError) as exc:
        detail = f"located; version probe warning: {exc}"
    return True, f"{located} ({detail})"


def run_doctor(config_path: Path | None = None, output: Path | None = None) -> dict[str, Any]:
    """Check Python, configuration, tools, four eggNOG files, and output writes."""
    checks = [
        _item(
            "ok" if sys.version_info >= (3, 9) else "error",
            "python",
            sys.version.split()[0],
        )
    ]
    try:
        config = load_config(config_path)
        checks.append(_item("ok", "configuration", str(config.source)))
        for name in ("trimmomatic", "reads_search", "assembler", "prokka", "eggnog"):
            section = config.value("tools", name)
            ok, message = _executable(
                str(section["executable"]),
                [str(value) for value in section.get("prefix_options", [])],
            )
            checks.append(_item("ok" if ok else "error", f"executable:{name}", message))
        try:
            info = validate_database_path(config.eggnog_path("data_dir"))
            checks.append(
                _item(
                    "ok",
                    "database",
                    f"eggNOG detected version: {info['detected_version']}",
                )
            )
        except Exception as exc:
            checks.append(_item("error", "database", str(exc)))
    except Exception as exc:
        checks.append(_item("error", "configuration", str(exc)))
    target = (output or Path.cwd()).expanduser().resolve()
    try:
        target.mkdir(parents=True, exist_ok=True)
        descriptor, name = tempfile.mkstemp(prefix=".bacfunc-doctor-", dir=target)
        os.close(descriptor)
        Path(name).unlink()
        checks.append(_item("ok", "output_write", str(target)))
    except OSError as exc:
        checks.append(_item("error", "output_write", str(exc)))
    errors = sum(check["level"] == "error" for check in checks)
    warnings = sum(check["level"] == "warning" for check in checks)
    return {
        "project": "bacfunc",
        "version": __version__,
        "ok": errors == 0,
        "error_count": errors,
        "warning_count": warnings,
        "checks": checks,
    }

# --- original module: pipeline.py ---
"""End-to-end BacFunc orchestration."""


import shutil
from pathlib import Path
from typing import Any, Sequence



def _write_status(
    output: Path,
    status: str,
    sample_id: str,
    input_type: str,
    analysis_mode: str,
    dry_run: bool,
    warnings: list[str],
    **extra: Any,
) -> None:
    payload: dict[str, Any] = {
        "schema_version": "1.1",
        "status": status,
        "pipeline": "bacfunc",
        "pipeline_version": __version__,
        "sample_id": sample_id,
        "input_type": input_type,
        "analysis_mode": analysis_mode,
        "dry_run": dry_run,
        "warnings": warnings,
    }
    payload.update(extra)
    write_json(output / "status.json", payload)


def run_pipeline(
    inputs: Sequence[Path],
    output: Path,
    *,
    sample_id: str | None = None,
    config_path: Path | None = None,
    dry_run: bool = False,
    threads: int | None = None,
    input_type: str = "auto",
    analysis_mode: str = "auto",
) -> dict[str, Any]:
    """Run gene-level eggNOG annotation without aggregation or abundance."""
    output = Path(output).expanduser().resolve()
    validated: InputSet = validate_inputs(
        inputs,
        output,
        sample_id,
        input_type=input_type,
        analysis_mode=analysis_mode,
    )
    output.mkdir(parents=True, exist_ok=True)
    raw_dir, logs_dir, work_dir = output / "raw", output / "logs", output / "work"
    for directory in (raw_dir, logs_dir, work_dir):
        directory.mkdir(parents=True, exist_ok=True)
    warnings: list[str] = []
    started = utc_now()
    pipeline_log = logs_dir / "pipeline.log"
    pipeline_log.write_text(f"START bacfunc {started}\n", encoding="utf-8")
    runner = CommandRunner(dry_run=dry_run)
    _write_status(
        output,
        "running",
        validated.sample_id,
        validated.input_type,
        validated.analysis_mode,
        dry_run,
        warnings,
    )
    try:
        config = load_config(config_path)
        if threads is not None:
            from dataclasses import replace
            config = replace(config, threads=threads)
        deployed_manifest = database_manifest(
            config.eggnog_path("manifest", required=False), warnings
        )
        if config.value("runtime", "strict_manifest", required=False) and deployed_manifest is None:
            raise RuntimeError("A database manifest is required by runtime.strict_manifest.")
        database_info: dict[str, Any] | None = None
        if not dry_run:
            database_info = validate_database_path(config.eggnog_path("data_dir"))
        assembly_source = "not_applicable"
        assembly_metrics: dict[str, Any] = {}
        protein_count: int | None = None
        reads_metrics: dict[str, Any] = {}
        if validated.analysis_mode == "reads":
            prepared = prepare_reads(validated, work_dir, config, runner)
            reads_fasta = work_dir / "reads" / "trimmed_reads.fasta"
            if not dry_run:
                fastq_to_fasta(prepared.trimmed_reads, reads_fasta)
            diamond_path = raw_dir / "reads_diamond.tsv"
            run_diamond(reads_fasta, diamond_path, config, runner)
            seed_path = raw_dir / "reads.emapper.seed_orthologs"
            if dry_run:
                annotations_path = run_annotation(
                    seed_path, raw_dir, validated.sample_id, config, runner
                )
                header = ["query", *READ_ANNOTATION_FIELDS]
                gene_rows: list[dict[str, Any]] = []
                term_rows: list[dict[str, str]] = []
            else:
                diamond_hits = parse_diamond(diamond_path)
                write_seed_orthologs(seed_path, diamond_hits)
                if diamond_hits:
                    annotations_path = run_annotation(
                        seed_path, raw_dir, validated.sample_id, config, runner
                    )
                    source_header, source_rows = parse_annotations(annotations_path)
                    header, gene_rows = aggregate_annotations(
                        source_header, source_rows, diamond_hits
                    )
                    if not gene_rows:
                        warnings.append("eggNOG annotations contain no read-level rows.")
                else:
                    header = ["query", *READ_ANNOTATION_FIELDS]
                    gene_rows = []
                    warnings.append("DIAMOND found no reads passing the configured thresholds.")
                term_rows = expand_terms(gene_rows, validated.sample_id)
                raw_read_metrics = fastq_qc(validated.files)
                trimmed_read_metrics = fastq_qc(prepared.trimmed_reads)
                raw_count = int(raw_read_metrics["read_count"])
                reads_metrics = {
                    "raw": raw_read_metrics,
                    "trimmed": trimmed_read_metrics,
                    "retained_read_percent": round(
                        100.0 * int(trimmed_read_metrics["read_count"]) / raw_count, 3
                    ) if raw_count else 0.0,
                }
        else:
            assembly = prepare_assembly(validated, work_dir, config, runner)
            assembly_source = assembly.source
            assembly_metrics = assembly_qc(assembly.path) if assembly.path.is_file() else {}
            prokka = run_prokka(
                assembly.path, work_dir, raw_dir, validated.sample_id, config, runner
            )
            annotations_path = run_eggnog(
                prokka.faa, raw_dir, validated.sample_id, config, runner, warnings
            )
            if dry_run:
                header = ["query"]
                gene_rows = []
                term_rows = []
            else:
                header, gene_rows = parse_annotations(annotations_path)
                if not gene_rows:
                    warnings.append("eggNOG annotations contain a header but no gene rows.")
                term_rows = expand_terms(gene_rows, validated.sample_id)
                protein_count = count_fasta_records(prokka.faa)
        if dry_run:
            warnings.append("Dry-run planned commands; biological outputs were not executed.")
        wide_fields = ["sample_id", *header]
        wide_rows = [{"sample_id": validated.sample_id, **row} for row in gene_rows]
        write_tsv(output / "gene_annotations.tsv", wide_rows, wide_fields)
        write_tsv(output / "annotation_terms.tsv", term_rows, TERM_FIELDS)
        qc: dict[str, Any] = {
            "schema_version": "1.1",
            "analysis_mode": validated.analysis_mode,
            "input": {
                "type": validated.input_type,
                "paired": validated.paired,
                "file_count": len(validated.files),
                "compressed": list(validated.compressed),
            },
            "assembly": {"source": assembly_source, **assembly_metrics},
            "gene_prediction": {"status": "not_applicable"} if validated.analysis_mode == "reads" else {},
            "reads": reads_metrics,
            "annotation": {
                "gene_annotation_count": len(gene_rows),
                "term_count": len(term_rows),
            },
            "warnings": warnings,
        }
        if protein_count is not None:
            qc["gene_prediction"]["protein_count"] = protein_count
        write_json(output / "qc.json", qc)
        if validated.analysis_mode == "reads":
            tool_names = ("trimmomatic", "reads_search", "eggnog")
            search = config.value("tools", "reads_search")
            scientific_parameters = {
                "eggnog_mapper_version": config.value("tools", "eggnog", "version"),
                "search_mode": "diamond_blastx_then_no_search_annotation",
                "evalue": search["evalue"],
                "min_identity": search["min_identity"],
                "min_query_coverage": search["min_query_coverage"],
                "diamond_options": search.get("options", []),
                "trimmomatic_options": config.value("tools", "trimmomatic", "options"),
            }
        else:
            tool_names = ("trimmomatic", "assembler", "prokka", "eggnog")
            scientific_parameters = {
                "eggnog_mapper_version": config.value("tools", "eggnog", "version"),
                "search_mode": config.value("tools", "eggnog", "search_mode"),
                "trimmomatic_options": config.value("tools", "trimmomatic", "options"),
                "assembler_options": config.value("tools", "assembler", "options"),
                "prokka_options": config.value("tools", "prokka", "options"),
            }
        tool_records = {}
        for name in tool_names:
            section = config.value("tools", name)
            detected = "not_probed_dry_run" if dry_run else probe_version(
                section["executable"], section.get("prefix_options", [])
            )
            tool_records[name] = {
                "executable": str(section["executable"]),
                "version": detected,
            }
        manifest = {
            "schema_version": "1.1",
            "pipeline": "bacfunc",
            "pipeline_version": __version__,
            "started_at_utc": started,
            "ended_at_utc": utc_now(),
            "sample_id": validated.sample_id,
            "input_type": validated.input_type,
            "analysis_mode": validated.analysis_mode,
            "inputs": input_records(validated.files),
            "assembly_source": assembly_source,
            "threads": config.threads,
            "commands": render_commands(runner.commands),
            "tools": tool_records,
            "database": database_info
            or {"name": "eggNOG", "validation": "skipped_in_dry_run"},
            "database_manifest": deployed_manifest,
            "scientific_parameters": scientific_parameters,
            "runtime": runtime_record(),
            "warnings": warnings,
            "outputs": [
                "gene_annotations.tsv", "annotation_terms.tsv", "status.json",
                "manifest.json", "qc.json",
            ],
            "dry_run": dry_run,
        }
        write_json(output / "manifest.json", manifest)
        status = {
            "schema_version": "1.1",
            "status": "success",
            "pipeline": "bacfunc",
            "pipeline_version": __version__,
            "sample_id": validated.sample_id,
            "input_type": validated.input_type,
            "analysis_mode": validated.analysis_mode,
            "gene_annotation_count": len(gene_rows),
            "term_count": len(term_rows),
            "dry_run": dry_run,
            "warnings": warnings,
        }
        write_json(output / "status.json", status)
        with pipeline_log.open("a", encoding="utf-8", newline="\n") as handle:
            handle.write(f"END bacfunc success {utc_now()}\n")
        if config.value("runtime", "keep_work", required=False) is False and not dry_run:
            shutil.rmtree(work_dir)
        return status
    except Exception as exc:
        _write_status(
            output,
            "failed",
            validated.sample_id,
            validated.input_type,
            validated.analysis_mode,
            dry_run,
            warnings,
            error_type=type(exc).__name__,
            message=str(exc),
        )
        with pipeline_log.open("a", encoding="utf-8", newline="\n") as handle:
            handle.write(f"END bacfunc failed {utc_now()} {type(exc).__name__}: {exc}\n")
        raise

# --- original module: batch.py ---
"""Independent per-sample batch orchestration."""


from pathlib import Path
from typing import Any, Sequence



def run_samples(
    samples: Sequence[InputSet],
    output: Path,
    *,
    config_path: Path | None = None,
    dry_run: bool = False,
    threads: int | None = None,
) -> list[dict[str, Any]]:
    """Run one or more samples without combining their biological inputs."""
    if not samples:
        raise ValueError("At least one validated sample is required.")
    root = Path(output).expanduser().resolve()
    multiple = len(samples) > 1
    if multiple:
        root.mkdir(parents=True, exist_ok=True)
    statuses: list[dict[str, Any]] = []
    for sample in samples:
        target = root / sample.sample_id if multiple else root
        statuses.append(
            run_pipeline(
                sample.files,
                target,
                sample_id=sample.sample_id,
                config_path=config_path,
                dry_run=dry_run,
                threads=threads,
                input_type=sample.input_type,
                analysis_mode=sample.analysis_mode,
            )
        )
    return statuses

# --- original module: cli.py ---
"""BacFunc general and Agent-specific command-line entry points."""


import argparse
import json
import sys
from pathlib import Path
from typing import Sequence



def _run_arguments(parser: argparse.ArgumentParser) -> None:
    sources = parser.add_mutually_exclusive_group(required=True)
    sources.add_argument("--input", nargs="+", type=Path)
    sources.add_argument("--input-dir", type=Path)
    parser.add_argument("--input-type", choices=("auto", "reads", "genome"), default="auto")
    parser.add_argument(
        "--analysis-mode",
        choices=("auto", "reads", "genome", "assemble"),
        default="auto",
    )
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--sample-id")
    parser.add_argument("--config", type=Path)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--threads", type=int, default=8)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="bacfunc",
        description="Gene-level eggNOG-mapper annotation for metagenomes.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)
    run_parser = subparsers.add_parser("run")
    _run_arguments(run_parser)
    doctor_parser = subparsers.add_parser("doctor")
    doctor_parser.add_argument("--config", type=Path)
    doctor_parser.add_argument("--output", type=Path)
    doctor_parser.add_argument("--json", action="store_true", dest="as_json")
    subparsers.add_parser("version")
    return parser


def _execute_run(namespace: argparse.Namespace) -> int:
    try:
        samples = discover_samples(
            namespace.input or [],
            namespace.output,
            input_directory=namespace.input_dir,
            sample_id=namespace.sample_id,
            input_type=namespace.input_type,
            analysis_mode=namespace.analysis_mode,
        )
        run_samples(
            samples,
            namespace.output,
            config_path=namespace.config,
            dry_run=namespace.dry_run,
            threads=namespace.threads,
        )
        return 0
    except Exception as exc:
        print(f"bacfunc: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 1


def main(argv: Sequence[str] | None = None) -> int:
    namespace = build_parser().parse_args(argv)
    if namespace.command == "version":
        print(__version__)
        return 0
    if namespace.command == "doctor":
        report = run_doctor(namespace.config, namespace.output)
        if namespace.as_json:
            print(json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True))
        else:
            for item in report["checks"]:
                print(f"[{item['level'].upper()}] {item['name']}: {item['message']}")
            print("READY" if report["ok"] else "NOT READY")
        return 0 if report["ok"] else 1
    return _execute_run(namespace)


def fasta_main(argv: Sequence[str] | None = None) -> int:
    """FASTA-only Agent entry point."""
    parser = argparse.ArgumentParser(prog="bacfunc-fasta")
    parser.add_argument("--assembly", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--sample-id")
    parser.add_argument("--config", type=Path)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--threads", type=int, default=8)
    namespace = parser.parse_args(argv)
    namespace.input = [namespace.assembly]
    namespace.input_dir = None
    namespace.input_type = "genome"
    namespace.analysis_mode = "genome"
    return _execute_run(namespace)


def fastq_main(argv: Sequence[str] | None = None) -> int:
    """FASTQ-only Agent entry point with explicit R1/R2 roles."""
    parser = argparse.ArgumentParser(prog="bacfunc-fastq")
    parser.add_argument("--read1", required=True, type=Path)
    parser.add_argument("--read2", type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--sample-id")
    parser.add_argument("--config", type=Path)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--analysis-mode", choices=("assemble", "reads"), default="assemble")
    parser.add_argument("--threads", type=int, default=8)
    namespace = parser.parse_args(argv)
    namespace.input = [namespace.read1] + ([namespace.read2] if namespace.read2 else [])
    namespace.input_dir = None
    namespace.input_type = "reads"
    return _execute_run(namespace)


if __name__ == "__main__":
    raise SystemExit(main())
