"""BioAgent pipeline implementation. Generated by consolidating the original modules."""
from __future__ import annotations

# --- original module: __init__.py ---
"""BacARG: MEGARes 3.0 sequence-homology candidate annotation."""


__version__ = "0.2.0"

__all__ = ["__version__"]

# --- original module: errors.py ---
"""BacARG exception hierarchy."""



class BacargError(RuntimeError):
    """Base class for user-facing pipeline failures."""


class ConfigurationError(BacargError):
    """Raised when deployment configuration is invalid."""


class DatabaseConfigurationError(ConfigurationError):
    """Raised when a required database is unavailable or invalid."""


class InputValidationError(BacargError):
    """Raised when sequence input is unsafe or malformed."""


class ExternalToolError(BacargError):
    """Raised when an external command fails."""


class ParseError(BacargError):
    """Raised when an external data file cannot be parsed safely."""

# --- original module: manifest.py ---
"""Run provenance helpers."""


import hashlib
import platform
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable


def utc_now() -> str:
    """Return an ISO-8601 UTC timestamp."""
    return datetime.now(timezone.utc).isoformat()


def sha256_file(path: Path) -> str:
    """Stream a file SHA-256 without loading it into memory."""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def input_records(paths: Iterable[Path]) -> list[dict[str, Any]]:
    """Collect stable input provenance."""
    records: list[dict[str, Any]] = []
    for path in paths:
        stat = path.stat()
        records.append(
            {
                "name": path.name,
                "size": stat.st_size,
                "sha256": sha256_file(path),
            }
        )
    return records


def runtime_record() -> dict[str, str]:
    """Return Python and operating-system provenance."""
    return {
        "python_version": platform.python_version(),
        "python_implementation": platform.python_implementation(),
        "platform": platform.platform(),
        "executable_name": Path(sys.executable).name,
    }


def database_manifest(path: Path | None, warnings: list[str]) -> dict[str, Any] | None:
    """Record a deployment manifest or a warning-backed file summary."""
    if path is None:
        warnings.append("Database manifest is not configured; strict provenance is unavailable.")
        return None
    if not path.is_file():
        warnings.append(f"Database manifest is missing: {path.name}")
        return None
    import json

    try:
        with path.open("r", encoding="utf-8") as handle:
            payload = json.load(handle)
    except (OSError, json.JSONDecodeError) as exc:
        warnings.append(f"Database manifest could not be read: {exc}")
        return None
    return payload if isinstance(payload, dict) else {"content": payload}

# --- original module: outputs.py ---
"""Atomic deterministic result writers."""


import csv
import json
import os
import tempfile
from pathlib import Path
from typing import Iterable, Mapping, Sequence


def _temporary(path: Path) -> tuple[int, Path]:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    return descriptor, Path(name)


def write_json(path: Path, payload: object) -> None:
    """Atomically write stable UTF-8 JSON."""
    descriptor, temporary = _temporary(path)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            json.dump(payload, handle, ensure_ascii=False, indent=2, sort_keys=True)
            handle.write("\n")
        temporary.replace(path)
    except Exception:
        temporary.unlink(missing_ok=True)
        raise


def write_tsv(
    path: Path, rows: Iterable[Mapping[str, object]], fields: Sequence[str]
) -> None:
    """Atomically write a TSV with an explicit stable column order."""
    descriptor, temporary = _temporary(path)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="") as handle:
            writer = csv.DictWriter(
                handle, fieldnames=list(fields), delimiter="\t", lineterminator="\n"
            )
            writer.writeheader()
            for row in rows:
                writer.writerow({field: row.get(field, "") for field in fields})
        temporary.replace(path)
    except Exception:
        temporary.unlink(missing_ok=True)
        raise


def write_jsonl(path: Path, rows: Iterable[Mapping[str, object]]) -> None:
    """Atomically write deterministic JSON Lines."""
    descriptor, temporary = _temporary(path)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            for row in rows:
                handle.write(json.dumps(dict(row), ensure_ascii=False, sort_keys=True))
                handle.write("\n")
        temporary.replace(path)
    except Exception:
        temporary.unlink(missing_ok=True)
        raise

# --- original module: versions.py ---
"""Small, bounded external-tool version probes for provenance."""


import subprocess
from typing import Sequence


def probe_version(executable: object, prefix_options: Sequence[object] = ()) -> str:
    """Return the first version line, or an explicit unavailable marker."""
    try:
        completed = subprocess.run(
            [str(executable), *[str(item) for item in prefix_options], "--version"],
            stdin=subprocess.DEVNULL,
            capture_output=True,
            text=True,
            shell=False,
            check=False,
            timeout=15,
        )
    except (OSError, subprocess.SubprocessError):
        return "unavailable"
    if completed.returncode != 0:
        return "unavailable"
    lines = [
        line.strip()
        for line in (completed.stdout + "\n" + completed.stderr).splitlines()
        if line.strip()
    ]
    return lines[0][:500] if lines else "unavailable"

# --- original module: command.py ---
"""Safe external command execution with auditable argument boundaries."""


import json
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, Optional, Sequence



@dataclass
class CommandRunner:
    """Execute or plan subprocess calls without a shell."""

    dry_run: bool = False
    commands: list[list[str]] = field(default_factory=list)

    def run(
        self,
        command: Sequence[object],
        *,
        tool: str,
        log_path: Path,
        stdout_path: Optional[Path] = None,
    ) -> int:
        """Run one command and stream output directly to files."""
        args = [str(part) for part in command]
        if not args:
            raise ExternalToolError(f"{tool} command is empty.")
        self.commands.append(args)
        log_path.parent.mkdir(parents=True, exist_ok=True)
        with log_path.open("a", encoding="utf-8", newline="\n") as log:
            log.write(f"START {tool}\n")
            log.write("COMMAND " + json.dumps(args, ensure_ascii=False) + "\n")
            if self.dry_run:
                log.write(f"END {tool} dry-run\n")
                return 0
            output_handle = None
            try:
                if stdout_path is not None:
                    stdout_path.parent.mkdir(parents=True, exist_ok=True)
                    output_handle = stdout_path.open("w", encoding="utf-8", newline="\n")
                completed = subprocess.run(
                    args,
                    stdin=subprocess.DEVNULL,
                    stdout=output_handle if output_handle is not None else log,
                    stderr=log,
                    check=False,
                    shell=False,
                    text=True,
                )
            except OSError as exc:
                log.write(f"ERROR {exc}\n")
                raise ExternalToolError(
                    f"{tool} could not be started; see log: {log_path}"
                ) from exc
            finally:
                if output_handle is not None:
                    output_handle.close()
            log.write(f"EXIT_CODE {completed.returncode}\n")
            log.write(f"END {tool}\n")
        if completed.returncode != 0:
            raise ExternalToolError(
                f"{tool} failed with exit code {completed.returncode}; see log: {log_path}"
            )
        return completed.returncode


def render_commands(commands: Iterable[Sequence[str]]) -> list[list[str]]:
    """Return JSON-safe command argument lists."""
    return [[str(part) for part in command] for command in commands]

# --- original module: config.py ---
"""Configuration discovery, expansion, validation, and path resolution."""


import os
import re
from copy import deepcopy
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, MutableMapping, Optional

import yaml



PROJECT_NAME = "bacarg"
CONFIG_ENV = "BACARG_CONFIG"
DATABASE_ENVIRON = {
    "BACARG_ABRICATE_DATADIR": ("databases", "abricate_datadir"),
    "BACARG_MEGARES_METADATA": ("databases", "metadata"),
    "BACARG_MEGARES_MANIFEST": ("databases", "manifest"),
}
_ENV_PATTERN = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}")


@dataclass(frozen=True)
class PipelineConfig:
    """Fully expanded immutable view of one YAML configuration."""

    data: Mapping[str, Any]
    source: Path
    threads: int

    def section(self, name: str) -> Mapping[str, Any]:
        """Return a required top-level mapping."""
        value = self.data.get(name)
        if not isinstance(value, Mapping):
            raise ConfigurationError(f"Configuration section '{name}' must be a mapping.")
        return value

    def value(self, *keys: str, required: bool = True) -> Any:
        """Read a nested value with a clear error for absent keys."""
        current: Any = self.data
        for key in keys:
            if not isinstance(current, Mapping) or key not in current:
                if required:
                    raise ConfigurationError(
                        f"Missing configuration value: {'.'.join(keys)}"
                    )
                return None
            current = current[key]
        return current

    def database_path(self, key: str, required: bool = True) -> Optional[Path]:
        """Return a normalized database path."""
        value = self.value("databases", key, required=required)
        if value in (None, ""):
            if required:
                labels = {
                    "abricate_datadir": (
                        "MEGARes ABRicate database path is not configured. "
                        "Set BACARG_ABRICATE_DATADIR or databases.abricate_datadir."
                    ),
                    "metadata": (
                        "MEGARes metadata path is not configured. "
                        "Set BACARG_MEGARES_METADATA or databases.metadata."
                    ),
                }
                raise DatabaseConfigurationError(labels.get(key, f"{key} is not configured."))
            return None
        return Path(str(value))


def _deep_merge(base: MutableMapping[str, Any], update: Mapping[str, Any]) -> None:
    for key, value in update.items():
        if isinstance(value, Mapping) and isinstance(base.get(key), MutableMapping):
            _deep_merge(base[key], value)
        else:
            base[key] = deepcopy(value)


def _expand_string(value: str) -> str:
    missing = sorted({name for name in _ENV_PATTERN.findall(value) if name not in os.environ})
    if missing:
        joined = ", ".join(missing)
        raise ConfigurationError(f"Unset environment variable(s) in configuration: {joined}")
    expanded = _ENV_PATTERN.sub(lambda match: os.environ[match.group(1)], value)
    if _ENV_PATTERN.search(expanded):
        raise ConfigurationError(f"Unexpanded environment variable in value: {value}")
    return os.path.expanduser(expanded)


def _expand_tree(value: Any) -> Any:
    if isinstance(value, str):
        return _expand_string(value)
    if isinstance(value, list):
        return [_expand_tree(item) for item in value]
    if isinstance(value, Mapping):
        return {key: _expand_tree(item) for key, item in value.items()}
    return value


def _set_nested(data: MutableMapping[str, Any], keys: tuple[str, ...], value: Any) -> None:
    current = data
    for key in keys[:-1]:
        child = current.setdefault(key, {})
        if not isinstance(child, MutableMapping):
            raise ConfigurationError(f"Cannot apply environment override to {'.'.join(keys)}")
        current = child
    current[keys[-1]] = value


def _read_yaml(path: Path) -> dict[str, Any]:
    try:
        with path.open("r", encoding="utf-8") as handle:
            loaded = yaml.safe_load(handle) or {}
    except OSError as exc:
        raise ConfigurationError(f"Cannot read configuration file: {path}") from exc
    except yaml.YAMLError as exc:
        raise ConfigurationError(f"Invalid YAML configuration: {path}: {exc}") from exc
    if not isinstance(loaded, dict):
        raise ConfigurationError(f"Configuration root must be a mapping: {path}")
    return loaded


def discover_config(explicit: Optional[Path] = None, cwd: Optional[Path] = None) -> Path:
    """Apply the documented five-level configuration precedence."""
    project_root = Path(__file__).resolve().parents[1]
    package_default = Path(__file__).resolve().parent / "default_config.yaml"
    candidates: list[Path] = []
    if explicit is not None:
        candidates.append(Path(explicit))
    elif os.environ.get(CONFIG_ENV):
        candidates.append(Path(_expand_string(os.environ[CONFIG_ENV])))
    else:
        candidates.extend([(cwd or Path.cwd()) / "config.yaml", project_root / "config.yaml"])
        candidates.append(package_default)
    for candidate in candidates:
        expanded = Path(os.path.expanduser(str(candidate))).resolve()
        if expanded.is_file():
            return expanded
        if explicit is not None or os.environ.get(CONFIG_ENV):
            raise ConfigurationError(f"Configuration file does not exist: {expanded}")
    raise ConfigurationError("No configuration file was found.")


def _resolve_database_paths(data: MutableMapping[str, Any], source: Path) -> None:
    databases = data.setdefault("databases", {})
    if not isinstance(databases, MutableMapping):
        raise ConfigurationError("Configuration section 'databases' must be a mapping.")
    for key in ("abricate_datadir", "metadata", "manifest"):
        value = databases.get(key)
        if value in (None, ""):
            continue
        path = Path(str(value))
        if not path.is_absolute():
            path = source.parent / path
        databases[key] = str(path.resolve())


def _validate(data: Mapping[str, Any]) -> int:
    pipeline = data.get("pipeline", {})
    if not isinstance(pipeline, Mapping):
        raise ConfigurationError("Configuration section 'pipeline' must be a mapping.")
    if pipeline.get("sample_type") != "metagenome":
        raise ConfigurationError("pipeline.sample_type must be 'metagenome'.")
    raw_threads = pipeline.get("threads", "auto")
    if raw_threads == "auto":
        threads = max(1, os.cpu_count() or 1)
    else:
        try:
            threads = int(raw_threads)
        except (TypeError, ValueError) as exc:
            raise ConfigurationError("pipeline.threads must be 'auto' or a positive integer.") from exc
        if threads < 1:
            raise ConfigurationError("pipeline.threads must be at least 1.")
    tools = data.get("tools", {})
    if not isinstance(tools, Mapping):
        raise ConfigurationError("Configuration section 'tools' must be a mapping.")
    assembler = tools.get("assembler", {})
    assembler_options = [str(item) for item in assembler.get("options", [])]
    if any(item.lstrip("-").lower() == "isolate" for item in assembler_options):
        raise ConfigurationError("Metagenome assembly configuration must not enable isolate mode.")
    prokka_options = [str(item) for item in tools.get("prokka", {}).get("options", [])]
    if "--metagenome" not in prokka_options:
        raise ConfigurationError("Prokka configuration must include --metagenome.")
    return threads


def load_config(explicit: Optional[Path] = None, cwd: Optional[Path] = None) -> PipelineConfig:
    """Load, expand, normalize, and validate one configuration."""
    source = discover_config(explicit, cwd)
    data: dict[str, Any] = _read_yaml(source)
    for variable, keys in DATABASE_ENVIRON.items():
        if os.environ.get(variable):
            _set_nested(data, keys, os.environ[variable])
    data = _expand_tree(data)
    _resolve_database_paths(data, source)
    threads = _validate(data)
    data.setdefault("pipeline", {})["resolved_threads"] = threads
    return PipelineConfig(data=data, source=source, threads=threads)

# --- original module: gff.py ---
"""Prokka GFF overlap context for contig-level hits."""


from pathlib import Path
from typing import Any, Iterable, Mapping
from urllib.parse import unquote



def _attributes(value: str) -> dict[str, str]:
    result: dict[str, str] = {}
    for part in value.split(";"):
        if "=" in part:
            key, item = part.split("=", 1)
            result[key] = unquote(item)
    return result


def load_cds(path: Path) -> dict[str, list[dict[str, Any]]]:
    """Load Prokka CDS intervals grouped by contig."""
    grouped: dict[str, list[dict[str, Any]]] = {}
    try:
        with path.open("r", encoding="utf-8") as handle:
            for line_number, line in enumerate(handle, start=1):
                if line.startswith("##FASTA"):
                    break
                if not line.strip() or line.startswith("#"):
                    continue
                fields = line.rstrip("\n").split("\t")
                if len(fields) != 9:
                    raise ParseError(f"Malformed GFF line {line_number}: {path}")
                if fields[2] != "CDS":
                    continue
                attrs = _attributes(fields[8])
                grouped.setdefault(fields[0], []).append(
                    {
                        "start": int(fields[3]),
                        "end": int(fields[4]),
                        "locus_tag": attrs.get("locus_tag", attrs.get("ID", "")),
                        "gene": attrs.get("gene", ""),
                        "product": attrs.get("product", ""),
                    }
                )
    except OSError as exc:
        raise ParseError(f"Cannot read Prokka GFF: {path}") from exc
    for values in grouped.values():
        values.sort(key=lambda item: (item["start"], item["end"], item["locus_tag"]))
    return grouped


def add_context(
    hits: Iterable[Mapping[str, Any]], cds: Mapping[str, list[Mapping[str, Any]]]
) -> list[dict[str, Any]]:
    """Add the maximum-overlap Prokka locus context to each hit."""
    result: list[dict[str, Any]] = []
    for source in hits:
        row = dict(source)
        candidates: list[tuple[int, Mapping[str, Any]]] = []
        for feature in cds.get(str(row["contig"]), []):
            overlap = min(int(row["end"]), int(feature["end"])) - max(
                int(row["start"]), int(feature["start"])
            ) + 1
            if overlap > 0:
                candidates.append((overlap, feature))
        if candidates:
            _, best = max(
                candidates,
                key=lambda item: (
                    item[0], -int(item[1]["start"]), str(item[1]["locus_tag"])
                ),
            )
            row["locus_tag"] = best.get("locus_tag", "")
            row["prokka_gene"] = best.get("gene", "")
            row["prokka_product"] = best.get("product", "")
        result.append(row)
    return result

# --- original module: input.py ---
"""Content-based sequence detection, sample grouping, and input safety checks."""


import gzip
import io
import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator, Literal, Sequence, TextIO



SUPPORTED_SUFFIXES = (
    ".fa", ".fna", ".fasta", ".fas", ".fq", ".fastq",
    ".fa.gz", ".fna.gz", ".fasta.gz", ".fas.gz", ".fq.gz", ".fastq.gz",
)
_SAFE_SAMPLE = re.compile(r"[^A-Za-z0-9._-]+")
_MATE_PATTERN = re.compile(
    r"^(?P<sample>.*?)(?:(?:[._-]R?)(?P<separated>[12])|R(?P<compact>[12]))"
    r"(?:[._-]?001)?$",
    re.IGNORECASE,
)
InputType = Literal["reads", "genome"]
AnalysisMode = Literal["reads", "genome", "assemble"]


@dataclass(frozen=True)
class InputSet:
    """Validated sequence inputs."""

    files: tuple[Path, ...]
    kind: str
    paired: bool
    compressed: tuple[bool, ...]
    sample_id: str
    input_type: InputType
    analysis_mode: AnalysisMode


def is_gzip(path: Path) -> bool:
    """Detect gzip by magic bytes rather than filename."""
    with path.open("rb") as handle:
        return handle.read(2) == b"\x1f\x8b"


def open_sequence_text(path: Path) -> TextIO:
    """Open plain or gzip-compressed sequence text as UTF-8."""
    raw = path.open("rb")
    try:
        if raw.read(2) == b"\x1f\x8b":
            raw.seek(0)
            binary = gzip.GzipFile(fileobj=raw)
            return io.TextIOWrapper(binary, encoding="utf-8", newline=None)
        raw.seek(0)
        return io.TextIOWrapper(raw, encoding="utf-8", newline=None)
    except Exception:
        raw.close()
        raise


def _nonblank(lines: Iterator[str]) -> Iterator[str]:
    for line in lines:
        value = line.rstrip("\r\n")
        if value.strip():
            yield value


def _validate_fasta(first: str, lines: Iterator[str], path: Path) -> None:
    records = 0
    has_sequence = False
    for line in (item for item in (first, *()) if item):
        if not line.startswith(">") or not line[1:].strip():
            raise InputValidationError(f"Invalid FASTA header in {path}")
        records += 1
    for line in lines:
        value = line.rstrip("\r\n")
        if not value.strip():
            continue
        if value.startswith(">"):
            if not has_sequence:
                raise InputValidationError(f"FASTA record has no sequence in {path}")
            if not value[1:].strip():
                raise InputValidationError(f"Invalid FASTA header in {path}")
            records += 1
            has_sequence = False
        else:
            if value.startswith("@") or re.search(r"\s", value):
                raise InputValidationError(f"Invalid or mixed FASTA content in {path}")
            has_sequence = True
    if records == 0 or not has_sequence:
        raise InputValidationError(f"FASTA contains no sequence records: {path}")


def _validate_fastq(first: str, lines: Iterator[str], path: Path) -> None:
    if not first.startswith("@") or not first[1:].strip():
        raise InputValidationError(f"Invalid FASTQ header in {path}")
    pending: list[str] = [first]
    record_count = 0
    for line in lines:
        pending.append(line.rstrip("\r\n"))
        if len(pending) == 4:
            header, sequence, plus, quality = pending
            if not header.startswith("@") or not header[1:].strip():
                raise InputValidationError(f"Invalid FASTQ header in {path}")
            if not sequence or re.search(r"\s", sequence):
                raise InputValidationError(f"Invalid FASTQ sequence in {path}")
            if not plus.startswith("+"):
                raise InputValidationError(f"Invalid FASTQ separator in {path}")
            if len(sequence) != len(quality):
                raise InputValidationError(f"FASTQ sequence/quality length mismatch in {path}")
            record_count += 1
            pending = []
    if pending:
        raise InputValidationError(f"Incomplete FASTQ record in {path}")
    if record_count == 0:
        raise InputValidationError(f"FASTQ contains no records: {path}")


def detect_sequence_format(path: Path) -> str:
    """Return ``fasta`` or ``fastq`` after validating file content."""
    path = Path(path)
    if not path.exists():
        raise InputValidationError(f"Input file does not exist: {path}")
    if not path.is_file():
        raise InputValidationError(f"Input path is not a file: {path}")
    if not os.access(path, os.R_OK):
        raise InputValidationError(f"Input file is not readable: {path}")
    try:
        with open_sequence_text(path) as handle:
            iterator = iter(handle)
            first = next(_nonblank(iterator), None)
            if first is None:
                raise InputValidationError(f"Input file is empty: {path}")
            if first.startswith(">"):
                _validate_fasta(first, iterator, path)
                return "fasta"
            if first.startswith("@"):
                _validate_fastq(first, iterator, path)
                return "fastq"
    except (gzip.BadGzipFile, UnicodeError, OSError) as exc:
        raise InputValidationError(f"Cannot read sequence content from {path}: {exc}") from exc
    raise InputValidationError(f"Input is neither valid FASTA nor FASTQ: {path}")


def sanitize_sample_id(value: str) -> str:
    """Return a filesystem-safe, stable sample identifier."""
    cleaned = _SAFE_SAMPLE.sub("_", value.strip()).strip("._-")
    cleaned = re.sub(r"_+", "_", cleaned)
    if not cleaned:
        cleaned = "sample"
    return cleaned[:100]


def _derived_sample(files: Sequence[Path]) -> str:
    names = []
    for path in files:
        name = path.name
        if name.lower().endswith(".gz"):
            name = name[:-3]
        name = re.sub(r"\.(?:fa|fna|fasta|fas|fq|fastq)$", "", name, flags=re.I)
        name = re.sub(r"([._-])R?[12]$", "", name, flags=re.I)
        names.append(name)
    if len(names) == 2:
        first = _mate_key(files[0])
        second = _mate_key(files[1])
        if first is not None and second is not None and first[0].casefold() == second[0].casefold():
            return sanitize_sample_id(first[0] or "sample")
        common = os.path.commonprefix(names).rstrip("._-")
        return sanitize_sample_id(common or names[0])
    return sanitize_sample_id(names[0])


def _sequence_stem(path: Path) -> str:
    name = path.name
    if name.lower().endswith(".gz"):
        name = name[:-3]
    return re.sub(r"\.(?:fa|fna|fasta|fas|fq|fastq)$", "", name, flags=re.I)


def _mate_key(path: Path) -> tuple[str, int] | None:
    match = _MATE_PATTERN.fullmatch(_sequence_stem(path))
    if match is None:
        return None
    mate = match.group("separated") or match.group("compact")
    sample = match.group("sample").rstrip("._-")
    return sample, int(mate)


def _validate_pair(files: Sequence[Path]) -> None:
    if len(files) != 2:
        return
    first = _mate_key(files[0])
    second = _mate_key(files[1])
    if first is None or second is None:
        raise InputValidationError(
            "Two FASTQ files require recognizable R1/R2 (or _1/_2) mate names; "
            "use separate runs for unrelated single-end samples."
        )
    if (
        first[0].casefold() != second[0].casefold()
        or first[1] != 1
        or second[1] != 2
    ):
        raise InputValidationError(
            "FASTQ pair must be an ordered R1/R2 pair with the same sample stem."
        )


def _resolve_contract(
    sequence_kind: str, input_type: str, analysis_mode: str
) -> tuple[InputType, AnalysisMode]:
    if input_type not in {"auto", "reads", "genome"}:
        raise InputValidationError("input_type must be one of: auto, reads, genome.")
    if analysis_mode not in {"auto", "reads", "genome", "assemble"}:
        raise InputValidationError(
            "analysis_mode must be one of: auto, reads, genome, assemble."
        )
    detected_type: InputType = "reads" if sequence_kind == "fastq" else "genome"
    resolved_type: InputType = (
        detected_type if input_type == "auto" else input_type  # type: ignore[assignment]
    )
    if resolved_type != detected_type:
        raise InputValidationError(
            f"Explicit input_type '{resolved_type}' does not match detected "
            f"{sequence_kind.upper()} content ({detected_type})."
        )
    if analysis_mode == "auto":
        resolved_mode: AnalysisMode = (
            "assemble" if resolved_type == "reads" else "genome"
        )
    else:
        resolved_mode = analysis_mode  # type: ignore[assignment]
    allowed_modes = {"reads", "assemble"} if resolved_type == "reads" else {"genome"}
    if resolved_mode not in allowed_modes:
        raise InputValidationError(
            f"input_type '{resolved_type}' does not support analysis_mode "
            f"'{resolved_mode}'."
        )
    return resolved_type, resolved_mode


def validate_inputs(
    files: Sequence[Path],
    output: Path,
    sample_id: str | None = None,
    *,
    input_type: str = "auto",
    analysis_mode: str = "auto",
) -> InputSet:
    """Validate count, identity, content type, and output safety."""
    if not files:
        raise InputValidationError("Provide one FASTA/FASTQ file or a paired FASTQ pair.")
    if len(files) > 2:
        raise InputValidationError("At most two input files are accepted.")
    resolved = tuple(Path(item).expanduser().resolve() for item in files)
    if len(set(resolved)) != len(resolved):
        raise InputValidationError("Duplicate input files are not allowed.")
    kinds = tuple(detect_sequence_format(path) for path in resolved)
    if len(set(kinds)) != 1:
        raise InputValidationError("Mixed FASTA and FASTQ input is not allowed.")
    if kinds[0] == "fasta" and len(resolved) != 1:
        raise InputValidationError("FASTA mode accepts exactly one assembled metagenome.")
    if kinds[0] == "fastq":
        _validate_pair(resolved)
    resolved_type, resolved_mode = _resolve_contract(
        kinds[0], input_type, analysis_mode
    )
    output_resolved = Path(output).expanduser().resolve()
    if output_resolved.exists() and not output_resolved.is_dir():
        raise InputValidationError(f"Output path is an existing file: {output_resolved}")
    for path in resolved:
        if output_resolved == path or output_resolved in path.parents:
            raise InputValidationError(
                f"Output directory would contain or overwrite an input file: {output_resolved}"
            )
    return InputSet(
        files=resolved,
        kind=kinds[0],
        paired=kinds[0] == "fastq" and len(resolved) == 2,
        compressed=tuple(is_gzip(path) for path in resolved),
        sample_id=sanitize_sample_id(sample_id) if sample_id else _derived_sample(resolved),
        input_type=resolved_type,
        analysis_mode=resolved_mode,
    )


def discover_samples(
    files: Sequence[Path],
    output: Path,
    *,
    input_directory: Path | None = None,
    sample_id: str | None = None,
    input_type: str = "auto",
    analysis_mode: str = "auto",
) -> list[InputSet]:
    """Discover independent FASTA samples and strict FASTQ singletons/pairs."""
    if files and input_directory is not None:
        raise InputValidationError("Use either input files or input_directory, not both.")
    candidates = [Path(item) for item in files]
    if input_directory is not None:
        directory = Path(input_directory).expanduser().resolve()
        if not directory.is_dir():
            raise InputValidationError(f"Input directory does not exist: {directory}")
        output_resolved = Path(output).expanduser().resolve()
        if directory == output_resolved or directory in output_resolved.parents:
            raise InputValidationError(
                "Output directory must not be inside the input directory."
            )
        candidates = sorted(
            (
                item
                for item in directory.iterdir()
                if item.is_file()
                and any(item.name.lower().endswith(suffix) for suffix in SUPPORTED_SUFFIXES)
            ),
            key=lambda item: item.name.casefold(),
        )
    if not candidates:
        raise InputValidationError("No supported FASTA/FASTQ input files were found.")
    resolved = [item.expanduser().resolve() for item in candidates]
    if len(set(resolved)) != len(resolved):
        raise InputValidationError("Duplicate input files are not allowed.")
    detected = {path: detect_sequence_format(path) for path in resolved}
    groups: list[list[Path]] = []
    groups.extend([[path] for path in resolved if detected[path] == "fasta"])
    paired: dict[str, dict[int, Path]] = {}
    for path in (item for item in resolved if detected[item] == "fastq"):
        key = _mate_key(path)
        if key is None:
            groups.append([path])
            continue
        stem, mate = key
        normalized = stem.casefold()
        slots = paired.setdefault(normalized, {})
        if mate in slots:
            raise InputValidationError(
                f"Duplicate R{mate} FASTQ files for sample stem '{stem or 'sample'}'."
            )
        slots[mate] = path
    for stem, slots in sorted(paired.items()):
        if set(slots) == {1}:
            groups.append([slots[1]])
            continue
        if set(slots) != {1, 2}:
            raise InputValidationError(
                f"FASTQ sample stem '{stem or 'sample'}' has R2 without R1."
            )
        groups.append([slots[1], slots[2]])
    groups.sort(key=lambda group: tuple(path.name.casefold() for path in group))
    if sample_id is not None and len(groups) != 1:
        raise InputValidationError(
            "--sample-id can only be used when exactly one sample is discovered."
        )
    samples = [
        validate_inputs(
            group,
            output,
            sample_id=sample_id,
            input_type=input_type,
            analysis_mode=analysis_mode,
        )
        for group in groups
    ]
    identifiers = [item.sample_id.casefold() for item in samples]
    if len(set(identifiers)) != len(identifiers):
        raise InputValidationError(
            "Discovered sample IDs are not unique; rename inputs or run samples "
            "separately with explicit --sample-id values."
        )
    return samples

# --- original module: metadata.py ---
"""Strict, configurable MEGARes metadata loading."""


import csv
import re
from pathlib import Path
from typing import Any, Mapping



FIELD_ALIASES: dict[str, tuple[str, ...]] = {
    "accession": (
        "accession", "accession_number", "sequence_accession", "megares_accession",
        "header", "id",
    ),
    "gene": ("gene", "gene_name", "resistance_gene", "name"),
    "product": ("product", "description", "annotation"),
    "compound_type": ("compound_type", "type", "drug_type", "compound"),
    "class": ("class", "drug_class", "antimicrobial_class"),
    "mechanism": ("mechanism", "resistance_mechanism"),
    "group": ("group", "gene_group", "resistance_group"),
    "resistance": ("resistance", "phenotype", "drug", "antibiotic"),
    "requires_snp_confirmation": (
        "requires_snp_confirmation", "snp_confirmation_required", "requires_snp",
    ),
}
OUTPUT_FIELDS = tuple(FIELD_ALIASES)


def normalize_header(value: str) -> str:
    """Normalize only header punctuation/case, not semantic content."""
    return re.sub(r"[^a-z0-9]+", "_", value.strip().lower()).strip("_")


def normalize_accession(value: str) -> str:
    """Normalize an accession for exact metadata joins."""
    cleaned = value.strip().lstrip(">").split()[0] if value.strip() else ""
    if "|" in cleaned:
        tokens = [token for token in cleaned.split("|") if token]
        if len(tokens) >= 2 and tokens[0].lower() in {"gb", "emb", "dbj", "ref"}:
            cleaned = tokens[1]
    cleaned = re.sub(r"\.\d+$", "", cleaned)
    return cleaned.upper()


def _dialect(path: Path, sample: str) -> csv.Dialect:
    if path.suffix.lower() == ".csv":
        return csv.excel
    if path.suffix.lower() in {".tsv", ".tab"}:
        return csv.excel_tab
    try:
        return csv.Sniffer().sniff(sample, delimiters="\t,")
    except csv.Error:
        return csv.excel_tab


def _resolve_fields(
    headers: list[str], configured: Mapping[str, Any] | None
) -> dict[str, str | None]:
    normalized = {normalize_header(header): header for header in headers}
    mapping: dict[str, str | None] = {}
    configured = configured or {}
    for logical, aliases in FIELD_ALIASES.items():
        requested = configured.get(logical)
        if requested:
            key = normalize_header(str(requested))
            if key not in normalized:
                raise ParseError(
                    f"Configured MEGARes metadata field '{requested}' for '{logical}' "
                    "does not exist."
                )
            mapping[logical] = normalized[key]
            continue
        candidates = [normalized[alias] for alias in aliases if alias in normalized]
        if len(candidates) > 1:
            raise ParseError(
                f"Ambiguous MEGARes metadata fields for '{logical}': {candidates}. "
                "Set metadata_fields explicitly."
            )
        mapping[logical] = candidates[0] if candidates else None
    if mapping["accession"] is None:
        raise ParseError(
            "MEGARes metadata is missing an accession join field. "
            "Configure metadata_fields.accession."
        )
    return mapping


def load_metadata(
    path: Path, configured_fields: Mapping[str, Any] | None = None
) -> dict[str, dict[str, str]]:
    """Load MEGARes TSV/CSV keyed by normalized accession."""
    try:
        text = path.read_text(encoding="utf-8-sig")
    except OSError as exc:
        raise ParseError(f"Cannot read MEGARes metadata: {path}") from exc
    if not text.strip():
        raise ParseError(f"MEGARes metadata is empty: {path}")
    dialect = _dialect(path, text[:4096])
    reader = csv.DictReader(text.splitlines(), dialect=dialect)
    if not reader.fieldnames:
        raise ParseError(f"MEGARes metadata has no header: {path}")
    fields = _resolve_fields([name.strip() for name in reader.fieldnames], configured_fields)
    result: dict[str, dict[str, str]] = {}
    for line_number, row in enumerate(reader, start=2):
        raw_accession = str(row.get(fields["accession"] or "", "") or "")
        accession = normalize_accession(raw_accession)
        if not accession:
            raise ParseError(f"MEGARes metadata row {line_number} has an empty accession.")
        if accession in result:
            raise ParseError(f"Duplicate normalized MEGARes accession: {accession}")
        result[accession] = {
            logical: str(row.get(source, "") or "").strip() if source else ""
            for logical, source in fields.items()
        }
        result[accession]["accession"] = raw_accession.strip()
    return result


def truthy(value: str) -> bool:
    """Interpret explicit metadata boolean values."""
    return value.strip().lower() in {"1", "true", "yes", "y", "required"}

# --- original module: runner_bridge.py ---
"""Small helpers for Agent runtime YAML inputs."""


from pathlib import Path
from typing import Any

import yaml



def read_runtime(path: Path, mode: str = "auto") -> tuple[list[Path], Path, str | None]:
    """Translate an Agent runtime YAML into explicit CLI-equivalent values."""
    with path.open("r", encoding="utf-8") as handle:
        data: Any = yaml.safe_load(handle) or {}
    if not isinstance(data, dict):
        raise ConfigurationError("Runner runtime YAML must be a mapping.")
    base = path.resolve().parent
    inputs = data.get("inputs", {})
    outputs = data.get("outputs", {})
    if not isinstance(inputs, dict) or not isinstance(outputs, dict):
        raise ConfigurationError("Runner inputs and outputs must be mappings.")
    if mode == "fasta":
        raw_files = [inputs.get("assembly")]
    elif mode == "fastq":
        raw_files = [inputs.get("read1"), inputs.get("read2")]
    else:
        raw = inputs.get("sequences")
        raw_files = raw if isinstance(raw, list) else [raw]
    files = [
        (base / str(item)).resolve() if not Path(str(item)).is_absolute() else Path(str(item)).resolve()
        for item in raw_files
        if item
    ]
    raw_output = outputs.get("directory") or data.get("output")
    if not raw_output:
        raise ConfigurationError("Runner runtime YAML is missing outputs.directory.")
    output = Path(str(raw_output))
    if not output.is_absolute():
        output = base / output
    return files, output.resolve(), data.get("sample_id")

# --- original module: abricate.py ---
"""ABRicate command construction and name-based result parsing."""


import csv
from pathlib import Path
from typing import Any, Iterable, Mapping



ARG_FIELDS = [
    "sample_id", "contig", "start", "end", "strand", "gene", "accession",
    "product", "compound_type", "class", "mechanism", "group", "resistance",
    "pct_identity", "pct_coverage", "coverage", "gaps", "supporting_reads", "depth",
    "database_name",
    "database_version", "locus_tag", "prokka_gene", "prokka_product",
    "requires_snp_confirmation", "snp_status", "final_call",
]


def abricate_command(
    assembly: Path, config: PipelineConfig
) -> list[str]:
    """Build the configured custom-MEGARes ABRicate command."""
    tool = config.value("tools", "abricate")
    datadir = config.database_path("abricate_datadir")
    return [
        str(tool["executable"]),
        *[str(item) for item in tool.get("prefix_options", [])],
        "--datadir", str(datadir),
        "--db", str(tool["database_name"]),
        "--minid", str(tool["min_identity"]),
        "--mincov", str(tool["min_coverage"]),
        "--threads", str(config.threads),
        str(assembly),
    ]


def run_abricate(
    assembly: Path, raw_path: Path, config: PipelineConfig, runner: CommandRunner
) -> Path:
    """Stream ABRicate stdout directly to its raw TSV."""
    runner.run(
        abricate_command(assembly, config),
        tool="ABRicate",
        log_path=raw_path.parent.parent / "logs" / "abricate.log",
        stdout_path=raw_path,
    )
    return raw_path


def _canon(value: str) -> str:
    return value.lstrip("#").strip().upper().replace(" ", "_")


def _get(row: Mapping[str, str], *names: str) -> str:
    for name in names:
        value = row.get(_canon(name), "")
        if value not in ("", "."):
            return value.strip()
    return ""


def _integer(value: str, field: str, line_number: int) -> int:
    try:
        return int(float(value))
    except ValueError as exc:
        raise ParseError(f"ABRicate line {line_number} has invalid {field}: {value}") from exc


def parse_abricate(path: Path) -> list[dict[str, Any]]:
    """Parse ABRicate using header names and preserve empty-hit success."""
    try:
        with path.open("r", encoding="utf-8-sig", newline="") as handle:
            lines = [line for line in handle if line.strip()]
    except OSError as exc:
        raise ParseError(f"Cannot read ABRicate output: {path}") from exc
    if not lines:
        raise ParseError(f"ABRicate output is empty and has no header: {path}")
    reader = csv.DictReader(lines, delimiter="\t")
    if not reader.fieldnames:
        raise ParseError(f"ABRicate output has no header: {path}")
    reader.fieldnames = [_canon(name) for name in reader.fieldnames]
    required = {"SEQUENCE", "START", "END", "GENE"}
    if not required.issubset(set(reader.fieldnames)):
        missing = sorted(required - set(reader.fieldnames))
        raise ParseError(f"ABRicate output is missing required columns: {missing}")
    rows: list[dict[str, Any]] = []
    for line_number, raw in enumerate(reader, start=2):
        row = {_canon(key): str(value or "") for key, value in raw.items()}
        start = _integer(_get(row, "START"), "START", line_number)
        end = _integer(_get(row, "END"), "END", line_number)
        strand = _get(row, "STRAND") or ("-" if start > end else "+")
        rows.append(
            {
                "contig": _get(row, "SEQUENCE"),
                "start": min(start, end),
                "end": max(start, end),
                "strand": strand,
                "gene": _get(row, "GENE"),
                "accession": _get(row, "ACCESSION"),
                "product": _get(row, "PRODUCT"),
                "resistance": _get(row, "RESISTANCE"),
                "pct_identity": _get(row, "%IDENTITY", "IDENTITY"),
                "pct_coverage": _get(row, "%COVERAGE"),
                "coverage": _get(row, "COVERAGE"),
                "gaps": _get(row, "GAPS"),
            }
        )
    return rows


def enrich_hits(
    hits: Iterable[Mapping[str, Any]],
    metadata: Mapping[str, Mapping[str, str]],
    sample_id: str,
    database_name: str,
    database_version: str,
    warnings: list[str],
) -> list[dict[str, Any]]:
    """Join hierarchy and conservative SNP-call semantics onto hits."""
    enriched: list[dict[str, Any]] = []
    for hit in hits:
        raw_accession = str(hit.get("accession", ""))
        accession = normalize_accession(raw_accession)
        meta = metadata.get(accession)
        if meta is None:
            warnings.append(
                f"ABRicate hit accession '{raw_accession or '(empty)'}' "
                "did not match MEGARes metadata."
            )
            meta = {}
        requires_snp = truthy(str(meta.get("requires_snp_confirmation", "")))
        row = {field: "" for field in ARG_FIELDS}
        row.update(hit)
        row.update(
            {
                "sample_id": sample_id,
                "accession": raw_accession if raw_accession != "." else "",
                "compound_type": meta.get("compound_type", ""),
                "class": meta.get("class", ""),
                "mechanism": meta.get("mechanism", ""),
                "group": meta.get("group", ""),
                "resistance": hit.get("resistance") or meta.get("resistance", ""),
                "product": hit.get("product") or meta.get("product", ""),
                "database_name": database_name,
                "database_version": database_version,
                "requires_snp_confirmation": str(requires_snp).lower(),
                "snp_status": "not_evaluated",
                "final_call": "candidate_hit" if requires_snp else "sequence_homology_hit",
            }
        )
        enriched.append(row)
    return sorted(
        enriched,
        key=lambda row: (
            str(row["contig"]), str(row["start"]).zfill(20),
            str(row["end"]).zfill(20), str(row["gene"])
        ),
    )

# --- original module: assembly.py ---
"""Trimmomatic and metagenome assembly orchestration."""


import shutil
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping, Sequence



@dataclass(frozen=True)
class AssemblyResult:
    """Assembly path and preprocessing provenance."""

    path: Path
    source: str
    trimmed_reads: tuple[Path, ...]
    unpaired_reads: tuple[Path, ...]



@dataclass(frozen=True)
class ReadPreparation:
    """Trimmed reads and discarded mate outputs."""

    trimmed_reads: tuple[Path, ...]
    unpaired_reads: tuple[Path, ...]

def trimmomatic_command(
    reads: Sequence[Path], output_dir: Path, config: PipelineConfig
) -> tuple[list[str], tuple[Path, ...], tuple[Path, ...]]:
    """Build single- or paired-end Trimmomatic arguments."""
    tool = config.value("tools", "trimmomatic")
    executable = str(tool["executable"])
    options = [str(item) for item in tool.get("options", [])]
    if len(reads) == 1:
        trimmed = output_dir / "trimmed.fastq.gz"
        command = [
            executable, *[str(item) for item in tool.get("prefix_options", [])],
            "SE", "-threads", str(config.threads), str(reads[0]), str(trimmed), *options,
        ]
        return command, (trimmed,), ()
    if len(reads) == 2:
        paired1 = output_dir / "trimmed_R1.fastq.gz"
        unpaired1 = output_dir / "unpaired_R1.fastq.gz"
        paired2 = output_dir / "trimmed_R2.fastq.gz"
        unpaired2 = output_dir / "unpaired_R2.fastq.gz"
        command = [
            executable, *[str(item) for item in tool.get("prefix_options", [])],
            "PE", "-threads", str(config.threads), str(reads[0]), str(reads[1]),
            str(paired1), str(unpaired1), str(paired2), str(unpaired2), *options,
        ]
        return command, (paired1, paired2), (unpaired1, unpaired2)
    raise ValueError("Trimmomatic requires one read or an explicit R1/R2 pair.")



def prepare_reads(
    inputs: InputSet,
    work_dir: Path,
    config: PipelineConfig,
    runner: CommandRunner,
) -> ReadPreparation:
    """Quality-trim FASTQ reads without assembling them."""
    if inputs.kind != "fastq":
        raise ValueError("Direct reads analysis requires FASTQ input.")
    trim_dir = work_dir / "trimmed"
    trim_dir.mkdir(parents=True, exist_ok=True)
    command, trimmed, unpaired = trimmomatic_command(inputs.files, trim_dir, config)
    runner.run(
        command,
        tool="Trimmomatic",
        log_path=work_dir.parent / "logs" / "trimmomatic.log",
    )
    if not runner.dry_run:
        for path in trimmed:
            if not path.is_file() or path.stat().st_size == 0:
                raise ExternalToolError(
                    f"Trimmomatic completed without a non-empty output: {path}"
                )
    return ReadPreparation(tuple(trimmed), tuple(unpaired))

def assembler_command(
    trimmed: Sequence[Path],
    unpaired: Sequence[Path],
    output_dir: Path,
    config: PipelineConfig,
) -> list[str]:
    """Build a metaSPAdes command without isolate-mode assumptions."""
    tool = config.value("tools", "assembler")
    options = [str(item) for item in tool.get("options", [])]
    if any(item.lstrip("-").lower() == "isolate" for item in options):
        raise ValueError("Assembler options must not enable isolate mode.")
    command = [
        str(tool["executable"]), *[str(item) for item in tool.get("prefix_options", [])],
        *options, "-t", str(config.threads),
    ]
    memory = tool.get("memory_gb")
    if memory not in (None, ""):
        command.extend(["-m", str(memory)])
    command.extend(["-o", str(output_dir)])
    if len(trimmed) == 2:
        command.extend(["-1", str(trimmed[0]), "-2", str(trimmed[1])])
        if tool.get("include_unpaired", False):
            for index, path in enumerate(unpaired, start=1):
                command.extend([f"--s{index}", str(path)])
    else:
        command.extend(["-s", str(trimmed[0])])
    return command


def _copy_plain_fasta(source: Path, target: Path) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", newline="\n", delete=False, dir=target.parent
    ) as temporary:
        temporary_path = Path(temporary.name)
        with open_sequence_text(source) as handle:
            shutil.copyfileobj(handle, temporary)
    temporary_path.replace(target)


def prepare_assembly(
    inputs: InputSet,
    work_dir: Path,
    config: PipelineConfig,
    runner: CommandRunner,
) -> AssemblyResult:
    """Use supplied contigs or build a metagenome assembly from reads."""
    assembly_dir = work_dir / "assembly"
    assembly_dir.mkdir(parents=True, exist_ok=True)
    if inputs.kind == "fasta":
        assembly = assembly_dir / "assembly.fasta"
        _copy_plain_fasta(inputs.files[0], assembly)
        return AssemblyResult(assembly, "supplied", (), ())
    trim_dir = work_dir / "trimmed"
    trim_dir.mkdir(parents=True, exist_ok=True)
    trim_command, trimmed, unpaired = trimmomatic_command(inputs.files, trim_dir, config)
    runner.run(
        trim_command, tool="Trimmomatic", log_path=work_dir.parent / "logs" / "trimmomatic.log"
    )
    spades_dir = assembly_dir / "metaspades"
    command = assembler_command(trimmed, unpaired, spades_dir, config)
    runner.run(
        command, tool="metaSPAdes", log_path=work_dir.parent / "logs" / "metaspades.log"
    )
    assembly = spades_dir / "contigs.fasta"
    if not runner.dry_run and (not assembly.is_file() or assembly.stat().st_size == 0):
        raise ExternalToolError(
            f"metaSPAdes completed without a non-empty contigs.fasta: {assembly}"
        )
    return AssemblyResult(assembly, "metaspades", tuple(trimmed), tuple(unpaired))

# --- original module: database.py ---
"""Read-only MEGARes custom ABRicate database preflight."""


import os
from pathlib import Path
from typing import Any



def validate_database(config: PipelineConfig) -> dict[str, Any]:
    """Validate database directory, sequences, BLAST indexes, and metadata."""
    datadir = config.database_path("abricate_datadir")
    metadata = config.database_path("metadata")
    database_name = str(config.value("tools", "abricate", "database_name"))
    database_dir = datadir / database_name
    sequences = database_dir / "sequences"
    for path, label, directory in (
        (datadir, "ABRicate datadir", True),
        (database_dir, f"ABRicate database '{database_name}'", True),
        (sequences, "ABRicate sequences", False),
        (metadata, "MEGARes metadata", False),
    ):
        valid = path.is_dir() if directory else path.is_file()
        if not valid:
            raise DatabaseConfigurationError(f"{label} does not exist: {path}")
        if not directory and (path.stat().st_size == 0 or not os.access(path, os.R_OK)):
            raise DatabaseConfigurationError(f"{label} is empty or unreadable: {path}")
    indexes = sorted(
        item.name
        for item in database_dir.iterdir()
        if item.is_file() and item.suffix.lower() in {".nhr", ".nin", ".nsq", ".ndb", ".not", ".ntf", ".nto"}
    )
    if not indexes:
        raise DatabaseConfigurationError(
            f"BLAST nucleotide database indexes are missing in: {database_dir}"
        )
    return {
        "name": database_name,
        "directory": str(database_dir),
        "sequences": sequences.name,
        "blast_indexes": indexes,
    }

# --- original module: prokka.py ---
"""Metagenome-aware Prokka orchestration."""


import shutil
from dataclasses import dataclass
from pathlib import Path



@dataclass(frozen=True)
class ProkkaResult:
    """Required Prokka outputs."""

    faa: Path
    ffn: Path
    gff: Path
    tsv: Path
    txt: Path


def prokka_command(
    assembly: Path, output_dir: Path, prefix: str, config: PipelineConfig
) -> list[str]:
    """Build a configured Prokka command and enforce metagenome mode."""
    tool = config.value("tools", "prokka")
    options = [str(item) for item in tool.get("options", [])]
    if "--metagenome" not in options:
        raise ValueError("Prokka options must include --metagenome.")
    return [
        str(tool["executable"]), *[str(item) for item in tool.get("prefix_options", [])],
        *options, "--cpus", str(config.threads), "--outdir", str(output_dir),
        "--prefix", prefix, str(assembly),
    ]


def run_prokka(
    assembly: Path,
    work_dir: Path,
    raw_dir: Path,
    sample_id: str,
    config: PipelineConfig,
    runner: CommandRunner,
) -> ProkkaResult:
    """Run Prokka, validate outputs, and retain them under raw/prokka."""
    output_dir = work_dir / "prokka"
    runner.run(
        prokka_command(assembly, output_dir, sample_id, config),
        tool="Prokka",
        log_path=work_dir.parent / "logs" / "prokka.log",
    )
    result = ProkkaResult(
        faa=output_dir / f"{sample_id}.faa",
        ffn=output_dir / f"{sample_id}.ffn",
        gff=output_dir / f"{sample_id}.gff",
        tsv=output_dir / f"{sample_id}.tsv",
        txt=output_dir / f"{sample_id}.txt",
    )
    if not runner.dry_run:
        for path in result.__dict__.values():
            if not path.is_file() or path.stat().st_size == 0:
                raise ExternalToolError(f"Prokka required output is missing or empty: {path}")
        retained = raw_dir / "prokka"
        retained.mkdir(parents=True, exist_ok=True)
        for path in result.__dict__.values():
            shutil.copy2(path, retained / path.name)
    return result

# --- original module: qc.py ---
"""Assembly and gene-prediction quality metrics."""


from pathlib import Path
from typing import Iterator, Sequence



def iter_fasta(path: Path) -> Iterator[tuple[str, str]]:
    """Yield validated FASTA identifiers and sequences."""
    identifier: str | None = None
    pieces: list[str] = []
    with open_sequence_text(path) as handle:
        for raw in handle:
            line = raw.strip()
            if not line:
                continue
            if line.startswith(">"):
                if identifier is not None:
                    yield identifier, "".join(pieces)
                identifier = line[1:].split()[0]
                pieces = []
            elif identifier is None:
                raise InputValidationError(f"Sequence before FASTA header in {path}")
            else:
                pieces.append(line)
    if identifier is not None:
        yield identifier, "".join(pieces)



def fastq_qc(paths: Sequence[Path]) -> dict[str, float | int]:
    """Count reads and bases in validated plain or gzip FASTQ files."""
    read_count = 0
    base_count = 0
    for path in paths:
        file_lines = 0
        with open_sequence_text(path) as handle:
            for file_lines, raw in enumerate(handle, start=1):
                if file_lines % 4 == 2:
                    sequence = raw.strip()
                    if not sequence:
                        raise InputValidationError(f"Empty FASTQ sequence in {path}")
                    read_count += 1
                    base_count += len(sequence)
        if file_lines % 4:
            raise InputValidationError(f"Incomplete FASTQ record in {path}")
    return {
        "file_count": len(paths),
        "read_count": read_count,
        "base_count": base_count,
        "mean_read_length": round(base_count / read_count, 3) if read_count else 0.0,
    }

def assembly_qc(path: Path) -> dict[str, float | int]:
    """Calculate deterministic contig count, length, N50, and GC metrics."""
    lengths: list[int] = []
    gc = 0
    total = 0
    for _, sequence in iter_fasta(path):
        length = len(sequence)
        if length:
            lengths.append(length)
            total += length
            gc += sum(1 for base in sequence.upper() if base in {"G", "C"})
    if not lengths:
        raise InputValidationError(f"Assembly contains no non-empty contigs: {path}")
    threshold = total / 2
    cumulative = 0
    n50 = 0
    for length in sorted(lengths, reverse=True):
        cumulative += length
        if cumulative >= threshold:
            n50 = length
            break
    return {
        "contig_count": len(lengths),
        "total_length": total,
        "min_contig_length": min(lengths),
        "max_contig_length": max(lengths),
        "n50": n50,
        "gc_percent": round((gc / total) * 100, 6),
    }


def count_fasta_records(path: Path) -> int:
    """Count non-empty FASTA records."""
    return sum(1 for _ in iter_fasta(path))

# --- original module: read_mapping.py ---
"""Direct short-read mapping against the deployed nucleotide gene database."""


from pathlib import Path
from typing import Any, Sequence



def reference_sequences(config: PipelineConfig) -> Path:
    """Return the FASTA used by the configured custom ABRicate database."""
    datadir = config.database_path("abricate_datadir")
    database_name = str(config.value("tools", "abricate", "database_name"))
    return datadir / database_name / "sequences"


def minimap2_command(
    reads: Sequence[Path], reference: Path, config: PipelineConfig
) -> list[str]:
    """Build a short-read PAF mapping command with explicit argument boundaries."""
    tool = config.value("tools", "reads_mapper")
    return [
        str(tool["executable"]),
        *[str(item) for item in tool.get("prefix_options", [])],
        *[str(item) for item in tool.get("options", [])],
        "-t",
        str(config.threads),
        str(reference),
        *[str(path) for path in reads],
    ]


def run_minimap2(
    reads: Sequence[Path],
    raw_path: Path,
    config: PipelineConfig,
    runner: CommandRunner,
) -> Path:
    """Run minimap2 and stream PAF records to the raw output directory."""
    runner.run(
        minimap2_command(reads, reference_sequences(config), config),
        tool="minimap2",
        log_path=raw_path.parent.parent / "logs" / "minimap2.log",
        stdout_path=raw_path,
    )
    return raw_path


def _integer(value: str, label: str, line_number: int) -> int:
    try:
        return int(value)
    except ValueError as exc:
        raise ParseError(
            f"minimap2 PAF line {line_number} has invalid {label}: {value}"
        ) from exc


def _covered_bases(intervals: list[tuple[int, int]]) -> int:
    if not intervals:
        return 0
    total = 0
    current_start, current_end = sorted(intervals)[0]
    for start, end in sorted(intervals)[1:]:
        if start > current_end:
            total += current_end - current_start
            current_start, current_end = start, end
        else:
            current_end = max(current_end, end)
    return total + current_end - current_start


def _target_fields(target: str) -> dict[str, str]:
    parts = target.split("~~~")
    return {
        "gene": parts[1] if len(parts) > 1 else target,
        "accession": parts[2] if len(parts) > 2 else target,
        "resistance": parts[3] if len(parts) > 3 else "",
    }


def parse_paf(path: Path, config: PipelineConfig) -> list[dict[str, Any]]:
    """Aggregate passing read alignments by reference gene.

    Coordinates and strand are deliberately left empty because those output fields
    describe an assembled contig feature, which direct reads do not provide.
    """
    tool = config.value("tools", "reads_mapper")
    min_identity = float(tool["min_identity"])
    min_coverage = float(tool["min_coverage"])
    min_mapq = int(tool.get("min_mapq", 0))
    min_length = int(tool.get("min_alignment_length", 1))
    min_support = int(tool.get("min_supporting_reads", 1))
    grouped: dict[str, dict[str, Any]] = {}
    try:
        handle = path.open("r", encoding="utf-8-sig")
    except OSError as exc:
        raise ParseError(f"Cannot read minimap2 PAF output: {path}") from exc
    with handle:
        for line_number, raw in enumerate(handle, start=1):
            if not raw.strip():
                continue
            fields = raw.rstrip("\r\n").split("\t")
            if len(fields) < 12:
                raise ParseError(
                    f"minimap2 PAF line {line_number} has fewer than 12 columns."
                )
            target = fields[5]
            target_length = _integer(fields[6], "target length", line_number)
            target_start = _integer(fields[7], "target start", line_number)
            target_end = _integer(fields[8], "target end", line_number)
            matches = _integer(fields[9], "matching bases", line_number)
            block_length = _integer(fields[10], "alignment block length", line_number)
            mapq = _integer(fields[11], "mapping quality", line_number)
            if (
                target_length <= 0
                or block_length <= 0
                or target_start < 0
                or target_end > target_length
                or target_start >= target_end
            ):
                raise ParseError(f"minimap2 PAF line {line_number} has invalid coordinates.")
            identity = 100.0 * matches / block_length
            if identity < min_identity or mapq < min_mapq or block_length < min_length:
                continue
            item = grouped.setdefault(
                target,
                {
                    "target_length": target_length,
                    "intervals": [],
                    "matches": 0,
                    "aligned_bases": 0,
                    "supporting_reads": 0,
                },
            )
            if item["target_length"] != target_length:
                raise ParseError(
                    f"minimap2 PAF target length changed for reference: {target}"
                )
            item["intervals"].append((target_start, target_end))
            item["matches"] += matches
            item["aligned_bases"] += block_length
            item["supporting_reads"] += 1
    rows: list[dict[str, Any]] = []
    for target, item in grouped.items():
        covered = _covered_bases(item["intervals"])
        pct_coverage = 100.0 * covered / item["target_length"]
        if pct_coverage < min_coverage or item["supporting_reads"] < min_support:
            continue
        row: dict[str, Any] = {
            "contig": "",
            "start": "",
            "end": "",
            "strand": "",
            "pct_identity": round(100.0 * item["matches"] / item["aligned_bases"], 3),
            "pct_coverage": round(pct_coverage, 3),
            "coverage": f"{covered}/{item['target_length']}",
            "gaps": "",
            "supporting_reads": item["supporting_reads"],
            "depth": round(item["aligned_bases"] / item["target_length"], 3),
        }
        row.update(_target_fields(target))
        rows.append(row)
    return sorted(rows, key=lambda row: (str(row["gene"]), str(row["accession"])))

# --- original module: doctor.py ---
"""Read-only BacARG deployment diagnostics."""


import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any



def _check(level: str, name: str, message: str) -> dict[str, str]:
    return {"level": level, "name": name, "message": message}


def _executable(executable: str, prefix_options: list[str]) -> tuple[bool, str]:
    located = shutil.which(executable)
    if located is None and Path(executable).is_file():
        located = str(Path(executable).resolve())
    if located is None:
        return False, f"not found: {executable}"
    try:
        completed = subprocess.run(
            [located, *prefix_options, "--version"],
            stdin=subprocess.DEVNULL,
            capture_output=True,
            text=True,
            shell=False,
            timeout=10,
            check=False,
        )
        text = (completed.stdout or completed.stderr).strip().splitlines()
        version_text = text[0][:300] if text else "version output unavailable"
    except (OSError, subprocess.SubprocessError) as exc:
        version_text = f"located; version probe warning: {exc}"
    return True, f"{located} ({version_text})"


def run_doctor(config_path: Path | None = None, output: Path | None = None) -> dict[str, Any]:
    """Run checks without downloading or modifying databases."""
    checks: list[dict[str, str]] = []
    checks.append(
        _check(
            "ok" if sys.version_info >= (3, 9) else "error",
            "python",
            sys.version.split()[0],
        )
    )
    try:
        config = load_config(config_path)
        checks.append(_check("ok", "configuration", str(config.source)))
        for name in ("trimmomatic", "reads_mapper", "assembler", "prokka", "abricate"):
            section = config.value("tools", name)
            ok, message = _executable(
                str(section["executable"]),
                [str(item) for item in section.get("prefix_options", [])],
            )
            checks.append(_check("ok" if ok else "error", f"executable:{name}", message))
        try:
            info = validate_database(config)
            checks.append(_check("ok", "database", str(info["directory"])))
        except Exception as exc:
            checks.append(_check("error", "database", str(exc)))
    except Exception as exc:
        checks.append(_check("error", "configuration", str(exc)))
    target = (output or Path.cwd()).expanduser().resolve()
    try:
        target.mkdir(parents=True, exist_ok=True)
        descriptor, name = tempfile.mkstemp(prefix=".bacarg-doctor-", dir=target)
        os.close(descriptor)
        Path(name).unlink()
        checks.append(_check("ok", "output_write", str(target)))
    except OSError as exc:
        checks.append(_check("error", "output_write", str(exc)))
    errors = sum(item["level"] == "error" for item in checks)
    warnings = sum(item["level"] == "warning" for item in checks)
    return {
        "project": "bacarg",
        "version": __version__,
        "ok": errors == 0,
        "error_count": errors,
        "warning_count": warnings,
        "checks": checks,
    }

# --- original module: pipeline.py ---
"""End-to-end BacARG orchestration."""


import shutil
from pathlib import Path
from typing import Any, Sequence



def _status(
    output: Path,
    *,
    status: str,
    sample_id: str,
    input_type: str,
    analysis_mode: str,
    dry_run: bool,
    warnings: list[str],
    **extra: Any,
) -> None:
    payload: dict[str, Any] = {
        "schema_version": "1.1",
        "status": status,
        "pipeline": "bacarg",
        "pipeline_version": __version__,
        "sample_id": sample_id,
        "input_type": input_type,
        "analysis_mode": analysis_mode,
        "dry_run": dry_run,
        "warnings": warnings,
    }
    payload.update(extra)
    write_json(output / "status.json", payload)


def _database_version(config: PipelineConfig, deployed: dict[str, Any] | None) -> str:
    if deployed:
        for key in ("database_version", "version"):
            if deployed.get(key):
                return str(deployed[key])
    return str(config.value("tools", "abricate", "database_version", required=False) or "")


def run_pipeline(
    inputs: Sequence[Path],
    output: Path,
    *,
    sample_id: str | None = None,
    config_path: Path | None = None,
    dry_run: bool = False,
    threads: int | None = None,
    input_type: str = "auto",
    analysis_mode: str = "auto",
) -> dict[str, Any]:
    """Run BacARG and return the success status payload."""
    output = Path(output).expanduser().resolve()
    validated: InputSet = validate_inputs(
        inputs,
        output,
        sample_id,
        input_type=input_type,
        analysis_mode=analysis_mode,
    )
    output.mkdir(parents=True, exist_ok=True)
    raw_dir = output / "raw"
    logs_dir = output / "logs"
    work_dir = output / "work"
    for directory in (raw_dir, logs_dir, work_dir):
        directory.mkdir(parents=True, exist_ok=True)
    warnings: list[str] = []
    started = utc_now()
    pipeline_log = logs_dir / "pipeline.log"
    pipeline_log.write_text(f"START bacarg {started}\n", encoding="utf-8")
    runner = CommandRunner(dry_run=dry_run)
    _status(
        output,
        status="running",
        sample_id=validated.sample_id,
        input_type=validated.input_type,
        analysis_mode=validated.analysis_mode,
        dry_run=dry_run,
        warnings=warnings,
    )
    try:
        config = load_config(config_path)
        if threads is not None:
            from dataclasses import replace
            config = replace(config, threads=threads)
        deployed_manifest = database_manifest(
            config.database_path("manifest", required=False), warnings
        )
        if config.value("runtime", "strict_manifest", required=False) and deployed_manifest is None:
            raise RuntimeError("A database manifest is required by runtime.strict_manifest.")
        database_info: dict[str, Any] | None = None
        metadata: dict[str, dict[str, str]] = {}
        if not dry_run:
            database_info = validate_database(config)
            metadata = load_metadata(
                config.database_path("metadata"),
                config.value("metadata_fields", required=False),
            )
        database_name = str(config.value("tools", "abricate", "database_name"))
        assembly_source = "not_applicable"
        assembly_metrics: dict[str, Any] = {}
        protein_count: int | None = None
        reads_metrics: dict[str, Any] = {}
        if validated.analysis_mode == "reads":
            prepared = prepare_reads(validated, work_dir, config, runner)
            raw_paf = raw_dir / f"minimap2_{database_name}.paf"
            run_minimap2(prepared.trimmed_reads, raw_paf, config, runner)
            if dry_run:
                rows: list[dict[str, Any]] = []
            else:
                rows = enrich_hits(
                    parse_paf(raw_paf, config),
                    metadata,
                    validated.sample_id,
                    database_name,
                    _database_version(config, deployed_manifest),
                    warnings,
                )
                raw_read_metrics = fastq_qc(validated.files)
                trimmed_read_metrics = fastq_qc(prepared.trimmed_reads)
                raw_count = int(raw_read_metrics["read_count"])
                reads_metrics = {
                    "raw": raw_read_metrics,
                    "trimmed": trimmed_read_metrics,
                    "retained_read_percent": round(
                        100.0 * int(trimmed_read_metrics["read_count"]) / raw_count, 3
                    ) if raw_count else 0.0,
                }
        else:
            assembly = prepare_assembly(validated, work_dir, config, runner)
            assembly_source = assembly.source
            if assembly.path.is_file():
                assembly_metrics = assembly_qc(assembly.path)
            prokka = run_prokka(
                assembly.path, work_dir, raw_dir, validated.sample_id, config, runner
            )
            raw_abricate = raw_dir / f"abricate_{database_name}.tsv"
            run_abricate(assembly.path, raw_abricate, config, runner)
            if dry_run:
                rows = []
            else:
                rows = enrich_hits(
                    parse_abricate(raw_abricate),
                    metadata,
                    validated.sample_id,
                    database_name,
                    _database_version(config, deployed_manifest),
                    warnings,
                )
                rows = add_context(rows, load_cds(prokka.gff))
                protein_count = count_fasta_records(prokka.faa)
        if dry_run:
            warnings.append("Dry-run planned commands; biological outputs were not executed.")
        write_tsv(output / "arg_hits.tsv", rows, ARG_FIELDS)
        write_jsonl(output / "arg_hits.jsonl", rows)
        qc_payload: dict[str, Any] = {
            "schema_version": "1.1",
            "analysis_mode": validated.analysis_mode,
            "input": {
                "type": validated.input_type,
                "paired": validated.paired,
                "file_count": len(validated.files),
                "compressed": list(validated.compressed),
            },
            "assembly": {"source": assembly_source, **assembly_metrics},
            "gene_prediction": {"status": "not_applicable"} if validated.analysis_mode == "reads" else {},
            "reads": reads_metrics,
            "annotation": {"hit_count": len(rows)},
            "warnings": warnings,
        }
        if protein_count is not None:
            qc_payload["gene_prediction"]["protein_count"] = protein_count
        write_json(output / "qc.json", qc_payload)
        finished = utc_now()
        output_files = [
            "arg_hits.tsv", "arg_hits.jsonl", "status.json", "manifest.json", "qc.json"
        ]
        if validated.analysis_mode == "reads":
            tool_names = ("trimmomatic", "reads_mapper")
            mapper = config.value("tools", "reads_mapper")
            scientific_parameters = {
                "min_identity": mapper["min_identity"],
                "min_coverage": mapper["min_coverage"],
                "min_mapq": mapper["min_mapq"],
                "min_alignment_length": mapper["min_alignment_length"],
                "min_supporting_reads": mapper["min_supporting_reads"],
                "trimmomatic_options": config.value("tools", "trimmomatic", "options"),
                "mapper_options": mapper.get("options", []),
            }
        else:
            tool_names = ("trimmomatic", "assembler", "prokka", "abricate")
            scientific_parameters = {
                "min_identity": config.value("tools", "abricate", "min_identity"),
                "min_coverage": config.value("tools", "abricate", "min_coverage"),
                "trimmomatic_options": config.value("tools", "trimmomatic", "options"),
                "assembler_options": config.value("tools", "assembler", "options"),
                "prokka_options": config.value("tools", "prokka", "options"),
            }
        tool_records = {}
        for name in tool_names:
            section = config.value("tools", name)
            detected = "not_probed_dry_run" if dry_run else probe_version(
                section["executable"], section.get("prefix_options", [])
            )
            tool_records[name] = {
                "executable": str(section["executable"]),
                "version": detected,
            }
        manifest_payload = {
            "schema_version": "1.1",
            "pipeline": "bacarg",
            "pipeline_version": __version__,
            "started_at_utc": started,
            "ended_at_utc": finished,
            "sample_id": validated.sample_id,
            "input_type": validated.input_type,
            "analysis_mode": validated.analysis_mode,
            "inputs": input_records(validated.files),
            "assembly_source": assembly_source,
            "threads": config.threads,
            "commands": render_commands(runner.commands),
            "tools": tool_records,
            "database": database_info
            or {"name": database_name, "validation": "skipped_in_dry_run"},
            "database_manifest": deployed_manifest,
            "scientific_parameters": scientific_parameters,
            "runtime": runtime_record(),
            "warnings": warnings,
            "outputs": output_files,
            "dry_run": dry_run,
        }
        write_json(output / "manifest.json", manifest_payload)
        final_status = {
            "schema_version": "1.1",
            "status": "success",
            "pipeline": "bacarg",
            "pipeline_version": __version__,
            "sample_id": validated.sample_id,
            "input_type": validated.input_type,
            "analysis_mode": validated.analysis_mode,
            "hit_count": len(rows),
            "dry_run": dry_run,
            "warnings": warnings,
        }
        write_json(output / "status.json", final_status)
        with pipeline_log.open("a", encoding="utf-8", newline="\n") as handle:
            handle.write(f"END bacarg success {finished}\n")
        keep_work = config.value("runtime", "keep_work", required=False)
        if keep_work is False and not dry_run:
            shutil.rmtree(work_dir)
        return final_status
    except Exception as exc:
        _status(
            output,
            status="failed",
            sample_id=validated.sample_id,
            input_type=validated.input_type,
            analysis_mode=validated.analysis_mode,
            dry_run=dry_run,
            warnings=warnings,
            error_type=type(exc).__name__,
            message=str(exc),
        )
        with pipeline_log.open("a", encoding="utf-8", newline="\n") as handle:
            handle.write(f"END bacarg failed {utc_now()} {type(exc).__name__}: {exc}\n")
        raise

# --- original module: batch.py ---
"""Independent per-sample batch orchestration."""


from pathlib import Path
from typing import Any, Sequence



def run_samples(
    samples: Sequence[InputSet],
    output: Path,
    *,
    config_path: Path | None = None,
    dry_run: bool = False,
    threads: int | None = None,
) -> list[dict[str, Any]]:
    """Run one or more samples without combining their biological inputs."""
    if not samples:
        raise ValueError("At least one validated sample is required.")
    root = Path(output).expanduser().resolve()
    multiple = len(samples) > 1
    if multiple:
        root.mkdir(parents=True, exist_ok=True)
    statuses: list[dict[str, Any]] = []
    for sample in samples:
        target = root / sample.sample_id if multiple else root
        statuses.append(
            run_pipeline(
                sample.files,
                target,
                sample_id=sample.sample_id,
                config_path=config_path,
                dry_run=dry_run,
                threads=threads,
                input_type=sample.input_type,
                analysis_mode=sample.analysis_mode,
            )
        )
    return statuses

# --- original module: cli.py ---
"""Command-line and Agent-specific entry points."""


import argparse
import json
import sys
from pathlib import Path
from typing import Sequence



def _run_arguments(parser: argparse.ArgumentParser) -> None:
    sources = parser.add_mutually_exclusive_group(required=True)
    sources.add_argument("--input", nargs="+", type=Path)
    sources.add_argument("--input-dir", type=Path)
    parser.add_argument("--input-type", choices=("auto", "reads", "genome"), default="auto")
    parser.add_argument(
        "--analysis-mode",
        choices=("auto", "reads", "genome", "assemble"),
        default="auto",
    )
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--sample-id")
    parser.add_argument("--config", type=Path)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--threads", type=int, default=8)


def build_parser() -> argparse.ArgumentParser:
    """Build the general CLI."""
    parser = argparse.ArgumentParser(
        prog="bacarg",
        description="MEGARes 3.0 sequence-homology ARG candidates from metagenomes.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)
    run_parser = subparsers.add_parser("run", help="Run the pipeline.")
    _run_arguments(run_parser)
    doctor_parser = subparsers.add_parser("doctor", help="Check deployment readiness.")
    doctor_parser.add_argument("--config", type=Path)
    doctor_parser.add_argument("--output", type=Path)
    doctor_parser.add_argument("--json", action="store_true", dest="as_json")
    subparsers.add_parser("version", help="Print the project version.")
    return parser


def _execute_run(namespace: argparse.Namespace) -> int:
    try:
        samples = discover_samples(
            namespace.input or [],
            namespace.output,
            input_directory=namespace.input_dir,
            sample_id=namespace.sample_id,
            input_type=namespace.input_type,
            analysis_mode=namespace.analysis_mode,
        )
        run_samples(
            samples,
            namespace.output,
            config_path=namespace.config,
            dry_run=namespace.dry_run,
            threads=namespace.threads,
        )
        return 0
    except Exception as exc:
        print(f"bacarg: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 1


def main(argv: Sequence[str] | None = None) -> int:
    """General CLI entry point."""
    namespace = build_parser().parse_args(argv)
    if namespace.command == "version":
        print(__version__)
        return 0
    if namespace.command == "doctor":
        report = run_doctor(namespace.config, namespace.output)
        if namespace.as_json:
            print(json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True))
        else:
            for item in report["checks"]:
                print(f"[{item['level'].upper()}] {item['name']}: {item['message']}")
            print("READY" if report["ok"] else "NOT READY")
        return 0 if report["ok"] else 1
    return _execute_run(namespace)


def fasta_main(argv: Sequence[str] | None = None) -> int:
    """FASTA-only Agent entry point."""
    parser = argparse.ArgumentParser(prog="bacarg-fasta")
    parser.add_argument("--assembly", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--sample-id")
    parser.add_argument("--config", type=Path)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--threads", type=int, default=8)
    namespace = parser.parse_args(argv)
    namespace.input = [namespace.assembly]
    namespace.input_dir = None
    namespace.input_type = "genome"
    namespace.analysis_mode = "genome"
    return _execute_run(namespace)


def fastq_main(argv: Sequence[str] | None = None) -> int:
    """FASTQ-only Agent entry point with explicit R1/R2 roles."""
    parser = argparse.ArgumentParser(prog="bacarg-fastq")
    parser.add_argument("--read1", required=True, type=Path)
    parser.add_argument("--read2", type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--sample-id")
    parser.add_argument("--config", type=Path)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--analysis-mode", choices=("assemble", "reads"), default="assemble")
    parser.add_argument("--threads", type=int, default=8)
    namespace = parser.parse_args(argv)
    namespace.input = [namespace.read1] + ([namespace.read2] if namespace.read2 else [])
    namespace.input_dir = None
    namespace.input_type = "reads"
    return _execute_run(namespace)


if __name__ == "__main__":
    raise SystemExit(main())
