# Commands required inside the WDL task image (mscan-detection:v1.0).
name: alignment-based-identification

channels:
  - conda-forge
  - bioconda
  - nodefaults

dependencies:
  - bash >=4.4
  - coreutils
  - python >=3.10
  - minimap2 >=2.26
  - sambamba >=1.0
  - samtools >=1.17
