label: bacterial_annotation
genome_path: ""
output_dir: output
params:
  annotator: prokka
  prefix: annotation
  genus: ""
  species: ""
  strain: ""
  cpus: 1
  translation_table: 11
  locus_tag: ""
  compliant: false
  bakta_db_path: ""
  gram: "?"
  meta: false
  complete: false
  keep_contig_headers: false
  rfam: false
