import { useEffect, useMemo, useRef, useState } from 'react';
import type { RunResult, WorkspaceFile } from '../../types';
import { workspacePathOf } from '../../types';
import { StructureViewer } from './StructureViewer';

type RecordValue = Record<string, unknown>;
const valueRecord = (value: unknown): RecordValue => (value && typeof value === 'object' ? value as RecordValue : {});
const valueString = (value: unknown): string => typeof value === 'string' ? value : value == null ? '' : String(value);
const arrayItems = (value: unknown): unknown[] => Array.isArray(value) ? value : [];
const fileName = (path: string): string => path.split(/[\\/]/).filter(Boolean).pop() || path || 'artifact';
const pathIsSafe = (path: string): boolean => Boolean(path) && !path.startsWith('/') && !path.split('/').includes('..') && !path.includes('\\');
const artifactPath = (value: unknown): string => typeof value === 'string' ? value : workspacePathOf(value as WorkspaceFile);
function fileUrl(sessionId: string, path: string, viewer?: string): string {
  if (!pathIsSafe(path)) return '#';
  const query = new URLSearchParams({ session_id: sessionId, path }); if (viewer) query.set('viewer', viewer);
  return `/workspace/file?${query.toString()}`;
}

function evidenceRecords(result: RunResult): RecordValue[] {
  const evidence = valueRecord(result?.evidence); const a = arrayItems(evidence.outputs); const b = arrayItems(evidence.tool_outputs);
  return [...a, ...b].map(valueRecord);
}
function collectImages(result: RunResult, suffixes: string[]): { path: string; label: string }[] {
  const out: { path: string; label: string }[] = []; const seen = new Set<string>(); const add = (path: unknown, label?: unknown) => { const value = artifactPath(path); if (!value || seen.has(value) || !suffixes.some(s => value.toLowerCase().split(/[?#]/)[0].endsWith(s))) return; seen.add(value); out.push({ path: value, label: valueString(label) || fileName(value) }); };
  for (const item of evidenceRecords(result)) add(item.image_path, item.label || item.summary || item.tool);
  for (const item of arrayItems(result?.artifacts)) if (valueRecord(item).kind === 'image') add(valueRecord(item).path, valueRecord(item).label);
  const tools = new Set(arrayItems(valueRecord(result?.evidence).tools).map(String)); if (!out.length && ['table_plot', 'pipeline_shell', 'genome_read_features', 'genome_render_map'].some(t => tools.has(t))) for (const item of arrayItems(result?.files)) if (valueRecord(item).kind === 'image') add(valueRecord(item).path, valueRecord(item).label);
  return out;
}
function collectStructures(result: RunResult): { path: string; label: string; pdbId: string; format: 'pdb' | 'cif' }[] {
  const out: { path: string; label: string; pdbId: string; format: 'pdb' | 'cif' }[] = []; const seen = new Set<string>(); const add = (path: unknown, label?: unknown) => { const value = artifactPath(path); if (!value || seen.has(value) || !/\.(?:pdb|cif|mmcif)$/i.test(value)) return; seen.add(value); const combined = `${valueString(label)} ${fileName(value)}`; const id = (combined.match(/\b([0-9][A-Za-z0-9]{3})\b/)?.[1] || '').toUpperCase(); out.push({ path: value, label: valueString(label) || fileName(value), pdbId: id, format: /\.pdb$/i.test(value) ? 'pdb' : 'cif' }); };
  for (const item of evidenceRecords(result)) if (['structure_inspect', 'pdb_download', 'alphafold_download'].includes(valueString(item.tool))) add(item.structure_path, item.pdb_id || item.summary);
  if (!out.length) for (const item of arrayItems(result?.artifacts)) if (valueRecord(item).kind === 'structure') add(valueRecord(item).path, valueRecord(item).label);
  const tools = new Set(arrayItems(valueRecord(result?.evidence).tools).map(String)); if (!out.length && ['structure_inspect', 'pdb_download', 'alphafold_download'].some(t => tools.has(t))) for (const item of arrayItems(result?.files)) if (valueRecord(item).kind === 'structure') add(valueRecord(item).path, valueRecord(item).label);
  return out;
}
function collectGenomeMaps(result: RunResult): string[] { const out = new Set<string>(); for (const item of evidenceRecords(result)) { const path = artifactPath(item.genome_map_path); if (fileName(path).toLowerCase() === 'genome_map.json') out.add(path); } if (!out.size) for (const item of arrayItems(result?.artifacts)) if (valueRecord(item).kind === 'genome_map') { const path = artifactPath(valueRecord(item).path); if (fileName(path).toLowerCase() === 'genome_map.json') out.add(path); } if (!out.size && arrayItems(valueRecord(result?.evidence).tools).map(String).includes('genome_render_map')) for (const item of arrayItems(result?.files)) if (valueRecord(item).kind === 'genome_map') { const path = artifactPath(valueRecord(item).path); if (fileName(path).toLowerCase() === 'genome_map.json') out.add(path); } return [...out]; }
function collectPipelineOutputs(result: RunResult): { path: string; label: string; kind: string }[] { const out: { path: string; label: string; kind: string }[] = []; const seen = new Set<string>(); for (const item of evidenceRecords(result)) if (item.tool === 'pipeline_shell' && Array.isArray(item.output_records)) for (const record of item.output_records as unknown[]) { const value = valueRecord(record); const path = artifactPath(value.path); if (path && !seen.has(path) && value.exists !== false) { seen.add(path); out.push({ path, label: valueString(value.label || value.name) || fileName(path), kind: valueString(value.kind) || 'file' }); } } if (!out.length) for (const item of arrayItems(result?.files)) { const value = valueRecord(item); const path = artifactPath(value.path); if (value.source_skill === 'pipeline_shell' && path && !seen.has(path) && !['config', 'directory', 'input', 'upload'].includes(valueString(value.kind))) { seen.add(path); out.push({ path, label: valueString(value.label) || fileName(path), kind: valueString(value.kind) || 'file' }); } } return out; }

function PipelineDownloads({ result, sessionId }: { result: RunResult; sessionId: string }) { const records = collectPipelineOutputs(result); const bundle = arrayItems(result?.files).filter(item => { const v = valueRecord(item); return v.source_skill === 'pipeline_shell' && v.kind === 'compressed' && /\.zip$/i.test(artifactPath(v.path)); }); if (!records.length && !bundle.length) return null; const pipeline = evidenceRecords(result).reverse().find(x => x.tool === 'pipeline_shell' && x.pipeline_name)?.pipeline_name; return <section className="pipeline-downloads"><div className="pipeline-downloads-heading"><strong>{records.length ? 'Result downloads' : 'Collected result bundle'}</strong><span>{records.length ? `${records.length} files` : ''}</span></div><div className="pipeline-download-grid">{(records.length ? records : bundle.map(x => ({ path: artifactPath(valueRecord(x).path), label: 'Download all collected results', kind: 'ZIP archive' }))).map(record => <a className="pipeline-download" key={record.path} href={fileUrl(sessionId, record.path)} download={fileName(record.path)}><span>{record.label}</span><small>{fileName(record.path)} · {record.kind}</small></a>)}</div>{records.length && <p className="pipeline-download-note">Result contents are not previewed automatically. To review them here, ask: <q>Collect and show all results from the {valueString(pipeline) || 'pipeline'} pipeline run.</q></p>}</section>; }

function FigureArtifacts({ result, sessionId, suffixes }: { result: RunResult; sessionId: string; suffixes: string[] }) { const images = collectImages(result, suffixes); return images.length ? <div className="artifact-list">{images.map(image => <figure className="artifact-figure" key={image.path}><div className="artifact-figure-frame"><img src={fileUrl(sessionId, image.path)} alt={image.label} loading="lazy" /></div><figcaption><span>{image.label}</span><a href={fileUrl(sessionId, image.path)} target="_blank" rel="noopener noreferrer">Open figure</a></figcaption></figure>)}</div> : null; }

function GenomeCard({ path, sessionId }: { path: string; sessionId: string }) { const [open, setOpen] = useState(false); const [status, setStatus] = useState('Open to load genome browser.'); const [map, setMap] = useState<RecordValue | null>(null); const host = useRef<HTMLDivElement>(null); useEffect(() => { if (!open || map) return; let cancelled = false; fetch(fileUrl(sessionId, path)).then(response => { if (!response.ok) throw new Error(`Genome map request failed (${response.status}).`); return response.json(); }).then(value => { if (!cancelled) { const parsed = valueRecord(value); if (parsed.schema_version !== 1 || parsed.coordinates !== '0-based-half-open' || !Array.isArray(parsed.features)) throw new Error('Invalid genome browser artifact.'); setMap(parsed); setStatus(parsed.features.length ? '' : 'No annotated features were found.'); } }).catch(error => !cancelled && setStatus(error instanceof Error ? error.message : String(error))); return () => { cancelled = true; }; }, [open, map, path, sessionId]); useEffect(() => { if (!open || !map || !host.current) return; let disposed = false; (async () => { try { const loadRemoteModule = new Function('url', 'return import(url)') as (url: string) => Promise<any>;
      const module = await loadRemoteModule('https://cdn.jsdelivr.net/npm/igv@3.0.0/dist/igv.esm.min.js'); if (disposed || !host.current) return; const igv = (module as any).default || module; const id = valueString(map.sequence_id); const length = Number(map.genome_length || 1); const browser = await igv.createBrowser(host.current, { reference: { id, name: valueString(map.title || id), fastaURL: fileUrl(sessionId, valueString(map.reference_path)), format: valueString(map.reference_format) || 'fasta', wholeGenomeView: false }, locus: `${id}:1-${length}`, tracks: [{ name: 'Annotations', type: 'annotation', format: 'bed', features: (map.features as unknown[]).map(valueRecord).map(feature => ({ chr: valueString(feature.chr), start: Number(feature.start), end: Number(feature.end), strand: valueString(feature.strand), color: valueString(feature.color), name: valueString(feature.name) })), displayMode: 'EXPANDED', height: 160 }] }); if (disposed) igv.removeBrowser?.(browser); else setStatus(valueString(map.truncated) === 'true' ? 'This view contains the first 50,000 feature segments.' : ''); } catch (error) { if (!disposed) setStatus(`Could not load genome browser: ${error instanceof Error ? error.message : String(error)}`); } })(); return () => { disposed = true; }; }, [open, map, path, sessionId]); return <details className="genome-viewer-details" open={open} onToggle={event => setOpen((event.currentTarget as HTMLDetailsElement).open)}><summary>Genome browser <span>Explore annotations</span></summary><section className="genome-viewer-card"><div className="genome-viewer-heading"><div><span className="genome-eyebrow">SEQUENCE EXPLORER</span><strong>{valueString(map?.title || map?.sequence_id) || 'Genome annotations'}</strong><span>{map ? `${valueString(map.sequence_id)} · ${Number(map.genome_length || 0).toLocaleString()} bp · ${(map.features as unknown[] || []).length.toLocaleString()} feature segments` : 'Loading annotated sequence…'}</span></div></div><div ref={host} className="genome-browser" role="region" aria-label="Interactive genome browser">{!open && <div className="structure-loading">Open to load genome browser</div>}</div><p className="genome-status" role="status">{status}</p><div className="genome-viewer-footer"><span>Drag to pan · use + / − to zoom</span><a href={fileUrl(sessionId, path)} download>Download data</a></div></section></details>; }

export function ArtifactViews({ result, sessionId, imageSuffixes = ['.gif', '.jpeg', '.jpg', '.png', '.svg', '.webp'] }: { result: RunResult; sessionId: string; imageSuffixes?: string[] }) { const structures = useMemo(() => collectStructures(result), [result]); const genomes = useMemo(() => collectGenomeMaps(result), [result]); return <>{<PipelineDownloads result={result} sessionId={sessionId} />}{structures.map(item => <StructureViewer key={item.path} item={item} src={fileUrl(sessionId, item.path)} />)}{genomes.map(path => <GenomeCard key={path} path={path} sessionId={sessionId} />)}<FigureArtifacts result={result} sessionId={sessionId} suffixes={imageSuffixes} /></>; }

export { fileUrl, collectImages, collectStructures, collectGenomeMaps, collectPipelineOutputs };
