"""BioAgent pipeline implementation. Generated by consolidating the original modules."""
from __future__ import annotations

# --- original module: __init__.py ---
"""Snippy-based bacterial FASTQ variant pipeline."""

__version__ = "1.0.0"

# --- original module: filtering.py ---
"""Coverage and sliding-window recombination filters."""


import math
from bisect import bisect_left
from dataclasses import dataclass
from statistics import fmean, pstdev
from typing import FrozenSet, List, Mapping, Protocol, Sequence, Set, Tuple


class CoverageCalls(Protocol):
    variants: Mapping[int, str]

    def is_covered(self, position: int) -> bool:
        ...


@dataclass(frozen=True)
class FilterResult:
    initial_positions: Tuple[int, ...]
    coverage_positions: Tuple[int, ...]
    final_positions: Tuple[int, ...]
    coverage_removed: FrozenSet[int]
    recombination_removed: FrozenSet[int]
    recombination_regions: Tuple[Tuple[int, int], ...]
    window_mean: float
    window_sd: float


def filter_snps(
    samples: Sequence[CoverageCalls],
    reference_length: int,
    min_coverage_fraction: float = 0.9,
    window_size: int = 50,
    step_size: int = 10,
    sd_threshold: float = 3.0,
) -> FilterResult:
    initial = sorted(
        {
            position
            for sample in samples
            for position, base in sample.variants.items()
            if base != "N"
        }
    )
    required_samples = math.ceil(min_coverage_fraction * len(samples))
    coverage_positions = [
        position
        for position in initial
        if sum(sample.is_covered(position) for sample in samples) >= required_samples
    ]
    coverage_removed = frozenset(set(initial) - set(coverage_positions))
    regions, mean_density, density_sd = find_recombination_regions(
        coverage_positions,
        reference_length,
        window_size,
        step_size,
        sd_threshold,
    )
    recombination_removed: Set[int] = set()
    for start, end in regions:
        left = bisect_left(coverage_positions, start)
        right = bisect_left(coverage_positions, end)
        recombination_removed.update(coverage_positions[left:right])
    final = [
        position
        for position in coverage_positions
        if position not in recombination_removed
    ]
    return FilterResult(
        initial_positions=tuple(initial),
        coverage_positions=tuple(coverage_positions),
        final_positions=tuple(final),
        coverage_removed=coverage_removed,
        recombination_removed=frozenset(recombination_removed),
        recombination_regions=tuple(regions),
        window_mean=mean_density,
        window_sd=density_sd,
    )


def find_recombination_regions(
    positions: Sequence[int],
    reference_length: int,
    window_size: int,
    step_size: int,
    sd_threshold: float,
) -> Tuple[List[Tuple[int, int]], float, float]:
    if reference_length <= 0:
        return [], 0.0, 0.0
    starts = list(range(0, max(1, reference_length - window_size + 1), step_size))
    final_start = max(0, reference_length - window_size)
    if not starts or starts[-1] != final_start:
        starts.append(final_start)
    densities = [
        (
            bisect_left(positions, min(reference_length, start + window_size))
            - bisect_left(positions, start)
        )
        / min(window_size, reference_length - start)
        for start in starts
    ]
    mean_density = fmean(densities) if densities else 0.0
    density_sd = pstdev(densities) if len(densities) > 1 else 0.0
    threshold = mean_density + sd_threshold * density_sd
    candidates = [
        (start, min(reference_length, start + window_size))
        for start, density in zip(starts, densities)
        if density > threshold
    ]
    merged: List[Tuple[int, int]] = []
    for start, end in candidates:
        if merged and start <= merged[-1][1]:
            merged[-1] = (merged[-1][0], max(end, merged[-1][1]))
        else:
            merged.append((start, end))
    return merged, mean_density, density_sd

# --- original module: reference.py ---
#!/usr/bin/env python3
"""
Reference handling and GTDB selection for the bactmut-fastq pipeline.
Provides fast, memory-efficient access to GTDB reference genomes.
"""

import csv
import hashlib
import json
import os
import re
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterator, List, Optional, Set, Tuple

CACHE_DIR = Path.home() / ".bactmut"
CACHE_DIR.mkdir(parents=True, exist_ok=True)
CACHE_VERSION = 3
CONTIG_GAP_SIZE = 20

Record = Tuple[str, int]
SpeciesCache = Dict[str, Dict[str, List[Record]]]
RepresentativeIndex = Dict[str, Set[str]]
_REQUIRED_METADATA_FIELDS = (
    "accession",
    "ncbi_genbank_assembly_accession",
    "gtdb_taxonomy",
    "gtdb_representative",
)
_REQUIRED_TAXID_METADATA_FIELDS = ("ncbi_taxid", "ncbi_species_taxid")
_ASSEMBLY_ACCESSION_RE = re.compile(r"^(?:(?:RS|GB)_)?(GC[AF]_\d+)(?:\.\d+)?$")


@dataclass(frozen=True)
class ReferenceGenome:
    path: Path
    records: Dict[str, str]
    offsets: Dict[str, int]
    length: int

    def base(self, global_position: int) -> str:
        _, local_position, sequence = self.location(global_position)
        return sequence[local_position]

    def location(self, global_position: int) -> Tuple[str, int, str]:
        for name, offset in self.offsets.items():
            sequence = self.records[name]
            if offset <= global_position < offset + len(sequence):
                return name, global_position - offset, sequence
        raise IndexError(global_position)


class ReferenceManager:
    """Manage GTDB reference genomes with on-the-fly extraction."""

    def __init__(
        self, db_path: Optional[str] = None, metadata_path: Optional[str] = None
    ):
        if db_path is None:
            db_path = os.environ.get("GTDB_DB_PATH")
            if not db_path:
                raise ValueError(
                    "请设置环境变量 GTDB_DB_PATH\n"
                    "  export GTDB_DB_PATH=/path/to/representative.fa"
                )
        self.db_path = Path(db_path)
        if not self.db_path.exists():
            raise FileNotFoundError(f"数据库不存在: {self.db_path}")

        configured_metadata = metadata_path or os.environ.get("GTDB_METADATA_PATH")
        self.metadata_path = Path(configured_metadata) if configured_metadata else None
        self._species_cache: SpeciesCache = {}
        self._representative_index: Optional[RepresentativeIndex] = None
        self._taxid_index: Optional[RepresentativeIndex] = None
        self._species_taxid_index: Optional[RepresentativeIndex] = None
        self._cache_loaded = False

        # 缓存文件路径（基于数据库路径的哈希值，避免不同数据库混用）
        db_hash = hashlib.md5(str(self.db_path).encode()).hexdigest()[:8]
        self.cache_file = CACHE_DIR / f"gtdb_index_{db_hash}.json"

    @staticmethod
    def _file_identity(path: Path) -> Dict[str, int]:
        stat = path.stat()
        return {"size": stat.st_size, "mtime_ns": stat.st_mtime_ns}

    @staticmethod
    def _normalize_assembly_id(value: object) -> Optional[str]:
        """Normalize a GTDB/NCBI assembly accession to its GCF/GCA identifier."""
        if not isinstance(value, str):
            return None
        match = _ASSEMBLY_ACCESSION_RE.fullmatch(value.strip())
        return match.group(1) if match else None

    @staticmethod
    def _gtdb_species(taxonomy: object) -> Optional[str]:
        """Extract the exact GTDB species name from a taxonomy string."""
        if not isinstance(taxonomy, str):
            return None
        for field in taxonomy.split(";"):
            field = field.strip()
            if field.startswith("s__"):
                species = field[3:].strip().lower()
                return species or None
        return None

    def _load_cache(self) -> bool:
        """Load the FASTA index and any valid representative index from disk."""
        if not self.cache_file.exists():
            return False
        try:
            with open(self.cache_file, "r") as f:
                data = json.load(f)
        except (json.JSONDecodeError, OSError, TypeError):
            self.cache_file.unlink(missing_ok=True)
            return False

        if not self._is_valid_fasta_cache(data):
            return False

        self._species_cache = {
            species: {
                assembly_id: [tuple(record) for record in records]
                for assembly_id, records in assemblies.items()
            }
            for species, assemblies in data["index"].items()
        }
        self._cache_loaded = True

        if self.metadata_path and self._is_valid_metadata_cache(data):
            self._representative_index = {
                species: set(assemblies)
                for species, assemblies in data["representatives"].items()
            }
            self._taxid_index = {
                taxid: set(assemblies)
                for taxid, assemblies in data["taxid_index"].items()
            }
            self._species_taxid_index = {
                taxid: set(assemblies)
                for taxid, assemblies in data["species_taxid_index"].items()
            }
        return True

    def _is_valid_fasta_cache(self, data: object) -> bool:
        """Return whether a disk cache has a valid FASTA index for this database."""
        if not isinstance(data, dict) or data.get("cache_version") != CACHE_VERSION:
            return False
        if data.get("db_path") != str(self.db_path):
            return False
        identity = self._file_identity(self.db_path)
        if data.get("db_size") != identity["size"]:
            return False
        if data.get("db_mtime_ns") != identity["mtime_ns"]:
            return False
        return self._is_valid_cache_index(data.get("index"))

    def _is_valid_metadata_cache(self, data: object) -> bool:
        """Return whether cached representatives match the configured metadata file."""
        if not isinstance(data, dict) or self.metadata_path is None:
            return False
        if not self.metadata_path.exists():
            return False
        identity = self._file_identity(self.metadata_path)
        if data.get("metadata_path") != str(self.metadata_path):
            return False
        if data.get("metadata_size") != identity["size"]:
            return False
        if data.get("metadata_mtime_ns") != identity["mtime_ns"]:
            return False
        return (
            self._is_valid_representative_index(data.get("representatives"))
            and self._is_valid_representative_index(data.get("taxid_index"))
            and self._is_valid_representative_index(data.get("species_taxid_index"))
        )

    @staticmethod
    def _is_valid_cache_index(index: object) -> bool:
        """Return whether a disk cache has the expected nested FASTA structure."""
        if not isinstance(index, dict):
            return False
        for species, assemblies in index.items():
            if not isinstance(species, str) or not isinstance(assemblies, dict):
                return False
            for assembly_id, records in assemblies.items():
                if not isinstance(assembly_id, str) or not isinstance(records, list):
                    return False
                for record in records:
                    if (
                        not isinstance(record, list)
                        or len(record) != 2
                        or not isinstance(record[0], str)
                        or not isinstance(record[1], int)
                    ):
                        return False
        return True

    @staticmethod
    def _is_valid_representative_index(index: object) -> bool:
        """Return whether cached representatives have the expected JSON structure."""
        if not isinstance(index, dict):
            return False
        for species, assemblies in index.items():
            if not isinstance(species, str) or not isinstance(assemblies, list):
                return False
            if not all(isinstance(assembly_id, str) for assembly_id in assemblies):
                return False
        return True

    def _save_cache(self) -> None:
        """Save the FASTA index and any loaded representative indexes to disk."""
        db_identity = self._file_identity(self.db_path)
        data = {
            "cache_version": CACHE_VERSION,
            "db_path": str(self.db_path),
            "db_size": db_identity["size"],
            "db_mtime_ns": db_identity["mtime_ns"],
            "index": self._species_cache,
        }
        if (
            self._representative_index is not None
            and self._taxid_index is not None
            and self._species_taxid_index is not None
            and self.metadata_path is not None
        ):
            metadata_identity = self._file_identity(self.metadata_path)
            data.update(
                {
                    "metadata_path": str(self.metadata_path),
                    "metadata_size": metadata_identity["size"],
                    "metadata_mtime_ns": metadata_identity["mtime_ns"],
                    "representatives": {
                        species: sorted(assemblies)
                        for species, assemblies in self._representative_index.items()
                    },
                    "taxid_index": {
                        taxid: sorted(assemblies)
                        for taxid, assemblies in self._taxid_index.items()
                    },
                    "species_taxid_index": {
                        taxid: sorted(assemblies)
                        for taxid, assemblies in self._species_taxid_index.items()
                    },
                }
            )
        with open(self.cache_file, "w") as f:
            json.dump(data, f)

    def _build_cache(self) -> None:
        """Scan FASTA headers to build species→assembly→record mappings."""
        if self._cache_loaded:
            return

        if self._load_cache():
            print(f"✅ 从缓存加载索引成功，共 {len(self._species_cache)} 个物种")
            return

        print("⏳ 正在构建参考基因组索引（首次使用，约需30秒）...")
        with open(self.db_path, "r") as f:
            pos = 0
            line = f.readline()
            while line:
                if line.startswith(">"):
                    parts = line[1:].strip().split(" ", 1)
                    seq_id = parts[0]
                    description = parts[1] if len(parts) > 1 else ""

                    species_match = re.match(r"^([A-Za-z]+ [a-z]+)", description)
                    if species_match:
                        species_name = species_match.group(1).lower()
                    else:
                        species_name = description.split(" strain ")[0].lower()

                    accession_match = re.search(r"(?:^|\s)acc_label=([^\s]+)", description)
                    assembly_id = accession_match.group(1) if accession_match else seq_id
                    assemblies = self._species_cache.setdefault(species_name, {})
                    assemblies.setdefault(assembly_id, []).append((seq_id, pos))

                pos = f.tell()
                line = f.readline()

        self._cache_loaded = True
        self._save_cache()
        print(f"索引构建完成，共 {len(self._species_cache)} 个物种")

    def _build_representative_index(self, require_taxid_fields: bool = False) -> None:
        """Stream GTDB metadata into compact representative and taxid indexes."""
        if self._representative_index is not None and (
            not require_taxid_fields
            or (
                self._taxid_index is not None
                and self._species_taxid_index is not None
            )
        ):
            return
        if self.metadata_path is None:
            raise ValueError("未配置 GTDB_METADATA_PATH")
        if not self.metadata_path.exists():
            raise FileNotFoundError(f"GTDB metadata 不存在: {self.metadata_path}")

        representatives: RepresentativeIndex = {}
        taxid_index: RepresentativeIndex = {}
        species_taxid_index: RepresentativeIndex = {}
        with open(self.metadata_path, "r", newline="") as handle:
            reader = csv.DictReader(handle, delimiter="\t")
            fieldnames = set(reader.fieldnames or [])
            missing = [field for field in _REQUIRED_METADATA_FIELDS if field not in fieldnames]
            if missing:
                raise ValueError(f"GTDB metadata 缺少必要字段: {', '.join(missing)}")
            missing_taxid = [
                field for field in _REQUIRED_TAXID_METADATA_FIELDS if field not in fieldnames
            ]
            if require_taxid_fields and missing_taxid:
                raise ValueError(f"GTDB metadata 缺少必要字段: {', '.join(missing_taxid)}")
            has_taxid_fields = not missing_taxid

            for row in reader:
                if row["gtdb_representative"] != "t":
                    continue
                species = self._gtdb_species(row.get("gtdb_taxonomy"))
                assembly_id = self._normalize_assembly_id(row.get("accession"))
                if assembly_id is None:
                    assembly_id = self._normalize_assembly_id(
                        row.get("ncbi_genbank_assembly_accession")
                    )
                if not species or not assembly_id:
                    continue

                representatives.setdefault(species, set()).add(assembly_id)
                if has_taxid_fields:
                    taxid = (row.get("ncbi_taxid") or "").strip()
                    species_taxid = (row.get("ncbi_species_taxid") or "").strip()
                    if taxid:
                        taxid_index.setdefault(taxid, set()).add(assembly_id)
                    if species_taxid:
                        species_taxid_index.setdefault(species_taxid, set()).add(assembly_id)

        self._representative_index = representatives
        if has_taxid_fields:
            self._taxid_index = taxid_index
            self._species_taxid_index = species_taxid_index
        else:
            self._taxid_index = None
            self._species_taxid_index = None
        self._save_cache()

    def _find_records_by_assembly_id(self, assembly_id: str) -> Optional[List[Record]]:
        """Find FASTA records for an assembly in the loaded species cache."""
        for assemblies in self._species_cache.values():
            records = assemblies.get(assembly_id)
            if records is not None:
                return records
        return None

    @staticmethod
    def _display_gtdb_species_name(species: str) -> str:
        """Format a normalized GTDB species key for user-facing errors."""
        parts = species.split(" ", 1)
        if len(parts) == 1:
            return parts[0].capitalize()
        epithet = parts[1]
        if "_" in epithet:
            base, *suffixes = epithet.split("_")
            epithet = "_".join(
                [base]
                + [suffix.upper() if len(suffix) == 1 else suffix for suffix in suffixes]
            )
        return f"{parts[0].capitalize()} {epithet}"

    def _taxid_candidate_text(self, assembly_ids: Set[str]) -> str:
        """Render taxid candidate assemblies with their GTDB species names."""
        representatives = self._representative_index or {}
        chunks = []
        for assembly_id in sorted(assembly_ids):
            species_names = sorted(
                self._display_gtdb_species_name(species)
                for species, assemblies in representatives.items()
                if assembly_id in assemblies
            )
            if species_names:
                chunks.append(f"{assembly_id} ({', '.join(species_names)})")
            else:
                chunks.append(assembly_id)
        return ", ".join(chunks)

    def _all_fasta_assembly_ids(self) -> List[str]:
        """Return all assembly identifiers present in the loaded FASTA cache."""
        return sorted(
            assembly_id
            for assemblies in self._species_cache.values()
            for assembly_id in assemblies
        )

    def _select_representative_assembly(
        self, species_name: str, matched_species: str, assemblies: Dict[str, List[Record]]
    ) -> List[Record]:
        """Resolve a multi-assembly species through GTDB representative metadata."""
        candidates = sorted(assemblies)
        candidate_text = ", ".join(candidates)
        if self.metadata_path is None:
            raise ValueError(
                f"物种名 '{species_name}' 对应多个 FASTA assembly: {candidate_text}; "
                "请设置 GTDB_METADATA_PATH"
            )

        self._build_representative_index()
        assert self._representative_index is not None
        representatives = self._representative_index.get(matched_species, set())
        if not representatives:
            raise ValueError(
                f"未找到物种名 '{species_name}' 的 GTDB representative; "
                f"FASTA 候选 assembly: {candidate_text}"
            )
        if len(representatives) > 1:
            representative_text = ", ".join(sorted(representatives))
            raise ValueError(
                f"物种名 '{species_name}' 对应多个 GTDB representative: "
                f"{representative_text}"
            )

        representative = next(iter(representatives))
        if representative not in assemblies:
            raise ValueError(
                f"物种名 '{species_name}' 的 GTDB representative '{representative}' "
                f"不在 FASTA 候选 assembly 中: {candidate_text}"
            )
        return assemblies[representative]

    def get_reference(self, species_name: str) -> str:
        """Retrieve a reference genome for a given species name."""
        self._build_cache()

        query = species_name.strip().lower()
        if query in self._species_cache:
            matched_species = query
        else:
            matches = [key for key in self._species_cache if query in key]
            if not matches:
                raise ValueError(f"未找到物种 '{species_name}' 在参考数据库中")
            if len(matches) > 1:
                raise ValueError(
                    f"物种名 '{species_name}' 不唯一，匹配项: {', '.join(matches[:5])}"
                )
            matched_species = matches[0]

        assemblies = self._species_cache[matched_species]
        if len(assemblies) == 1:
            records = next(iter(assemblies.values()))
        else:
            records = self._select_representative_assembly(
                species_name, matched_species, assemblies
            )
        return self._extract_sequence(records)

    def get_reference_by_taxonid(self, taxid: str) -> str:
        """Retrieve a GTDB representative reference selected by NCBI Taxon ID."""
        if self.metadata_path is None:
            raise ValueError(
                f"Taxon ID '{taxid}' 查询需要配置 GTDB_METADATA_PATH"
            )

        if not self._cache_loaded and not self._load_cache():
            self._build_cache()
        self._build_representative_index(require_taxid_fields=True)
        assert self._taxid_index is not None
        assert self._species_taxid_index is not None

        assemblies = self._taxid_index.get(taxid, set())
        if not assemblies:
            assemblies = self._species_taxid_index.get(taxid, set())
        if not assemblies:
            raise ValueError(f"未找到 taxid '{taxid}' 对应的 GTDB representative")

        if len(assemblies) > 1:
            raise ValueError(
                f"taxid '{taxid}' 对应多个 GTDB representative: "
                f"{self._taxid_candidate_text(assemblies)}; "
                "请使用更具体的菌株级 Taxon ID 或改用 --species"
            )

        assembly_id = next(iter(assemblies))
        records = self._find_records_by_assembly_id(assembly_id)
        if records is None:
            candidate_text = ", ".join(self._all_fasta_assembly_ids())
            raise ValueError(
                f"taxid '{taxid}' 的 GTDB representative '{assembly_id}' "
                f"不在 FASTA 候选 assembly 中: {candidate_text}"
            )
        return self._extract_sequence(records)

    def _extract_sequence(self, records: List[Record]) -> str:
        """Create one pseudo-reference and a sidecar contig-coordinate map."""
        tmp_fd, tmp_path = tempfile.mkstemp(suffix=".fa", prefix="ref_")
        os.close(tmp_fd)
        map_path = Path(tmp_path).with_suffix(".contig_map.tsv")
        extracted: List[Tuple[str, str]] = []
        with open(self.db_path, "r") as f_in:
            for seq_id, offset in records:
                f_in.seek(offset)
                line = f_in.readline()
                if not line.startswith(">"):
                    raise ValueError(f"在偏移量 {offset} 处未找到序列头部")
                chunks = []
                while True:
                    line = f_in.readline()
                    if not line or line.startswith(">"):
                        break
                    chunks.append(line.strip())
                extracted.append((seq_id, "".join(chunks)))

        if not extracted:
            Path(tmp_path).unlink(missing_ok=True)
            raise ValueError("所选 assembly 不包含 FASTA 序列")

        pseudo_name = (
            extracted[0][0] if len(extracted) == 1 else f"{extracted[0][0]}_pseudo"
        )
        with open(tmp_path, "w") as f_out, open(map_path, "w") as map_out:
            f_out.write(f">{pseudo_name}\n")
            map_out.write(
                "pseudo_start\tpseudo_end\tcontig_id\tcontig_start\tcontig_end\n"
            )
            pseudo_position = 1
            for index, (seq_id, sequence) in enumerate(extracted):
                if index:
                    f_out.write("N" * CONTIG_GAP_SIZE)
                    pseudo_position += CONTIG_GAP_SIZE
                start = pseudo_position
                end = start + len(sequence) - 1
                f_out.write(sequence)
                map_out.write(f"{start}\t{end}\t{seq_id}\t1\t{len(sequence)}\n")
                pseudo_position = end + 1
            f_out.write("\n")

        return tmp_path

    def clear_cache(self) -> None:
        """Clear in-memory cache to free memory."""
        self._species_cache.clear()
        self._representative_index = None
        self._taxid_index = None
        self._species_taxid_index = None
        self._cache_loaded = False


_global_manager: Optional[ReferenceManager] = None


def get_reference_manager(db_path: Optional[str] = None) -> ReferenceManager:
    """Get the global ReferenceManager instance (singleton)."""
    global _global_manager
    if _global_manager is None:
        _global_manager = ReferenceManager(db_path)
    return _global_manager


def read_fasta(path: Path) -> Iterator[Tuple[str, str]]:
    """Read FASTA records without third-party dependencies."""
    name: Optional[str] = None
    chunks: List[str] = []
    with Path(path).open("r", encoding="ascii") as handle:
        for line_number, raw_line in enumerate(handle, 1):
            line = raw_line.strip()
            if not line:
                continue
            if line.startswith(">"):
                if name is not None:
                    yield name, "".join(chunks)
                name = line[1:].split()[0]
                if not name:
                    raise ValueError(f"Empty FASTA record name in {path}:{line_number}")
                chunks = []
                continue
            if name is None:
                raise ValueError(f"Sequence before FASTA header in {path}:{line_number}")
            sequence = line.upper()
            invalid = set(sequence) - set("ACGTRYSWKMBDHVN")
            if invalid:
                raise ValueError(
                    f"Invalid FASTA symbols {sorted(invalid)} in {path}:{line_number}"
                )
            chunks.append(sequence)
    if name is None:
        raise ValueError(f"No FASTA records found in {path}")
    yield name, "".join(chunks)


def load_reference(path: Path) -> ReferenceGenome:
    """Load a possibly multi-contig reference and assign global offsets."""
    path = Path(path).resolve()
    if not path.is_file():
        raise ValueError(f"Reference genome does not exist: {path}")
    records: Dict[str, str] = {}
    offsets: Dict[str, int] = {}
    offset = 0
    for name, sequence in read_fasta(path):
        if name in records:
            raise ValueError(f"Duplicate reference record name: {name}")
        records[name] = sequence
        offsets[name] = offset
        offset += len(sequence)
    return ReferenceGenome(path=path, records=records, offsets=offsets, length=offset)


def resolve_reference(
    reference: Optional[str] = None,
    species: Optional[str] = None,
    taxonid: Optional[str] = None,
) -> Tuple[Path, bool]:
    """Resolve a local or GTDB reference and report whether it is temporary."""
    if sum(bool(value) for value in (reference, species, taxonid)) != 1:
        raise ValueError("Provide exactly one of --reference, --species, or --taxonid")
    if reference:
        path = Path(reference).resolve()
        if not path.is_file():
            raise ValueError(f"Reference genome does not exist: {path}")
        return path, False

    manager = get_reference_manager()
    if species:
        return Path(manager.get_reference(species)), True
    return Path(manager.get_reference_by_taxonid(str(taxonid))), True

# --- original module: tree.py ---
"""IQ-TREE integration for tabular SNP matrices."""


import logging
import shutil
import subprocess
from pathlib import Path
from typing import Optional, Tuple


LOGGER = logging.getLogger(__name__)


def run_iqtree(
    matrix_tsv: Path,
    output_prefix: Path,
    model: str = "GTR+G",
    threads: int = 1,
) -> Tuple[str, Optional[Path]]:
    if type(threads) is not int or threads < 1:
        raise ValueError("IQ-TREE threads must be an integer >= 1")

    with Path(matrix_tsv).open("r", encoding="utf-8") as matrix_file:
        header = next(matrix_file).rstrip("\n").split("\t")
        samples = header[1:]
        rows = [
            (int(fields[0]), fields[1:])
            for line in matrix_file
            if line.strip()
            for fields in [line.rstrip("\n").split("\t")]
        ]
    if not rows:
        message = "skipped: no SNPs remained after filtering"
        LOGGER.warning(message)
        return message, None

    output_prefix = Path(output_prefix)
    output_prefix.parent.mkdir(parents=True, exist_ok=True)
    alignment_fasta = output_prefix.with_suffix(".fasta")
    rows.sort(key=lambda row: row[0])
    with alignment_fasta.open("w", encoding="ascii", newline="\n") as handle:
        for index, sample in enumerate(samples):
            sequence = "".join(values[index] for _, values in rows)
            handle.write(f">{sample}\n{sequence}\n")

    executable = shutil.which("iqtree2") or shutil.which("iqtree")
    if executable is None:
        message = "not built: IQ-TREE (iqtree2 or iqtree) was not found on PATH"
        LOGGER.warning(message)
        return message, None
    command = [
        executable,
        "-s",
        str(alignment_fasta),
        "-st",
        "DNA",
        "-m",
        model,
        "-nt",
        str(threads),
        "-pre",
        str(output_prefix),
        "-redo",
    ]
    completed = subprocess.run(command, capture_output=True, text=True, check=False)
    if completed.returncode != 0:
        detail = (completed.stderr or completed.stdout).strip().replace("\n", " ")
        message = f"failed: IQ-TREE exited with code {completed.returncode}: {detail}"
        LOGGER.error(message)
        return message, None

    treefile = Path(f"{output_prefix}.treefile")
    if not treefile.is_file():
        message = "failed: IQ-TREE returned success but did not create a .treefile"
        LOGGER.error(message)
        return message, None
    final_tree = output_prefix.parent / "final_tree.nwk"
    shutil.copyfile(treefile, final_tree)
    return "completed", final_tree

# --- original module: snippy_pipeline.py ---
"""FASTQ discovery, short-read alignment, and bcftools variant calling."""


import logging
import re
import subprocess
from bisect import bisect_right
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple



LOGGER = logging.getLogger(__name__)
FASTQ_SUFFIXES = (".fastq.gz", ".fq.gz", ".fastq", ".fq")
PAIR_RE = re.compile(
    r"^(?P<sample>.+?)(?:_R|_)(?P<read>[12])(?P<tail>(?:[_-].*)?)$",
    re.IGNORECASE,
)
CANONICAL = frozenset("ACGT")


@dataclass(frozen=True)
class BcftoolsVariant:
    region: str
    pos: int
    global_pos: int
    variant_type: str
    ref: str
    alt: str
    evidence: str
    ftype: str
    strand: str
    nt_pos: str
    aa_pos: str
    locus_tag: str
    gene: str
    product: str
    effect: str
    alt_freq: str
    depth: str
    pval: str = "NA"
    pass_filter: str = "TRUE"


@dataclass
class SampleCalls:
    name: str
    reads: Tuple[Path, ...]
    output_dir: Path
    variants: Dict[int, str] = field(default_factory=dict)
    variant_info: Dict[int, BcftoolsVariant] = field(default_factory=dict)
    intervals: List[Tuple[int, int]] = field(default_factory=list)
    _starts: List[int] = field(default_factory=list, init=False, repr=False)

    def finalize_intervals(self) -> None:
        merged: List[Tuple[int, int]] = []
        for start, end in sorted(self.intervals):
            if start >= end:
                continue
            if merged and start <= merged[-1][1]:
                merged[-1] = (merged[-1][0], max(end, merged[-1][1]))
            else:
                merged.append((start, end))
        self.intervals = merged
        self._starts = [start for start, _ in merged]

    def is_covered(self, position: int) -> bool:
        index = bisect_right(self._starts, position) - 1
        return index >= 0 and position < self.intervals[index][1]

    def base_at(self, position: int, reference_base: str) -> str:
        if position in self.variants:
            return self.variants[position]
        return reference_base if self.is_covered(position) else "N"


def _detect_pairs(input_path: Path) -> Dict[str, Tuple[Path, ...]]:
    """Accept one FASTQ file or discover single/paired reads in a directory."""
    input_path = Path(input_path)
    if input_path.is_file():
        if not _is_fastq(input_path):
            raise ValueError(f"FASTQ input is not a FASTQ file: {input_path}")
        fastqs = [input_path]
    elif input_path.is_dir():
        fastqs = [
            path
            for path in sorted(input_path.iterdir())
            if path.is_file() and _is_fastq(path)
        ]
    else:
        raise ValueError(f"FASTQ input does not exist: {input_path}")
    if not fastqs:
        raise ValueError(f"No FASTQ files found in {input_path}")

    candidates: Dict[Tuple[str, str], Dict[str, Path]] = {}
    for path in fastqs:
        match = PAIR_RE.match(_strip_fastq_suffix(path.name))
        if match is None:
            continue
        key = (match.group("sample"), match.group("tail") or "")
        candidates.setdefault(key, {})[match.group("read")] = path

    read_sets: Dict[str, Tuple[Path, ...]] = {}
    paired_paths = set()
    for (sample, _tail), mates in sorted(candidates.items()):
        if "1" not in mates or "2" not in mates:
            continue
        _add_read_set(read_sets, sample, (mates["1"], mates["2"]))
        paired_paths.update(mates.values())

    for path in fastqs:
        if path in paired_paths:
            continue
        _add_read_set(read_sets, _strip_fastq_suffix(path.name), (path,))
    return read_sets


def run_fastq_pipeline(
    reference: ReferenceGenome,
    input_path: Path,
    output_dir: Path,
    threads: int = 1,
) -> List[SampleCalls]:
    """Run minimap2, samtools, and bcftools for every detected sample."""
    if type(threads) is not int or threads < 1:
        raise ValueError("threads must be an integer >= 1")
    read_sets = _detect_pairs(Path(input_path))
    calls_root = Path(output_dir) / "bcftools"
    calls_root.mkdir(parents=True, exist_ok=True)

    samples: List[SampleCalls] = []
    for sample_name, reads in read_sets.items():
        sample_dir = calls_root / sample_name
        _run_bcftools_pipeline(reference.path, reads, sample_dir, threads)
        variant_info = parse_bcftools_vcf(sample_dir / "variants.vcf", reference)
        sample = SampleCalls(
            name=sample_name,
            reads=reads,
            output_dir=sample_dir,
            variants={position: variant.alt for position, variant in variant_info.items()},
            variant_info=variant_info,
            intervals=_covered_intervals_from_bam(sample_dir / "aligned.bam", reference),
        )
        sample.finalize_intervals()
        samples.append(sample)
        LOGGER.info("bcftools variant calling completed for %s", sample_name)
    return samples


def _covered_intervals_from_bam(
    bam_path: Path,
    reference: ReferenceGenome,
) -> List[Tuple[int, int]]:
    """Return half-open reference intervals with positive read depth."""
    command = ["samtools", "depth", str(bam_path)]
    LOGGER.debug("Running: %s", " ".join(command))
    process = subprocess.Popen(
        command,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        encoding="ascii",
        errors="replace",
    )
    assert process.stdout is not None
    intervals: List[Tuple[int, int]] = []
    current_start: Optional[int] = None
    current_end: Optional[int] = None
    try:
        for line_number, raw_line in enumerate(process.stdout, 1):
            if not raw_line.strip():
                continue
            fields = raw_line.rstrip("\n").split("\t")
            if len(fields) < 3:
                raise ValueError(f"Malformed samtools depth record at line {line_number}")
            region, pos_text, depth_text = fields[:3]
            if region not in reference.records:
                raise ValueError(f"samtools depth refers to unknown reference record: {region}")
            try:
                local_pos = int(pos_text)
                depth = int(depth_text)
            except ValueError as error:
                raise ValueError(f"Malformed samtools depth record at line {line_number}") from error
            if depth <= 0:
                continue
            if local_pos < 1 or local_pos > len(reference.records[region]):
                raise ValueError(f"samtools depth position outside reference record: {region}:{local_pos}")
            global_pos = reference.offsets[region] + local_pos - 1
            if current_start is None or current_end is None:
                current_start = global_pos
                current_end = global_pos + 1
            elif global_pos <= current_end:
                current_end = max(current_end, global_pos + 1)
            else:
                intervals.append((current_start, current_end))
                current_start = global_pos
                current_end = global_pos + 1
        stderr = process.stderr.read() if process.stderr else ""
        return_code = process.wait()
    except Exception:
        if process.poll() is None:
            process.kill()
        process.wait()
        raise
    if return_code != 0:
        detail = stderr.strip()
        raise RuntimeError(
            f"samtools depth failed for {bam_path} with code {return_code}: {detail}"
        )
    if current_start is not None and current_end is not None:
        intervals.append((current_start, current_end))
    return intervals


def parse_bcftools_vcf(
    vcf_path: Path,
    reference: ReferenceGenome,
) -> Dict[int, BcftoolsVariant]:
    """Parse genotype-supported SNP calls from a bcftools VCF."""
    variants: Dict[int, BcftoolsVariant] = {}
    header_seen = False
    with Path(vcf_path).open("r", encoding="utf-8") as handle:
        for line_number, raw_line in enumerate(handle, 1):
            if not raw_line.strip() or raw_line.startswith("##"):
                continue
            if raw_line.startswith("#CHROM"):
                columns = raw_line.rstrip("\n").split("\t")
                if len(columns) < 10:
                    raise ValueError("bcftools VCF must contain one sample column")
                header_seen = True
                continue
            if raw_line.startswith("#"):
                continue
            if not header_seen:
                raise ValueError("bcftools VCF is missing the #CHROM header")

            fields = raw_line.rstrip("\n").split("\t")
            if len(fields) < 10:
                raise ValueError(f"Malformed VCF record at {vcf_path}:{line_number}")
            region, pos_text, _identifier, ref, alt_text, _qual, filter_value, info_text, format_text, sample_text = fields[:10]
            if region not in reference.records:
                raise ValueError(f"bcftools VCF refers to unknown reference record: {region}")
            pos = int(pos_text)
            if pos < 1 or pos > len(reference.records[region]):
                raise ValueError(f"bcftools position outside reference record: {region}:{pos}")

            format_values = _parse_format(format_text, sample_text)
            alt_index = _called_alt_index(format_values.get("GT", "."), format_values.get("AD", ""))
            if alt_index is None:
                continue
            alternate_alleles = alt_text.upper().split(",")
            if alt_index > len(alternate_alleles):
                continue
            ref = ref.upper()
            alt = alternate_alleles[alt_index - 1]
            if not _is_snp_allele(ref, alt):
                continue

            info_values = _parse_info(info_text)
            ad = format_values.get("AD") or info_values.get("AD", "")
            alt_freq, depth = _vcf_metrics(ad, alt_index)
            if depth == "NA":
                depth = format_values.get("DP") or info_values.get("DP", "NA")
            global_pos = reference.offsets[region] + pos - 1
            variant = BcftoolsVariant(
                region=region,
                pos=pos,
                global_pos=global_pos,
                variant_type="SNP",
                ref=ref,
                alt=alt,
                evidence=f"AD={ad or 'NA'};DP={depth}",
                ftype="NA",
                strand="+",
                nt_pos="NA",
                aa_pos="NA",
                locus_tag="NA",
                gene="NA",
                product="NA",
                effect="NA",
                alt_freq=alt_freq,
                depth=depth,
                pass_filter="TRUE" if filter_value in {"PASS", "."} else "FALSE",
            )
            existing = variants.get(global_pos)
            if existing is None or _variant_rank(variant) > _variant_rank(existing):
                variants[global_pos] = variant
    if not header_seen:
        raise ValueError("bcftools VCF is missing the #CHROM header")
    return variants


def _run_bcftools_pipeline(
    reference: Path,
    reads: Sequence[Path],
    sample_dir: Path,
    threads: int,
) -> None:
    if len(reads) not in {1, 2}:
        raise ValueError("Variant calling requires one single-end read or one paired-end read set")
    sample_dir = Path(sample_dir)
    sample_dir.mkdir(parents=True, exist_ok=True)
    output_sam = sample_dir / "aligned.sam"
    unsorted_bam = sample_dir / "aligned.unsorted.bam"
    output_bam = sample_dir / "aligned.bam"
    output_vcf = sample_dir / "variants.vcf"

    minimap2_command = [
        "minimap2",
        "-ax",
        "sr",
        "-t",
        str(threads),
        str(reference),
        *[str(read) for read in reads],
    ]
    LOGGER.debug("Running: %s", " ".join(minimap2_command))
    with output_sam.open("w", encoding="ascii") as sam_file:
        subprocess.run(minimap2_command, stdout=sam_file, check=True)

    # Convert the text SAM explicitly before sorting.  Some samtools builds
    # infer BAM from `sort` input and otherwise reject a valid SAM stream.
    try:
        subprocess.run(
            ["samtools", "view", "-S", "-b", "-o", str(unsorted_bam), str(output_sam)],
            check=True,
        )
        subprocess.run(
            ["samtools", "sort", "-o", str(output_bam), str(unsorted_bam)],
            check=True,
        )
    finally:
        unsorted_bam.unlink(missing_ok=True)
    subprocess.run(["samtools", "index", str(output_bam)], check=True)

    mpileup_command = [
        "bcftools",
        "mpileup",
        "-a",
        "AD,DP",
        "-Q",
        "20",
        "-q",
        "30",
        "-f",
        str(reference),
        str(output_bam),
    ]
    call_command = [
        "bcftools",
        "call",
        "-mv",
        "-Ov",
        "-o",
        str(output_vcf),
    ]
    mpileup = subprocess.Popen(mpileup_command, stdout=subprocess.PIPE)
    try:
        if mpileup.stdout is None:
            raise RuntimeError("bcftools mpileup stdout pipe was not created")
        subprocess.run(call_command, stdin=mpileup.stdout, check=True)
        mpileup.stdout.close()
        return_code = mpileup.wait()
        if return_code != 0:
            raise subprocess.CalledProcessError(return_code, mpileup_command)
    except Exception:
        if mpileup.stdout is not None and not mpileup.stdout.closed:
            mpileup.stdout.close()
        if mpileup.poll() is None:
            mpileup.kill()
        mpileup.wait()
        raise


def _parse_format(format_text: str, sample_text: str) -> Dict[str, str]:
    keys = format_text.split(":")
    values = sample_text.split(":")
    return dict(zip(keys, values))


def _parse_info(info_text: str) -> Dict[str, str]:
    values: Dict[str, str] = {}
    for item in info_text.split(";"):
        if "=" in item:
            key, value = item.split("=", 1)
            values[key] = value
    return values


def _called_alt_index(genotype: str, ad: str) -> Optional[int]:
    allele_indexes = {
        int(value)
        for value in re.split(r"[/|]", genotype)
        if value.isdigit() and int(value) > 0
    }
    if not allele_indexes:
        return None
    depths = _parse_ad(ad)
    return max(
        allele_indexes,
        key=lambda index: depths[index] if index < len(depths) else -1,
    )


def _vcf_metrics(ad: str, alt_index: int = 1) -> Tuple[str, str]:
    depths = _parse_ad(ad)
    if not depths or alt_index >= len(depths):
        return "NA", "NA"
    ref_depth = depths[0]
    alt_depth = depths[alt_index]
    total_depth = ref_depth + alt_depth
    if total_depth == 0:
        return "NA", "0"
    frequency = f"{alt_depth / total_depth:.6f}".rstrip("0").rstrip(".")
    return frequency, str(total_depth)


def _parse_ad(ad: str) -> List[int]:
    if not ad or ad == ".":
        return []
    try:
        return [int(value) if value != "." else 0 for value in ad.split(",")]
    except ValueError:
        return []


def _variant_rank(variant: BcftoolsVariant) -> Tuple[float, int]:
    try:
        frequency = float(variant.alt_freq)
    except ValueError:
        frequency = -1.0
    try:
        depth = int(variant.depth)
    except ValueError:
        depth = -1
    return frequency, depth


def _is_snp_allele(ref: str, alt: str) -> bool:
    return (
        len(ref) == 1
        and len(alt) == 1
        and ref in CANONICAL
        and alt in CANONICAL
        and ref != alt
    )


def _is_fastq(path: Path) -> bool:
    return any(path.name.lower().endswith(suffix) for suffix in FASTQ_SUFFIXES)


def _strip_fastq_suffix(filename: str) -> str:
    lower = filename.lower()
    for suffix in FASTQ_SUFFIXES:
        if lower.endswith(suffix):
            return filename[: -len(suffix)]
    return Path(filename).stem


def _add_read_set(
    read_sets: Dict[str, Tuple[Path, ...]],
    sample: str,
    reads: Tuple[Path, ...],
) -> None:
    sample = re.sub(r"\s+", "_", sample.strip())
    if not sample:
        raise ValueError("FASTQ sample name is empty")
    if sample in read_sets:
        raise ValueError(f"Duplicate FASTQ sample name: {sample}")
    read_sets[sample] = reads

# --- original module: matrix.py ---
"""Filtered SNP matrix generation."""


from pathlib import Path
from typing import Sequence



def build_snp_matrix(
    samples: Sequence[SampleCalls],
    reference: ReferenceGenome,
    positions: Sequence[int],
    output_tsv: Path,
) -> None:
    if not samples:
        raise ValueError("No samples available for SNP matrix")
    output_tsv = Path(output_tsv)
    output_tsv.parent.mkdir(parents=True, exist_ok=True)
    with output_tsv.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write("pos\t" + "\t".join(sample.name for sample in samples) + "\n")
        for position in sorted(positions):
            reference_base = reference.base(position)
            calls = [sample.base_at(position, reference_base) for sample in samples]
            handle.write(f"{position + 1}\t" + "\t".join(calls) + "\n")

# --- original module: reporting.py ---
"""Variant and summary reports for Snippy calls."""


import csv
import re
from collections import Counter
from pathlib import Path
from typing import Optional, Sequence, Tuple



GENETIC_CODE = {
    "TTT": "F", "TTC": "F", "TTA": "L", "TTG": "L",
    "TCT": "S", "TCC": "S", "TCA": "S", "TCG": "S",
    "TAT": "Y", "TAC": "Y", "TAA": "*", "TAG": "*",
    "TGT": "C", "TGC": "C", "TGA": "*", "TGG": "W",
    "CTT": "L", "CTC": "L", "CTA": "L", "CTG": "L",
    "CCT": "P", "CCC": "P", "CCA": "P", "CCG": "P",
    "CAT": "H", "CAC": "H", "CAA": "Q", "CAG": "Q",
    "CGT": "R", "CGC": "R", "CGA": "R", "CGG": "R",
    "ATT": "I", "ATC": "I", "ATA": "I", "ATG": "M",
    "ACT": "T", "ACC": "T", "ACA": "T", "ACG": "T",
    "AAT": "N", "AAC": "N", "AAA": "K", "AAG": "K",
    "AGT": "S", "AGC": "S", "AGA": "R", "AGG": "R",
    "GTT": "V", "GTC": "V", "GTA": "V", "GTG": "V",
    "GCT": "A", "GCC": "A", "GCA": "A", "GCG": "A",
    "GAT": "D", "GAC": "D", "GAA": "E", "GAG": "E",
    "GGT": "G", "GGC": "G", "GGA": "G", "GGG": "G",
}
COMPLEMENT = str.maketrans("ACGT", "TGCA")
POSITION_RE = re.compile(r"^(\d+)(?:/\d+)?$")


def write_variants_table(
    variants_path: Path,
    reference: ReferenceGenome,
    samples: Sequence[SampleCalls],
    result: FilterResult,
    summary_path: Path,
) -> None:
    variants_path = Path(variants_path)
    variants_path.parent.mkdir(parents=True, exist_ok=True)
    effects: Counter[str] = Counter()
    with variants_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle, delimiter="\t", lineterminator="\n")
        writer.writerow(
            [
                "REGION",
                "POS",
                "REF",
                *[sample.name for sample in samples],
                "VARIANT_TYPE",
                "REF_CODON",
                "REF_AA",
                "ALT_CODON",
                "ALT_AA",
                "EFFECT",
                *[
                    column
                    for sample in samples
                    for column in (
                        f"{sample.name}_ALT_FREQ",
                        f"{sample.name}_DEPTH",
                        f"{sample.name}_PVAL",
                        f"{sample.name}_PASS",
                    )
                ],
            ]
        )
        for position in sorted(result.final_positions):
            event = _event_for_position(position, samples)
            if event is None:
                region, local_position, _ = reference.location(position)
                pos = local_position + 1
                ref = reference.base(position)
                variant_type = "UNKNOWN"
                annotation = ("NA", "NA", "NA", "NA")
                effect = "NA"
            else:
                region = event.region
                pos = event.pos
                ref = event.ref
                variant_type = event.variant_type
                annotation = _codon_annotation(event, reference)
                effect = event.effect
                if effect == "NA":
                    effect = _effect_annotation(annotation)
            effects[effect] += 1
            reference_base = reference.base(position)
            metadata = []
            for sample in samples:
                sample_event = sample.variant_info.get(position)
                if sample_event is None:
                    metadata.extend(["NA", "NA", "NA", "NA"])
                else:
                    metadata.extend(
                        [
                            sample_event.alt_freq,
                            sample_event.depth,
                            sample_event.pval,
                            sample_event.pass_filter,
                        ]
                    )
            writer.writerow(
                [
                    region,
                    pos,
                    ref,
                    *[sample.base_at(position, reference_base) for sample in samples],
                    variant_type,
                    *annotation,
                    effect,
                    *metadata,
                ]
            )

    summary_path = Path(summary_path)
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    with summary_path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(f"initial_variant_positions\t{len(result.initial_positions)}\n")
        handle.write(f"after_coverage_filter\t{len(result.coverage_positions)}\n")
        handle.write(f"after_recombination_filter\t{len(result.final_positions)}\n")
        handle.write(f"coverage_removed\t{len(result.coverage_removed)}\n")
        handle.write(f"recombination_removed\t{len(result.recombination_removed)}\n")
        for effect in sorted(effects):
            handle.write(f"{effect}\t{effects[effect]}\n")


def _event_for_position(
    position: int,
    samples: Sequence[SampleCalls],
) -> Optional[BcftoolsVariant]:
    for sample in samples:
        event = sample.variant_info.get(position)
        if event is not None:
            return event
    return None


def _codon_annotation(
    event: BcftoolsVariant,
    reference: ReferenceGenome,
) -> Tuple[str, str, str, str]:
    if (
        event.variant_type != "SNP"
        or len(event.ref) != 1
        or len(event.alt) != 1
        or event.strand not in {"+", "-"}
    ):
        return "NA", "NA", "NA", "NA"

    _, local_position, sequence = reference.location(event.global_pos)
    if event.nt_pos == "NA":
        coding_position = local_position + 1
    else:
        match = POSITION_RE.fullmatch(event.nt_pos)
        if match is None:
            return "NA", "NA", "NA", "NA"
        coding_position = int(match.group(1))
    offset_in_codon = (coding_position - 1) % 3
    if event.strand == "+":
        codon_start = local_position - offset_in_codon
        if codon_start < 0:
            return "NA", "NA", "NA", "NA"
        ref_codon = sequence[codon_start : codon_start + 3].upper()
        if len(ref_codon) != 3:
            return "NA", "NA", "NA", "NA"
        alt_codon = (
            ref_codon[:offset_in_codon]
            + event.alt
            + ref_codon[offset_in_codon + 1 :]
        )
    else:
        genomic_positions = [
            local_position + offset_in_codon - index for index in range(3)
        ]
        if min(genomic_positions) < 0 or max(genomic_positions) >= len(sequence):
            return "NA", "NA", "NA", "NA"
        ref_codon = "".join(
            sequence[position].translate(COMPLEMENT) for position in genomic_positions
        ).upper()
        coding_alt = event.alt.translate(COMPLEMENT)
        alt_codon = (
            ref_codon[:offset_in_codon]
            + coding_alt
            + ref_codon[offset_in_codon + 1 :]
        )
    if set(ref_codon + alt_codon) - set("ACGT"):
        return "NA", "NA", "NA", "NA"
    return (
        ref_codon,
        GENETIC_CODE.get(ref_codon, "X"),
        alt_codon,
        GENETIC_CODE.get(alt_codon, "X"),
    )


def _effect_annotation(annotation: Tuple[str, str, str, str]) -> str:
    _, ref_aa, _, alt_aa = annotation
    if "NA" in annotation or "X" in (ref_aa, alt_aa):
        return "NA"
    if ref_aa != "*" and alt_aa == "*":
        return "stop_gained"
    if ref_aa == "*" and alt_aa != "*":
        return "stop_lost"
    if ref_aa == alt_aa:
        return "synonymous"
    return "nonsynonymous"

# --- original module: cli.py ---
"""Command-line interface for the FASTQ-only bacterial pipeline."""


import argparse
import logging
import os
import shutil
import subprocess
from pathlib import Path
from typing import Mapping, Optional, Sequence



LOGGER = logging.getLogger(__name__)


def positive_int(value: str) -> int:
    try:
        parsed = int(value)
    except ValueError as error:
        raise argparse.ArgumentTypeError("must be a positive integer") from error
    if parsed < 1:
        raise argparse.ArgumentTypeError("must be a positive integer")
    return parsed


def positive_taxid(value: str) -> str:
    if not value.isdigit() or int(value) < 1:
        raise argparse.ArgumentTypeError("taxonid must be a positive integer")
    return value


def fraction(value: str) -> float:
    parsed = float(value)
    if not 0 < parsed <= 1:
        raise argparse.ArgumentTypeError("must be greater than 0 and at most 1")
    return parsed


def nonnegative_float(value: str) -> float:
    parsed = float(value)
    if parsed < 0:
        raise argparse.ArgumentTypeError("must be non-negative")
    return parsed


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="bactmut-fastq",
        description=(
            "Call bacterial variants from FASTQ reads with Snippy, filter SNPs, "
            "and build an IQ-TREE phylogeny."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--input", required=True, help="directory containing FASTQ reads")
    parser.add_argument("--output", required=True, help="directory for pipeline outputs")
    source_group = parser.add_mutually_exclusive_group(required=True)
    source_group.add_argument("--reference", help="local reference FASTA")
    source_group.add_argument("--species", help="species name resolved from the GTDB database")
    source_group.add_argument(
        "--taxonid",
        type=positive_taxid,
        help="NCBI strain or species Taxonomy ID resolved from GTDB metadata",
    )
    parser.add_argument(
        "--threads",
        type=positive_int,
        default=max(1, min(8, os.cpu_count() or 1)),
        help="CPUs passed to each Snippy run and IQ-TREE",
    )
    parser.add_argument(
        "--min-coverage",
        type=fraction,
        default=0.9,
        help="minimum sample fraction callable at an SNP position",
    )
    parser.add_argument(
        "--window-size",
        type=positive_int,
        default=50,
        help="recombination scan window size in bp",
    )
    parser.add_argument(
        "--step-size",
        type=positive_int,
        default=10,
        help="recombination scan step size in bp",
    )
    parser.add_argument(
        "--sd-threshold",
        type=nonnegative_float,
        default=3.0,
        help="standard deviations above mean SNP density used to flag windows",
    )
    parser.add_argument("--verbose", action="store_true", help="enable detailed logging")
    return parser


def configure_logging(output_dir: Path, verbose: bool) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    level = logging.DEBUG if verbose else logging.INFO
    formatter = logging.Formatter("%(asctime)s [%(levelname)s] %(message)s")
    console = logging.StreamHandler()
    console.setFormatter(formatter)
    file_handler = logging.FileHandler(output_dir / "pipeline.log", encoding="utf-8")
    file_handler.setFormatter(formatter)
    logging.basicConfig(level=level, handlers=[console, file_handler], force=True)


def run_pipeline(arguments: Mapping[str, object]) -> int:
    output_dir = Path(str(arguments["output"])).resolve()
    reference_path, temporary = resolve_reference(
        reference=_optional_text(arguments.get("reference")),
        species=_optional_text(arguments.get("species")),
        taxonid=_optional_text(arguments.get("taxonid")),
    )
    temporary_map = (
        reference_path.with_suffix(".contig_map.tsv") if temporary else None
    )
    if temporary_map and temporary_map.is_file():
        output_dir.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(temporary_map, output_dir / "reference_contig_map.tsv")
    try:
        reference = load_reference(reference_path)
        samples = run_fastq_pipeline(
            reference=reference,
            input_path=Path(str(arguments["input"])).resolve(),
            output_dir=output_dir,
            threads=int(arguments["threads"]),
        )
        result = filter_snps(
            samples=samples,
            reference_length=reference.length,
            min_coverage_fraction=float(arguments["min_coverage"]),
            window_size=int(arguments["window_size"]),
            step_size=int(arguments["step_size"]),
            sd_threshold=float(arguments["sd_threshold"]),
        )
        matrix_path = output_dir / "matrix.tsv"
        build_snp_matrix(samples, reference, result.final_positions, matrix_path)
        write_variants_table(
            output_dir / "variants.tsv",
            reference,
            samples,
            result,
            output_dir / "variants_summary.txt",
        )
        tree_status, _ = run_iqtree(
            matrix_path,
            output_dir / "tree",
            threads=int(arguments["threads"]),
        )
        LOGGER.info(
            "Completed: %d initial SNPs, %d final SNPs; tree %s",
            len(result.initial_positions),
            len(result.final_positions),
            tree_status,
        )
        return 0
    finally:
        if temporary:
            try:
                reference_path.unlink(missing_ok=True)
                if temporary_map:
                    temporary_map.unlink(missing_ok=True)
            except OSError as error:
                LOGGER.warning("Unable to remove temporary reference %s: %s", reference_path, error)


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    output_dir = Path(args.output).resolve()
    configure_logging(output_dir, args.verbose)
    try:
        return run_pipeline(vars(args))
    except (OSError, ValueError, RuntimeError, subprocess.SubprocessError) as error:
        LOGGER.error("Pipeline failed: %s", error)
        return 2


def _optional_text(value: object) -> Optional[str]:
    return None if value is None else str(value)

# --- original module: config_runner.py ---
"""BioAgent YAML configuration entry point for bactmut-fastq."""


import json
import math
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence

import yaml


class ConfigError(ValueError):
    """Raised when a BioAgent runtime configuration is invalid."""


_OUTPUT_DEFAULTS = {
    "matrix_path": "matrix.tsv",
    "variants_path": "variants.tsv",
    "variants_summary_path": "variants_summary.txt",
    "final_tree_path": "final_tree.nwk",
    "tree_alignment_path": "tree.fasta",
    "treefile_path": "tree.treefile",
    "iqtree_report_path": "tree.iqtree",
    "iqtree_log_path": "tree.log",
    "pipeline_log_path": "pipeline.log",
}
_REQUIRED_OUTPUT_KEYS = (
    "report_path",
    "metrics_path",
    "matrix_path",
    "variants_path",
    "variants_summary_path",
)


@dataclass(frozen=True)
class PipelineConfig:
    label: str
    input_path: Path
    reference_path: Path | None
    output_dir: Path
    output_paths: Mapping[str, Path]
    reference_mode: str
    species: str | None
    taxonid: str | None
    threads: int
    min_coverage: float
    window_size: int
    step_size: int
    sd_threshold: float
    verbose: bool

    def pipeline_arguments(self) -> dict[str, object]:
        return {
            "input": str(self.input_path),
            "output": str(self.output_dir),
            "reference": str(self.reference_path) if self.reference_mode == "local" else None,
            "species": self.species if self.reference_mode == "species" else None,
            "taxonid": self.taxonid if self.reference_mode == "taxonid" else None,
            "threads": self.threads,
            "min_coverage": self.min_coverage,
            "window_size": self.window_size,
            "step_size": self.step_size,
            "sd_threshold": self.sd_threshold,
            "verbose": self.verbose,
        }


def load_config(config_path: str | Path) -> PipelineConfig:
    path = Path(config_path).expanduser()
    if not path.is_file():
        raise ConfigError(f"configuration file not found: {path}")
    try:
        with path.open(encoding="utf-8") as stream:
            raw = yaml.safe_load(stream)
    except yaml.YAMLError as error:
        raise ConfigError(f"invalid YAML in {path}: {error}") from error
    if not isinstance(raw, Mapping):
        raise ConfigError("configuration root must be a YAML mapping")
    return parse_config(raw, base_dir=path.resolve().parent)


def parse_config(raw: Mapping[str, Any], *, base_dir: Path) -> PipelineConfig:
    base_dir = Path(base_dir).resolve()
    params = raw.get("params")
    if not isinstance(params, Mapping):
        params = {}

    def param(key: str, default: Any = None) -> Any:
        return raw.get(key, params.get(key, default))

    label = _nonempty_string(raw.get("label"), "label")
    input_path = _resolve_path(raw.get("input_path"), "input_path", base_dir)
    output_dir = _resolve_path(raw.get("output_dir"), "output_dir", base_dir)
    reference_path = _optional_path(raw.get("reference_path"), "reference_path", base_dir)
    reference_mode = _choice(
        param("reference_mode", "local"),
        "params.reference_mode",
        {"local", "species", "taxonid"},
    )
    species = _optional_string(param("species"))
    taxonid = _optional_taxonid(param("taxonid"))
    if reference_mode == "local" and reference_path is None:
        raise ConfigError("reference_mode 'local' requires reference_path")
    if reference_mode == "species" and species is None:
        raise ConfigError("reference_mode 'species' requires non-empty params.species")
    if reference_mode == "taxonid" and taxonid is None:
        raise ConfigError("reference_mode 'taxonid' requires positive params.taxonid")

    output_paths: dict[str, Path] = {
        "report_path": _resolve_path(raw.get("report_path"), "report_path", base_dir),
        "metrics_path": _resolve_path(raw.get("metrics_path"), "metrics_path", base_dir),
    }
    for key, filename in _OUTPUT_DEFAULTS.items():
        value = raw.get(key)
        output_paths[key] = (
            _resolve_path(value, key, base_dir)
            if value not in (None, "")
            else output_dir / filename
        )

    return PipelineConfig(
        label=label,
        input_path=input_path,
        reference_path=reference_path,
        output_dir=output_dir,
        output_paths=output_paths,
        reference_mode=reference_mode,
        species=species,
        taxonid=taxonid,
        threads=_positive_integer(param("threads", 1), "params.threads"),
        min_coverage=_fraction(param("min_coverage", 0.9), "params.min_coverage"),
        window_size=_positive_integer(param("window_size", 50), "params.window_size"),
        step_size=_positive_integer(param("step_size", 10), "params.step_size"),
        sd_threshold=_nonnegative_float(
            param("sd_threshold", 3.0), "params.sd_threshold"
        ),
        verbose=_boolean(param("verbose", False), "params.verbose"),
    )


def run_config(config: PipelineConfig) -> int:
    if not config.input_path.exists():
        raise ConfigError(f"input_path does not exist: {config.input_path}")
    if config.reference_mode == "local":
        assert config.reference_path is not None
        if not config.reference_path.is_file():
            raise ConfigError(f"reference_path is not a file: {config.reference_path}")
    missing_tools = [
        executable
        for executable in ("minimap2", "samtools", "bcftools")
        if shutil.which(executable) is None
    ]
    if missing_tools:
        raise ConfigError(
            "required executable(s) not found on PATH: " + ", ".join(missing_tools)
        )

    config.output_dir.mkdir(parents=True, exist_ok=True)

    configure_logging(config.output_dir, config.verbose)
    result = run_pipeline(config.pipeline_arguments())
    if int(result or 0) != 0:
        raise RuntimeError(f"bactmut-fastq exited with status {result}")

    _publish_outputs(config)
    metrics = _build_metrics(config)
    _write_metrics(config.output_paths["metrics_path"], metrics)
    _write_report(config, metrics)
    _assert_required_outputs(config)
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    if len(args) != 1:
        print(
            "Usage: python3 -m bactmut_fastq.config_runner CONFIG.yaml",
            file=sys.stderr,
        )
        return 2
    try:
        return run_config(load_config(args[0]))
    except (
        ConfigError,
        OSError,
        RuntimeError,
        ValueError,
        subprocess.SubprocessError,
    ) as error:
        print(f"bactmut_fastq pipeline error: {error}", file=sys.stderr)
        return 1


def _publish_outputs(config: PipelineConfig) -> None:
    for key, filename in _OUTPUT_DEFAULTS.items():
        source = config.output_dir / filename
        destination = config.output_paths[key]
        if not source.is_file() or source.resolve() == destination.resolve():
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)


def _build_metrics(config: PipelineConfig) -> dict[str, object]:
    summary = _read_key_value_file(config.output_dir / "variants_summary.txt")
    matrix_path = config.output_dir / "matrix.tsv"
    sample_count = None
    if matrix_path.is_file():
        with matrix_path.open(encoding="utf-8") as handle:
            header = handle.readline().rstrip("\n").split("\t")
        sample_count = max(0, len(header) - 1)

    final_positions = _as_integer(summary.get("after_recombination_filter"))
    final_tree = config.output_dir / "final_tree.nwk"
    if final_tree.is_file():
        tree_status = "completed"
    elif final_positions == 0:
        tree_status = "skipped: no SNPs remained after filtering"
    else:
        tree_status = "not generated (IQ-TREE unavailable or failed)"
    return {
        "pipeline": "bactmut_fastq",
        "label": config.label,
        "status": "completed",
        "reference_mode": config.reference_mode,
        "sample_count": sample_count,
        "initial_variant_positions": _as_integer(
            summary.get("initial_variant_positions")
        ),
        "after_coverage_filter": _as_integer(summary.get("after_coverage_filter")),
        "final_snp_positions": final_positions,
        "coverage_removed": _as_integer(summary.get("coverage_removed")),
        "recombination_removed": _as_integer(summary.get("recombination_removed")),
        "tree_status": tree_status,
    }


def _read_key_value_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.is_file():
        return values
    for line in path.read_text(encoding="utf-8").splitlines():
        if "\t" in line:
            key, value = line.split("\t", 1)
            values[key] = value
    return values


def _as_integer(value: str | None) -> int | None:
    if value is None:
        return None
    try:
        return int(value)
    except ValueError:
        return None


def _write_metrics(path: Path, metrics: Mapping[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(metrics, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def _write_report(config: PipelineConfig, metrics: Mapping[str, object]) -> None:
    summary_path = config.output_dir / "variants_summary.txt"
    summary = (
        summary_path.read_text(encoding="utf-8").strip()
        if summary_path.is_file()
        else "Variant summary was not available."
    )
    lines = [
        f"# {config.label}",
        "",
        "BactMut FASTQ completed successfully.",
        "",
        "## Key metrics",
        "",
        f"- Samples: {metrics.get('sample_count')}",
        f"- Initial variant positions: {metrics.get('initial_variant_positions')}",
        f"- Final SNP positions: {metrics.get('final_snp_positions')}",
        f"- Tree: {metrics.get('tree_status')}",
        "",
        "## Variant summary",
        "",
        "```text",
        summary,
        "```",
        "",
        "The SNP matrix, annotated variant table, per-sample calling files, and "
        "optional IQ-TREE files are available in the configured output directory.",
        "",
    ]
    path = config.output_paths["report_path"]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def _assert_required_outputs(config: PipelineConfig) -> None:
    missing = [
        str(config.output_paths[key])
        for key in _REQUIRED_OUTPUT_KEYS
        if not config.output_paths[key].is_file()
    ]
    if missing:
        raise RuntimeError("pipeline did not generate required output(s): " + ", ".join(missing))


def _resolve_path(value: Any, field: str, base_dir: Path) -> Path:
    text = _nonempty_string(value, field)
    path = Path(text).expanduser()
    return path.resolve() if path.is_absolute() else (base_dir / path).resolve()


def _optional_path(value: Any, field: str, base_dir: Path) -> Path | None:
    if value in (None, ""):
        return None
    return _resolve_path(value, field, base_dir)


def _nonempty_string(value: Any, field: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ConfigError(f"{field} must be a non-empty string")
    return value.strip()


def _optional_string(value: Any) -> str | None:
    if value in (None, ""):
        return None
    if not isinstance(value, str):
        raise ConfigError("optional text parameters must be strings")
    return value.strip() or None


def _choice(value: Any, field: str, choices: set[str]) -> str:
    text = _nonempty_string(value, field).lower()
    if text not in choices:
        raise ConfigError(f"{field} must be one of: {', '.join(sorted(choices))}")
    return text


def _integer(value: Any, field: str) -> int:
    if isinstance(value, bool):
        raise ConfigError(f"{field} must be an integer")
    if isinstance(value, int):
        return value
    if isinstance(value, str):
        try:
            return int(value.strip())
        except ValueError as error:
            raise ConfigError(f"{field} must be an integer") from error
    raise ConfigError(f"{field} must be an integer")


def _positive_integer(value: Any, field: str) -> int:
    integer = _integer(value, field)
    if integer < 1:
        raise ConfigError(f"{field} must be a positive integer")
    return integer


def _float(value: Any, field: str) -> float:
    if isinstance(value, bool):
        raise ConfigError(f"{field} must be numeric")
    try:
        number = float(value)
    except (TypeError, ValueError) as error:
        raise ConfigError(f"{field} must be numeric") from error
    if not math.isfinite(number):
        raise ConfigError(f"{field} must be finite")
    return number


def _fraction(value: Any, field: str) -> float:
    number = _float(value, field)
    if not 0 < number <= 1:
        raise ConfigError(f"{field} must be greater than 0 and at most 1")
    return number


def _nonnegative_float(value: Any, field: str) -> float:
    number = _float(value, field)
    if number < 0:
        raise ConfigError(f"{field} must be non-negative")
    return number


def _boolean(value: Any, field: str) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, str) and value.strip().lower() in {"true", "false"}:
        return value.strip().lower() == "true"
    raise ConfigError(f"{field} must be true or false")


def _optional_taxonid(value: Any) -> str | None:
    if value in (None, ""):
        return None
    return str(_positive_integer(value, "params.taxonid"))


if __name__ == "__main__":
    raise SystemExit(main())
