label: virmut_example

input_path: data/input/example_genomes.fasta
reference_path: data/input/example_reference.fasta
output_dir: data/output

matrix_path: data/output/matrix.tsv
variants_path: data/output/variants.tsv
summary_path: data/output/variants_summary.txt
tree_fasta_path: data/output/tree.fasta
treefile_path: data/output/tree.treefile
iqtree_report_path: data/output/tree.iqtree
iqtree_log_path: data/output/tree.log

params:
  mode: fasta
  reference_mode: local
  species: ""
  taxonid: ""
  threads: 1
