"""BioAgent pipeline implementation. Generated by consolidating the original modules."""
from __future__ import annotations

# --- original module: __init__.py ---
"""virmut package."""

# --- original module: align.py ---
"""Alignment stage."""


import subprocess
from pathlib import Path


def run_minimap2(
    query: Path,
    reference: Path,
    output_paf: Path,
    preset: str = "asm20",
) -> None:
    output_paf = Path(output_paf)
    output_paf.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        "minimap2",
        "-x",
        preset,
        "-c",
        "--cs",
        str(reference),
        str(query),
    ]
    with output_paf.open("w", encoding="utf-8") as out:
        subprocess.run(cmd, stdout=out, check=True)

# --- original module: cli.py ---
"""Command-line parsing for virmut."""


import argparse
import os
from collections.abc import Sequence


def positive_taxid(value: str) -> str:
    """Return a taxon id only when it is a positive integer string."""
    if not value.isdigit() or int(value) <= 0:
        raise argparse.ArgumentTypeError("taxonid must be a positive integer")
    return value


def positive_int(value: str) -> int:
    """Return a positive integer for CLI options."""
    if not value.isdigit() or int(value) <= 0:
        raise argparse.ArgumentTypeError("value must be a positive integer")
    return int(value)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="virmut")
    parser.add_argument(
        "--input",
        required=True,
        help="input FASTA file/directory in fasta mode, or FASTQ directory in fastq mode",
    )
    parser.add_argument("--output", required=True, help="output directory")
    parser.add_argument(
        "--mode",
        choices=("fasta", "fastq"),
        default="fasta",
        help="input mode: assembled FASTA genomes or raw FASTQ reads",
    )
    parser.add_argument(
        "--threads",
        type=positive_int,
        default=1,
        help="threads for FASTQ alignment and sorting steps",
    )
    parser.add_argument("--annotate", action="store_true", default=True)

    source_group = parser.add_mutually_exclusive_group(required=True)
    source_group.add_argument("--reference", help="local reference FASTA")
    source_group.add_argument("--species", help="species name resolved from local SEQ_DB")
    source_group.add_argument(
        "--taxonid",
        type=positive_taxid,
        help="positive integer taxon id resolved from local SEQ_DB",
    )
    return parser


def virmut_cli_main(argv: Sequence[str] | None = None) -> int:
    """Run the consolidated virmut CLI implementation."""
    parser = build_parser()
    args = parser.parse_args(argv)
    if args.reference:
        ensure_single_record(Path(args.reference))
    resolved = resolve_reference(
        reference=args.reference,
        species=args.species,
        taxonid=args.taxonid,
        db_fasta=os.environ.get("VIRUS_DB"),
        db_metadata=os.environ.get("VIRUS_METADATA"),
    )
    output_dir = Path(args.output) if args.output else Path("results")

    pafs = {}
    ivar_variants = None
    if args.mode == "fastq":
        snp_tsvs, ivar_variants = run_fastq_pipeline(
            reference=resolved.path,
            fastq_dir=Path(args.input),
            output_dir=output_dir,
            threads=args.threads,
        )
    else:
        input_fastas = collect_input_fastas(Path(args.input))
        for input_fasta in input_fastas.values():
            ensure_single_record(input_fasta)

        snp_tsvs = {}
        for sample, input_fasta in input_fastas.items():
            output_paf = output_dir / "align" / f"{sample}.paf"
            run_minimap2(
                query=input_fasta,
                reference=resolved.path,
                output_paf=output_paf,
            )
            output_tsv = output_dir / "snps" / f"{sample}.tsv"
            call_snps(
                paf=output_paf,
                reference=resolved.path,
                output_tsv=output_tsv,
            )
            pafs[sample] = output_paf
            snp_tsvs[sample] = output_tsv
    output_matrix = output_dir / "matrix.tsv"
    build_snp_matrix(
        snp_tsvs=snp_tsvs,
        output_tsv=output_matrix,
    )
    if args.annotate:
        build_variants_table(
            pafs=pafs,
            reference=resolved.path,
            output_tsv=output_dir / "variants.tsv",
            output_summary=output_dir / "variants_summary.txt",
            ivar_variants=ivar_variants,
        )
    output_tree = output_dir / "tree"
    run_iqtree(
        matrix_tsv=output_matrix,
        output_prefix=output_tree,
    )
    return 0



# --- original module: config_runner.py ---
"""BioAgent YAML configuration entry point for virmut."""


import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence

import yaml


class ConfigError(ValueError):
    """Raised when a BioAgent configuration is invalid."""


_OUTPUT_DEFAULTS = {
    "matrix_path": "matrix.tsv",
    "variants_path": "variants.tsv",
    "summary_path": "variants_summary.txt",
    "tree_fasta_path": "tree.fasta",
    "treefile_path": "tree.treefile",
    "iqtree_report_path": "tree.iqtree",
    "iqtree_log_path": "tree.log",
}
_CORE_OUTPUT_KEYS = ("matrix_path", "variants_path", "summary_path")


@dataclass(frozen=True)
class PipelineConfig:
    """Validated and path-normalized pipeline configuration."""

    label: str
    input_path: Path
    output_dir: Path
    mode: str
    reference_mode: str
    threads: int
    reference_path: Path | None
    species: str | None
    taxonid: str | None
    output_paths: Mapping[str, Path]

    def cli_argv(self) -> list[str]:
        argv = [
            "--input",
            str(self.input_path),
            "--output",
            str(self.output_dir),
            "--mode",
            self.mode,
            "--threads",
            str(self.threads),
        ]
        if self.reference_mode == "local":
            assert self.reference_path is not None
            argv.extend(["--reference", str(self.reference_path)])
        elif self.reference_mode == "species":
            assert self.species is not None
            argv.extend(["--species", self.species])
        else:
            assert self.taxonid is not None
            argv.extend(["--taxonid", self.taxonid])
        return argv


def load_config(config_path: str | Path) -> PipelineConfig:
    """Load, validate, and normalize one YAML configuration file."""
    path = Path(config_path).expanduser()
    if not path.is_file():
        raise ConfigError(f"configuration file not found: {path}")

    try:
        with path.open(encoding="utf-8") as stream:
            raw = yaml.safe_load(stream)
    except yaml.YAMLError as exc:
        raise ConfigError(f"invalid YAML in {path}: {exc}") from exc
    except OSError as exc:
        raise ConfigError(f"cannot read configuration file {path}: {exc}") from exc

    if not isinstance(raw, Mapping):
        raise ConfigError("configuration root must be a YAML mapping")
    return parse_config(raw, base_dir=path.resolve().parent)


def parse_config(raw: Mapping[str, Any], *, base_dir: Path) -> PipelineConfig:
    """Validate a configuration mapping and resolve its filesystem paths."""
    base_dir = Path(base_dir).resolve()
    label = _nonempty_string(raw.get("label"), "label")
    input_path = _resolve_path(raw.get("input_path"), "input_path", base_dir)
    output_dir = _resolve_path(raw.get("output_dir"), "output_dir", base_dir)

    params = raw.get("params")
    if not isinstance(params, Mapping):
        params = {}

    def _resolve_param(key):
        return raw.get(key, params.get(key))

    mode = _normalized_choice(_resolve_param("mode"), "mode", {"fasta", "fastq"})
    reference_mode = _normalized_choice(
        _resolve_param("reference_mode"),
        "reference_mode",
        {"local", "species", "taxonid"},
    )
    threads = _positive_integer(_resolve_param("threads"), "threads")

    reference_value = raw.get("reference_path")
    reference_path = None
    if reference_value not in (None, ""):
        reference_path = _resolve_path(reference_value, "reference_path", base_dir)

    species_value = _resolve_param("species")
    if species_value is not None and not isinstance(species_value, str):
        raise ConfigError("species must be a string")
    species = species_value.strip() if isinstance(species_value, str) else ""

    taxonid_value = _resolve_param("taxonid")
    if isinstance(taxonid_value, str) and taxonid_value.lower() in ("taxonid", "none", ""):
        taxonid_value = None
    taxonid = _optional_taxonid(taxonid_value) if taxonid_value is not None else None

    supplied = {
        "local": reference_path is not None,
        "species": bool(species),
        "taxonid": taxonid is not None,
    }
    if not supplied[reference_mode]:
        required = {
            "local": "reference_path",
            "species": "non-empty params.species",
            "taxonid": "positive integer params.taxonid",
        }[reference_mode]
        raise ConfigError(f"reference_mode '{reference_mode}' requires {required}")

    output_paths: dict[str, Path] = {}
    for key, filename in _OUTPUT_DEFAULTS.items():
        value = raw.get(key)
        output_paths[key] = (
            _resolve_path(value, key, base_dir)
            if value not in (None, "")
            else output_dir / filename
        )

    return PipelineConfig(
        label=label,
        input_path=input_path,
        output_dir=output_dir,
        mode=mode,
        reference_mode=reference_mode,
        threads=threads,
        reference_path=reference_path,
        species=species or None,
        taxonid=taxonid,
        output_paths=output_paths,
    )


def run_config(config: PipelineConfig) -> int:
    """Run the existing CLI and publish configured output paths."""
    if not config.input_path.exists():
        raise ConfigError(f"input_path does not exist: {config.input_path}")
    if config.reference_mode == "local" and not config.reference_path.is_file():
        raise ConfigError(f"reference_path is not a file: {config.reference_path}")
    try:
        config.output_dir.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        raise ConfigError(f"cannot create output_dir {config.output_dir}: {exc}") from exc

    tree_status: str | None = None
    try:
        result = virmut_cli_main(config.cli_argv())
    except InsufficientSamplesForTreeError as exc:
        tree_status = f"phylogenetic tree was not generated: {exc}"
        result = 0
    except ValueError as exc:
        if str(exc) != "no variant positions":
            raise
        tree_status = "phylogenetic tree was not generated: no variant positions"
        result = 0

    _publish_outputs(config)
    missing_core = [
        str(config.output_paths[key])
        for key in _CORE_OUTPUT_KEYS
        if not config.output_paths[key].is_file()
    ]
    if missing_core:
        raise RuntimeError("pipeline did not generate core output(s): " + ", ".join(missing_core))

    missing_tree = [
        str(config.output_paths[key])
        for key in _OUTPUT_DEFAULTS
        if key not in _CORE_OUTPUT_KEYS and not config.output_paths[key].is_file()
    ]
    if tree_status:
        print(f"virmut status: {tree_status}", file=sys.stderr)
    elif missing_tree:
        print(
            "virmut status: optional IQ-TREE output(s) not present: "
            + ", ".join(missing_tree),
            file=sys.stderr,
        )
    return int(result or 0)


def main(argv: Sequence[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    if len(args) != 1:
        print("Usage: python -m virmut.config_runner CONFIG.yaml", file=sys.stderr)
        return 2
    try:
        return run_config(load_config(args[0]))
    except (
        ConfigError,
        OSError,
        RuntimeError,
        ValueError,
        subprocess.CalledProcessError,
    ) as exc:
        print(f"virmut pipeline error: {exc}", file=sys.stderr)
        return 1


def _publish_outputs(config: PipelineConfig) -> None:
    for key, filename in _OUTPUT_DEFAULTS.items():
        source = config.output_dir / filename
        destination = config.output_paths[key]
        if not source.is_file() or source.resolve() == destination.resolve():
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)


def _resolve_path(value: Any, field: str, base_dir: Path) -> Path:
    text = _nonempty_string(value, field)
    path = Path(text).expanduser()
    return path.resolve() if path.is_absolute() else (base_dir / path).resolve()


def _nonempty_string(value: Any, field: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ConfigError(f"{field} must be a non-empty string")
    return value.strip()


def _normalized_choice(value: Any, field: str, choices: set[str]) -> str:
    text = _nonempty_string(value, field).lower()
    if text not in choices:
        raise ConfigError(f"{field} must be one of: {', '.join(sorted(choices))}")
    return text


def _positive_integer(value: Any, field: str) -> int:
    if isinstance(value, bool):
        raise ConfigError(f"{field} must be a positive integer")
    if isinstance(value, int):
        integer = value
    elif isinstance(value, str) and value.strip().isdigit():
        integer = int(value.strip())
    else:
        raise ConfigError(f"{field} must be a positive integer")
    if integer <= 0:
        raise ConfigError(f"{field} must be a positive integer")
    return integer


def _optional_taxonid(value: Any) -> str | None:
    if value is None:
        return None
    if value in (None, ""):
        return None
    return str(_positive_integer(value, "params.taxonid"))



# --- original module: ivar_variants.py ---
"""FASTQ read alignment and iVar variant calling."""


import csv
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path


_FASTQ_SUFFIXES = (".fastq.gz", ".fq.gz", ".fastq", ".fq")
_PAIR_RE = re.compile(r"^(?P<sample>.+?)(?:_R|_)(?P<read>[12])(?P<tail>(?:[_-].*)?)$")
_REQUIRED_IVAR_COLUMNS = (
    "REGION",
    "POS",
    "REF",
    "ALT",
    "ALT_DP",
    "REF_DP",
    "TOTAL_DP",
    "ALT_FREQ",
    "ALT_QUAL",
    "PVAL",
    "PASS",
)
_SNP_BASES = {"A", "C", "G", "T", "N"}


@dataclass(frozen=True)
class IvarVariant:
    region: str
    pos: int
    ref: str
    alt: str
    alt_depth: str
    ref_depth: str
    total_depth: str
    alt_freq: str
    alt_qual: str
    pval: str
    pass_filter: str


def run_fastq_pipeline(
    reference: Path,
    fastq_dir: Path,
    output_dir: Path,
    threads: int = 1,
) -> tuple[dict[str, Path], dict[str, dict[int, IvarVariant]]]:
    """Run minimap2, samtools, and iVar for every FASTQ sample."""
    if threads <= 0:
        raise ValueError("threads must be positive")

    reference = Path(reference)
    output_dir = Path(output_dir)
    read_sets = _detect_pairs(Path(fastq_dir))

    snp_tsvs: dict[str, Path] = {}
    sample_variants: dict[str, dict[int, IvarVariant]] = {}
    for sample, reads in read_sets.items():
        output_sam = output_dir / "align" / f"{sample}.sam"
        output_bam = output_dir / "align" / f"{sample}.bam"
        output_prefix = output_dir / "ivar" / sample
        ivar_tsv = output_prefix.parent / f"{output_prefix.name}.tsv"
        output_snp_tsv = output_dir / "snps" / f"{sample}.tsv"

        _run_minimap2_short_reads(
            reference=reference,
            reads=reads,
            output_sam=output_sam,
            threads=threads,
        )
        _run_samtools_sort(
            input_sam=output_sam,
            output_bam=output_bam,
            threads=threads,
        )
        _run_samtools_index(output_bam)
        _run_ivar_variants(
            reference=reference,
            input_bam=output_bam,
            output_prefix=output_prefix,
        )

        variants = _parse_ivar_records(ivar_tsv)
        _write_snp_tsv(variants, output_snp_tsv)
        snp_tsvs[sample] = output_snp_tsv
        sample_variants[sample] = variants

    return snp_tsvs, sample_variants


def parse_ivar_tsv(tsv_path: Path) -> dict[str, dict[int, IvarVariant]]:
    """Parse one iVar variants TSV into a sample-indexed variant mapping."""
    tsv_path = Path(tsv_path)
    return {tsv_path.stem: _parse_ivar_records(tsv_path)}


def _parse_ivar_records(tsv_path: Path) -> dict[int, IvarVariant]:
    """Parse one iVar variants TSV into position-indexed variant calls."""
    variants: dict[int, IvarVariant] = {}
    with Path(tsv_path).open(encoding="utf-8", newline="") as tsv_file:
        reader = csv.DictReader(tsv_file, delimiter="\t")
        fieldnames = set(reader.fieldnames or [])
        missing = [column for column in _REQUIRED_IVAR_COLUMNS if column not in fieldnames]
        if missing:
            raise ValueError("iVar TSV missing required columns: " + ", ".join(missing))

        for row in reader:
            if not row.get("POS"):
                continue
            variant = IvarVariant(
                region=_value(row, "REGION"),
                pos=int(_value(row, "POS")),
                ref=_value(row, "REF").upper(),
                alt=_value(row, "ALT").upper(),
                alt_depth=_value(row, "ALT_DP"),
                ref_depth=_value(row, "REF_DP"),
                total_depth=_value(row, "TOTAL_DP"),
                alt_freq=_value(row, "ALT_FREQ"),
                alt_qual=_value(row, "ALT_QUAL"),
                pval=_value(row, "PVAL"),
                pass_filter=_value(row, "PASS"),
            )
            existing = variants.get(variant.pos)
            if existing is None or _variant_rank(variant) > _variant_rank(existing):
                variants[variant.pos] = variant

    return variants


def _detect_pairs(fastq_dir: Path) -> dict[str, tuple[Path, ...]]:
    """Group complete _R1/_R2 pairs and leave other FASTQs as single-end."""
    fastq_dir = Path(fastq_dir)
    if not fastq_dir.is_dir():
        raise ValueError("FASTQ input must be a directory")

    fastqs = [
        path
        for path in sorted(fastq_dir.iterdir())
        if path.is_file() and _is_fastq(path)
    ]
    if not fastqs:
        raise ValueError("no FASTQ reads")

    pair_candidates: dict[tuple[str, str], dict[str, Path]] = {}
    for path in fastqs:
        stem = _strip_fastq_suffix(path.name)
        match = _PAIR_RE.match(stem)
        if match is None:
            continue
        key = (match.group("sample"), match.group("tail") or "")
        pair_candidates.setdefault(key, {})[match.group("read")] = path

    read_sets: dict[str, tuple[Path, ...]] = {}
    paired_paths: set[Path] = set()
    for (sample, _tail), mates in sorted(pair_candidates.items()):
        if "1" not in mates or "2" not in mates:
            continue
        _add_read_set(read_sets, sample, (mates["1"], mates["2"]))
        paired_paths.update(mates.values())

    for path in fastqs:
        if path in paired_paths:
            continue
        sample = _strip_fastq_suffix(path.name)
        _add_read_set(read_sets, sample, (path,))

    return read_sets


def _run_minimap2_short_reads(
    reference: Path,
    reads: tuple[Path, ...],
    output_sam: Path,
    threads: int,
) -> None:
    output_sam = Path(output_sam)
    output_sam.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        "minimap2",
        "-ax",
        "sr",
        "-t",
        str(threads),
        str(reference),
        *[str(read) for read in reads],
    ]
    with output_sam.open("w", encoding="utf-8") as sam_file:
        subprocess.run(cmd, stdout=sam_file, check=True)


def _run_samtools_sort(input_sam: Path, output_bam: Path, threads: int) -> None:
    output_bam = Path(output_bam)
    output_bam.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            "samtools",
            "sort",
            "-@",
            str(threads),
            str(input_sam),
            "-o",
            str(output_bam),
        ],
        check=True,
    )


def _run_samtools_index(output_bam: Path) -> None:
    subprocess.run(["samtools", "index", str(output_bam)], check=True)


def _run_ivar_variants(
    reference: Path,
    input_bam: Path,
    output_prefix: Path,
) -> None:
    output_prefix = Path(output_prefix)
    output_prefix.parent.mkdir(parents=True, exist_ok=True)
    mpileup_cmd = [
        "samtools",
        "mpileup",
        "-aa",
        "-A",
        "-d",
        "0",
        "-Q",
        "20",
        "-q",
        "30",
        "-f",
        str(reference),
        str(input_bam),
    ]
    ivar_cmd = [
        "ivar",
        "variants",
        "-p",
        str(output_prefix),
        "-q",
        "20",
        "-t",
        "0.03",
        "-m",
        "10",
        "-r",
        str(reference),
    ]

    mpileup = subprocess.Popen(mpileup_cmd, stdout=subprocess.PIPE)
    try:
        if mpileup.stdout is None:
            raise RuntimeError("samtools mpileup stdout pipe was not created")
        subprocess.run(ivar_cmd, stdin=mpileup.stdout, check=True)
        mpileup.stdout.close()
        return_code = mpileup.wait()
        if return_code != 0:
            raise subprocess.CalledProcessError(return_code, mpileup_cmd)
    except Exception:
        if mpileup.stdout is not None and not mpileup.stdout.closed:
            mpileup.stdout.close()
        if mpileup.poll() is None:
            mpileup.kill()
        mpileup.wait()
        raise


def _write_snp_tsv(
    variants: dict[int, IvarVariant],
    output_tsv: Path,
) -> None:
    output_tsv = Path(output_tsv)
    output_tsv.parent.mkdir(parents=True, exist_ok=True)
    with output_tsv.open("w", encoding="utf-8") as out:
        out.write("pos\tref\talt\n")
        for pos, variant in sorted(variants.items()):
            if _is_snp(variant):
                out.write(f"{pos}\t{variant.ref}\t{variant.alt}\n")


def _is_fastq(path: Path) -> bool:
    name = path.name.lower()
    return any(name.endswith(suffix) for suffix in _FASTQ_SUFFIXES)


def _strip_fastq_suffix(filename: str) -> str:
    lower = filename.lower()
    for suffix in _FASTQ_SUFFIXES:
        if lower.endswith(suffix):
            return filename[: -len(suffix)]
    return Path(filename).stem


def _add_read_set(
    read_sets: dict[str, tuple[Path, ...]],
    sample: str,
    reads: tuple[Path, ...],
) -> None:
    if sample in read_sets:
        raise ValueError(f"duplicate FASTQ sample name: {sample}")
    read_sets[sample] = reads


def _value(row: dict[str, str | None], column: str) -> str:
    return (row.get(column) or "NA").strip() or "NA"


def _variant_rank(variant: IvarVariant) -> tuple[float, int]:
    return (_as_float(variant.alt_freq), _as_int(variant.alt_depth))


def _is_snp(variant: IvarVariant) -> bool:
    return (
        len(variant.ref) == 1
        and len(variant.alt) == 1
        and variant.ref in _SNP_BASES
        and variant.alt in _SNP_BASES
        and variant.ref != variant.alt
    )


def _as_float(value: str) -> float:
    try:
        return float(value)
    except ValueError:
        return -1.0


def _as_int(value: str) -> int:
    try:
        return int(value)
    except ValueError:
        return -1

# --- original module: matrix.py ---
"""Mutation matrix stage."""


from pathlib import Path


def build_snp_matrix(
    snp_tsvs: dict[str, Path],
    output_tsv: Path,
) -> None:
    if not snp_tsvs:
        raise ValueError("no snp tables")

    output_tsv = Path(output_tsv)
    output_tsv.parent.mkdir(parents=True, exist_ok=True)

    sample_calls: dict[str, dict[int, tuple[str, str]]] = {}
    refs: dict[int, str] = {}
    positions: set[int] = set()
    for sample, snp_tsv in snp_tsvs.items():
        calls: dict[int, tuple[str, str]] = {}
        with Path(snp_tsv).open(encoding="utf-8") as snp_file:
            next(snp_file, None)
            for line in snp_file:
                if not line.strip():
                    continue
                pos_text, ref, alt = line.rstrip("\n").split("\t")
                pos = int(pos_text)
                calls[pos] = (ref, alt)
                refs.setdefault(pos, ref)
                positions.add(pos)
        sample_calls[sample] = calls

    samples = list(snp_tsvs)
    with output_tsv.open("w", encoding="utf-8") as out:
        out.write("pos\t" + "\t".join(samples) + "\n")
        for pos in sorted(positions):
            values = []
            for sample in samples:
                if pos in sample_calls[sample]:
                    values.append(sample_calls[sample][pos][1])
                else:
                    values.append(refs[pos])
            out.write(f"{pos}\t" + "\t".join(values) + "\n")

# --- original module: reference.py ---
"""Reference source resolution for the local virus database."""


import csv
import os
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, NamedTuple


VIRUS_DB_ENV = "VIRUS_DB"
VIRUS_METADATA_ENV = "VIRUS_METADATA"
DB_REQUIRED_MESSAGE = "VIRUS_DB and VIRUS_METADATA are required"
_REQUIRED_METADATA_FIELDS = (
    "Accession",
    "Sequence_type",
    "Completeness",
    "Curated_species",
    "Lineage",
    "Ranks",
    "Family",
    "Species_taxid",
    "Accession_tax_name",
    "Accession_taxid",
    "Distance_to_species",
    "Group_name",
)


class ReferenceError(ValueError):
    """Base error for reference resolution."""


class DBRequiredError(ReferenceError):
    """Raised when the local virus database is required but unavailable."""


SEQDBRequiredError = DBRequiredError


class MultipleReferenceCandidatesError(ReferenceError):
    """Raised when a lookup returns more than one possible reference."""


@dataclass(frozen=True)
class ReferenceCandidate:
    path: str = ""
    species: str | None = None
    taxonid: str | None = None
    accession: str | None = None

    def display(self) -> str:
        parts = []
        if self.accession:
            parts.append(f"accession={self.accession}")
        if self.species:
            parts.append(f"species={self.species}")
        if self.taxonid:
            parts.append(f"taxonid={self.taxonid}")
        if self.path:
            parts.append(self.path)
        return " | ".join(parts)


class ResolvedReference(NamedTuple):
    path: Path


def resolve_reference(
    *,
    reference: str | None = None,
    species: str | None = None,
    taxonid: str | None = None,
    seq_db: str | None = None,
    candidates: Iterable[ReferenceCandidate] | None = None,
    db_fasta: str | Path | None = None,
    db_metadata: str | Path | None = None,
) -> ResolvedReference:
    supplied = [value is not None for value in (reference, species, taxonid)]
    if sum(supplied) != 1:
        raise ReferenceError("provide exactly one of --reference, --species, or --taxonid")

    if reference is not None:
        return ResolvedReference(path=Path(reference))

    if candidates is not None:
        return _resolve_candidates(candidates)

    db_fasta_path, db_metadata_path = _resolve_db_paths(
        db_fasta=db_fasta,
        db_metadata=db_metadata,
        seq_db=seq_db,
    )

    if species is not None:
        query = species.strip().casefold()
        matches = _metadata_candidates(
            db_metadata_path,
            db_fasta_path,
            lambda row: _clean(row.get("Curated_species")).casefold() == query,
            taxonid_field="Species_taxid",
        )
        return _resolve_db_candidates(matches, db_fasta_path)

    assert taxonid is not None
    accession_matches = _metadata_candidates(
        db_metadata_path,
        db_fasta_path,
        lambda row: _clean(row.get("Accession_taxid")) == taxonid,
        taxonid_field="Accession_taxid",
    )
    if accession_matches:
        return _resolve_db_candidates(accession_matches, db_fasta_path)

    species_matches = _metadata_candidates(
        db_metadata_path,
        db_fasta_path,
        lambda row: _clean(row.get("Species_taxid")) == taxonid,
        taxonid_field="Species_taxid",
    )
    return _resolve_db_candidates(species_matches, db_fasta_path)


def _resolve_db_paths(
    *,
    db_fasta: str | Path | None,
    db_metadata: str | Path | None,
    seq_db: str | None,
) -> tuple[Path, Path]:
    if seq_db is not None:
        seq_db_path = Path(seq_db)
        db_fasta = db_fasta or seq_db_path / "reference.fasta"
        db_metadata = db_metadata or seq_db_path / "meta.tsv"

    configured_fasta = db_fasta or os.environ.get(VIRUS_DB_ENV)
    configured_metadata = db_metadata or os.environ.get(VIRUS_METADATA_ENV)
    missing = []
    if not configured_fasta:
        missing.append(VIRUS_DB_ENV)
    if not configured_metadata:
        missing.append(VIRUS_METADATA_ENV)
    if missing:
        raise DBRequiredError(f"{DB_REQUIRED_MESSAGE}: {', '.join(missing)}")

    db_fasta_path = Path(configured_fasta)
    db_metadata_path = Path(configured_metadata)
    if not db_fasta_path.is_file():
        raise FileNotFoundError(f"virus reference FASTA not found: {db_fasta_path}")
    if not db_metadata_path.is_file():
        raise FileNotFoundError(f"virus metadata not found: {db_metadata_path}")
    return db_fasta_path, db_metadata_path


def _metadata_candidates(
    metadata_path: Path,
    db_fasta_path: Path,
    predicate,
    *,
    taxonid_field: str,
) -> list[ReferenceCandidate]:
    matches: list[ReferenceCandidate] = []
    with metadata_path.open(encoding="utf-8", newline="") as metadata:
        reader = csv.DictReader(metadata, delimiter="\t")
        fieldnames = set(reader.fieldnames or [])
        missing = [field for field in _REQUIRED_METADATA_FIELDS if field not in fieldnames]
        if missing:
            raise ReferenceError(
                "virus metadata missing required columns: " + ", ".join(missing)
            )
        for row in reader:
            if predicate(row):
                accession = _clean(row.get("Accession"))
                if not accession:
                    continue
                matches.append(
                    ReferenceCandidate(
                        path=str(db_fasta_path),
                        species=_clean(row.get("Curated_species")) or None,
                        taxonid=_clean(row.get(taxonid_field)) or None,
                        accession=accession,
                    )
                )
    return matches


def _resolve_candidates(candidates: Iterable[ReferenceCandidate]) -> ResolvedReference:
    matches = list(candidates)
    if len(matches) > 1:
        raise _multiple_candidates_error(matches)

    if len(matches) == 1:
        return ResolvedReference(path=Path(matches[0].path))

    raise ReferenceError("no matching reference")


def _resolve_db_candidates(
    candidates: Iterable[ReferenceCandidate],
    db_fasta_path: Path,
) -> ResolvedReference:
    matches = list(candidates)
    if len(matches) > 1:
        raise _multiple_candidates_error(matches)

    if len(matches) == 1:
        accession = matches[0].accession
        if accession is None:
            raise ReferenceError("matching reference is missing an accession")
        return ResolvedReference(path=_extract_accession_fasta(db_fasta_path, accession))

    raise ReferenceError("no matching reference")


def _multiple_candidates_error(
    candidates: Iterable[ReferenceCandidate],
) -> MultipleReferenceCandidatesError:
    candidate_lines = "\n".join(f"- {candidate.display()}" for candidate in candidates)
    return MultipleReferenceCandidatesError(
        "multiple reference candidates found; refusing to choose silently:\n"
        f"{candidate_lines}\n"
        "Hint: use a more specific taxonid or --reference to narrow the search."
    )


def _extract_accession_fasta(db_fasta_path: Path, accession: str) -> Path:
    fd, tmp_name = tempfile.mkstemp(suffix=".fa", prefix="virmut_ref_")
    tmp_path = Path(tmp_name)
    found = False
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as output:
            with db_fasta_path.open(encoding="utf-8") as source:
                copying = False
                for line in source:
                    if line.startswith(">"):
                        if copying:
                            break
                        copying = _header_matches_accession(line, accession)
                        if copying:
                            found = True
                            output.write(line)
                    elif copying:
                        output.write(line)
        if not found:
            raise ReferenceError(
                f"accession '{accession}' was not found in {db_fasta_path}"
            )
    except Exception:
        tmp_path.unlink(missing_ok=True)
        raise
    return tmp_path


def _header_matches_accession(header: str, accession: str) -> bool:
    header = header.strip()
    if not header.startswith(">"):
        return False
    return header[1:].split(maxsplit=1)[0] == accession


def _clean(value: str | None) -> str:
    return (value or "").strip()

# --- original module: snp.py ---
"""Consensus SNP stage."""


from collections import Counter
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from Bio import SeqIO
from Bio.Seq import Seq


@dataclass(frozen=True)
class VariantEvent:
    pos: int
    ref: str
    alt: str
    variant_type: str


def call_snps(
    paf: Path,
    reference: Path,
    output_tsv: Path,
) -> None:
    reference_record = next(SeqIO.parse(Path(reference), "fasta"))
    reference_seq = str(reference_record.seq).upper()
    output_tsv = Path(output_tsv)
    output_tsv.parent.mkdir(parents=True, exist_ok=True)

    saw_alignment = False
    rows: list[tuple[int, str, str]] = []
    with Path(paf).open(encoding="utf-8") as paf_file:
        for line in paf_file:
            if not line.strip():
                continue
            saw_alignment = True
            fields = line.rstrip("\n").split("\t")
            ref_pos = int(fields[7])
            cs_tag = next((field[5:] for field in fields[12:] if field.startswith("cs:Z:")), None)
            if cs_tag is None:
                continue
            rows.extend(_snps_from_cs(cs_tag, ref_pos, reference_seq))

    if not saw_alignment:
        raise ValueError("no alignments in PAF")

    with output_tsv.open("w", encoding="utf-8") as out:
        out.write("pos\tref\talt\n")
        for pos, ref, alt in rows:
            out.write(f"{pos}\t{ref}\t{alt}\n")


def _snps_from_cs(
    cs: str,
    ref_start: int,
    reference_seq: str,
) -> list[tuple[int, str, str]]:
    rows: list[tuple[int, str, str]] = []
    i = 0
    ref_pos = ref_start
    while i < len(cs):
        op = cs[i]
        if op == ":":
            i += 1
            start = i
            while i < len(cs) and cs[i].isdigit():
                i += 1
            ref_pos += int(cs[start:i])
        elif op == "*":
            ref_base = cs[i + 1].upper()
            alt_base = cs[i + 2].upper()
            rows.append((ref_pos + 1, reference_seq[ref_pos].upper(), alt_base))
            ref_pos += 1
            i += 3
        else:
            i += 1
    return rows


def build_variants_table(
    pafs: dict[str, Path] | None,
    reference: Path,
    output_tsv: Path,
    output_summary: Path,
    ivar_variants: Mapping[str, Mapping[int, Any]] | None = None,
) -> None:
    reference_record = next(SeqIO.parse(Path(reference), "fasta"))
    reference_seq = str(reference_record.seq).upper()
    if ivar_variants is not None:
        sample_events = {
            sample: [
                _event_from_ivar_variant(pos, variant)
                for pos, variant in variants.items()
            ]
            for sample, variants in ivar_variants.items()
        }
        samples = list(ivar_variants)
    else:
        pafs = pafs or {}
        sample_events = {
            sample: _events_from_paf(paf, reference_seq)
            for sample, paf in pafs.items()
        }
        samples = list(pafs)

    first_events: dict[int, VariantEvent] = {}
    calls: dict[str, dict[int, VariantEvent]] = {}
    for sample, events in sample_events.items():
        calls[sample] = {}
        for event in events:
            calls[sample].setdefault(event.pos, event)
            first_events.setdefault(event.pos, event)

    output_tsv = Path(output_tsv)
    output_tsv.parent.mkdir(parents=True, exist_ok=True)
    fastq_columns = _ivar_sample_columns(samples) if ivar_variants is not None else []
    effects: Counter[str] = Counter()
    with output_tsv.open("w", encoding="utf-8") as out:
        columns = [
            "REGION",
            "POS",
            "REF",
            *samples,
            "VARIANT_TYPE",
            "REF_CODON",
            "REF_AA",
            "ALT_CODON",
            "ALT_AA",
            "EFFECT",
            *fastq_columns,
        ]
        out.write("\t".join(columns) + "\n")
        for pos in sorted(first_events):
            event = first_events[pos]
            ref_codon, ref_aa, alt_codon, alt_aa, effect = _annotate_event(
                event,
                reference_seq,
            )
            effects[effect] += 1
            sample_bases = [
                calls[sample].get(pos, event).alt
                if pos in calls[sample]
                else event.ref
                for sample in samples
            ]
            row = [
                reference_record.id,
                str(pos),
                event.ref,
                *sample_bases,
                event.variant_type,
                ref_codon,
                ref_aa,
                alt_codon,
                alt_aa,
                effect,
                *_ivar_sample_values(samples, ivar_variants, pos),
            ]
            out.write("\t".join(row) + "\n")

    output_summary = Path(output_summary)
    output_summary.parent.mkdir(parents=True, exist_ok=True)
    with output_summary.open("w", encoding="utf-8") as out:
        out.write(f"unique_variant_positions\t{len(first_events)}\n")
        for effect in sorted(effects):
            out.write(f"{effect}\t{effects[effect]}\n")


def _events_from_paf(paf: Path, reference_seq: str) -> list[VariantEvent]:
    events: list[VariantEvent] = []
    with Path(paf).open(encoding="utf-8") as paf_file:
        for line in paf_file:
            fields = line.rstrip("\n").split("\t")
            if len(fields) < 13:
                continue
            cs_tag = next(
                (field[5:] for field in fields[12:] if field.startswith("cs:Z:")),
                None,
            )
            if cs_tag is not None:
                events.extend(_events_from_cs(cs_tag, int(fields[7]), reference_seq))
    return events


def _event_from_ivar_variant(pos: int, variant: Any) -> VariantEvent:
    event_pos = int(_variant_value(variant, "pos", default=str(pos)))
    ref = _variant_value(variant, "ref").upper()
    alt = _variant_value(variant, "alt").upper()

    if alt.startswith("+"):
        return VariantEvent(event_pos, "-", alt[1:] or "N", "INSERTION")
    if alt.startswith("-"):
        return VariantEvent(event_pos, alt[1:] or ref, "-", "DELETION")
    if alt == "-":
        return VariantEvent(event_pos, ref, "-", "DELETION")
    if ref == "-":
        return VariantEvent(event_pos, "-", alt, "INSERTION")
    if len(ref) == 1 and len(alt) == 1:
        return VariantEvent(event_pos, ref, alt, "SNP")
    if len(ref) < len(alt):
        return VariantEvent(event_pos, "-", alt[len(ref) :] or alt, "INSERTION")
    if len(ref) > len(alt):
        return VariantEvent(event_pos, ref[len(alt) :] or ref, "-", "DELETION")
    return VariantEvent(event_pos, ref, alt, "MNP")


def _ivar_sample_columns(samples: list[str]) -> list[str]:
    columns: list[str] = []
    for sample in samples:
        columns.extend(
            [
                f"{sample}_ALT_FREQ",
                f"{sample}_DEPTH",
                f"{sample}_PVAL",
                f"{sample}_PASS",
            ]
        )
    return columns


def _ivar_sample_values(
    samples: list[str],
    ivar_variants: Mapping[str, Mapping[int, Any]] | None,
    pos: int,
) -> list[str]:
    if ivar_variants is None:
        return []

    values: list[str] = []
    for sample in samples:
        variant = ivar_variants[sample].get(pos)
        if variant is None:
            values.extend(["NA", "NA", "NA", "NA"])
        else:
            values.extend(
                [
                    _variant_value(variant, "alt_freq"),
                    _variant_value(variant, "total_depth"),
                    _variant_value(variant, "pval"),
                    _variant_value(variant, "pass_filter"),
                ]
            )
    return values


def _variant_value(variant: Any, name: str, default: str = "NA") -> str:
    value: Any
    if isinstance(variant, Mapping):
        value = variant.get(name, variant.get(name.upper(), default))
    else:
        value = getattr(variant, name, default)
    if value is None:
        return default
    text = str(value).strip()
    return text if text else default


def _events_from_cs(
    cs: str,
    ref_start: int,
    reference_seq: str,
) -> list[VariantEvent]:
    events: list[VariantEvent] = []
    i = 0
    ref_pos = ref_start
    while i < len(cs):
        op = cs[i]
        if op == ":":
            i += 1
            start = i
            while i < len(cs) and cs[i].isdigit():
                i += 1
            ref_pos += int(cs[start:i])
        elif op == "*":
            events.append(
                VariantEvent(ref_pos + 1, reference_seq[ref_pos], cs[i + 2].upper(), "SNP")
            )
            ref_pos += 1
            i += 3
        elif op in {"+", "-"}:
            i += 1
            start = i
            while i < len(cs) and cs[i].isalpha():
                i += 1
            sequence = cs[start:i].upper()
            if op == "+":
                events.append(VariantEvent(max(ref_pos, 1), "-", sequence, "INSERTION"))
            else:
                deleted = reference_seq[ref_pos : ref_pos + len(sequence)]
                events.append(VariantEvent(ref_pos + 1, deleted, "-", "DELETION"))
                ref_pos += len(sequence)
        elif op == "=":
            i += 1
            start = i
            while i < len(cs) and cs[i].isalpha():
                i += 1
            ref_pos += i - start
        else:
            i += 1
    return events


def _annotate_event(
    event: VariantEvent,
    reference_seq: str,
) -> tuple[str, str, str, str, str]:
    # Assembled single-record FASTA consensus mode: annotations are derived
    # only from observed sequence events and the reference sequence.
    if event.variant_type == "INSERTION":
        effect = "inframe_insertion" if len(event.alt) % 3 == 0 else "frameshift"
        return "NA", "NA", "NA", "NA", effect
    if event.variant_type == "DELETION":
        effect = "inframe_deletion" if len(event.ref) % 3 == 0 else "frameshift"
        return "NA", "NA", "NA", "NA", effect
    if event.variant_type != "SNP":
        return "NA", "NA", "NA", "NA", "frameshift"

    codon_start = ((event.pos - 1) // 3) * 3
    ref_codon = reference_seq[codon_start : codon_start + 3]
    if len(ref_codon) != 3:
        return "NA", "NA", "NA", "NA", "NA"
    offset = (event.pos - 1) % 3
    alt_codon = ref_codon[:offset] + event.alt + ref_codon[offset + 1 :]
    ref_aa = str(Seq(ref_codon).translate(table=1))
    alt_aa = str(Seq(alt_codon).translate(table=1))
    if ref_aa == alt_aa:
        effect = "synonymous"
    elif ref_aa != "*" and alt_aa == "*":
        effect = "stop_gained"
    elif ref_aa == "*" and alt_aa != "*":
        effect = "stop_lost"
    else:
        effect = "nonsynonymous"
    return ref_codon, ref_aa, alt_codon, alt_aa, effect

# --- original module: tree.py ---
"""Tree-building stage."""


import subprocess
from pathlib import Path


class InsufficientSamplesForTreeError(ValueError):
    """Raised when a SNP matrix has too few samples for tree inference."""


def run_iqtree(
    matrix_tsv: Path,
    output_prefix: Path,
    model: str = "GTR+G",
) -> None:
    with Path(matrix_tsv).open(encoding="utf-8") as matrix_file:
        header = next(matrix_file).rstrip("\n").split("\t")
        samples = header[1:]
        rows = [
            (int(fields[0]), fields[1:])
            for line in matrix_file
            if line.strip()
            for fields in [line.rstrip("\n").split("\t")]
        ]

    if not rows:
        raise ValueError("no variant positions")
    if len(samples) < 3:
        raise InsufficientSamplesForTreeError(
            f"at least three samples are required for IQ-TREE; found {len(samples)}"
        )

    output_prefix = Path(output_prefix)
    output_prefix.parent.mkdir(parents=True, exist_ok=True)
    alignment_fasta = output_prefix.with_suffix(".fasta")
    rows.sort(key=lambda row: row[0])
    with alignment_fasta.open("w", encoding="utf-8") as out:
        for index, sample in enumerate(samples):
            sequence = "".join(values[index] for _, values in rows)
            out.write(f">{sample}\n{sequence}\n")

    subprocess.run(
        [
            "iqtree",
            "-s",
            str(alignment_fasta),
            "-st",
            "DNA",
            "-m",
            model,
            "-pre",
            str(output_prefix),
            "-redo",
        ],
        check=True,
    )

# --- original module: utils.py ---
"""Shared utilities."""


import sys
from pathlib import Path

from Bio import SeqIO


def collect_input_fastas(input_path: Path) -> dict[str, Path]:
    input_path = Path(input_path)
    if input_path.is_file():
        fastas = [input_path]
    else:
        fastas = [
            path
            for path in sorted(input_path.iterdir())
            if path.is_file() and path.suffix.lower() in {".fa", ".fasta", ".fna"}
        ]

    if not fastas:
        raise ValueError("no input genomes")

    return {path.stem: path for path in fastas}


def ensure_single_record(path: Path) -> None:
    n = sum(1 for _ in SeqIO.parse(Path(path), "fasta"))
    if n != 1:
        print("multi-record FASTA not supported in v1", file=sys.stderr)
        raise SystemExit(1)


if __name__ == "__main__":
    raise SystemExit(main())
