"""BioAgent pipeline implementation. Generated by consolidating the original modules."""
from __future__ import annotations

# --- original module: fasta.py ---
"""Small streaming FASTA helpers with no third-party dependencies."""

from pathlib import Path
from typing import Dict, Iterable, Iterator, List, Sequence, Tuple


IUPAC = frozenset("ACGTRYSWKMBDHVN")
COMPLEMENT = str.maketrans("ACGTRYSWKMBDHVN", "TGCAYRSWMKVHDBN")


def read_fasta(path: Path) -> Iterator[Tuple[str, str]]:
    name = None
    chunks: List[str] = []
    with path.open("r", encoding="ascii") as handle:
        for line_number, raw_line in enumerate(handle, 1):
            line = raw_line.strip()
            if not line:
                continue
            if line.startswith(">"):
                if name is not None:
                    yield name, "".join(chunks)
                name = line[1:].split()[0]
                if not name:
                    raise ValueError(f"Empty FASTA record name in {path}:{line_number}")
                chunks = []
            else:
                if name is None:
                    raise ValueError(f"Sequence before FASTA header in {path}:{line_number}")
                sequence = line.upper()
                invalid = set(sequence) - IUPAC
                if invalid:
                    raise ValueError(
                        f"Invalid FASTA symbols {sorted(invalid)} in {path}:{line_number}"
                    )
                chunks.append(sequence)
    if name is not None:
        yield name, "".join(chunks)
    elif not chunks:
        raise ValueError(f"No FASTA records found in {path}")


def load_fasta(path: Path) -> List[Tuple[str, str]]:
    records = list(read_fasta(path))
    if not records:
        raise ValueError(f"No FASTA records found in {path}")
    return records


def write_fasta(records: Iterable[Tuple[str, str]], path: Path) -> None:
    with path.open("w", encoding="ascii", newline="\n") as handle:
        for name, sequence in records:
            handle.write(f">{name}\n{sequence}\n")


def reverse_complement(sequence: str) -> str:
    return sequence.translate(COMPLEMENT)[::-1]


# --- original module: models.py ---
"""Data models used across the pipeline."""

from bisect import bisect_right
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple


@dataclass(frozen=True)
class ReferenceGenome:
    path: Path
    records: Dict[str, str]
    offsets: Dict[str, int]
    length: int

    def base(self, global_position: int) -> str:
        for name, offset in self.offsets.items():
            sequence = self.records[name]
            if offset <= global_position < offset + len(sequence):
                return sequence[global_position - offset]
        raise IndexError(global_position)


@dataclass
class SampleCalls:
    name: str
    path: Path
    paf_path: Optional[Path] = None
    variants: Dict[int, str] = field(default_factory=dict)
    ambiguous: Dict[int, str] = field(default_factory=dict)
    intervals: List[Tuple[int, int]] = field(default_factory=list)
    _starts: List[int] = field(default_factory=list, init=False, repr=False)

    def finalize_intervals(self) -> None:
        if not self.intervals:
            self._starts = []
            return
        merged: List[Tuple[int, int]] = []
        for start, end in sorted(self.intervals):
            if start >= end:
                continue
            if merged and start <= merged[-1][1]:
                merged[-1] = (merged[-1][0], max(end, merged[-1][1]))
            else:
                merged.append((start, end))
        self.intervals = merged
        self._starts = [start for start, _ in merged]

    def is_covered(self, position: int) -> bool:
        index = bisect_right(self._starts, position) - 1
        return index >= 0 and position < self.intervals[index][1]

    def base_at(self, position: int, reference_base: str) -> str:
        if position in self.variants:
            return self.variants[position]
        if position in self.ambiguous:
            return self.ambiguous[position]
        return reference_base if self.is_covered(position) else "N"


@dataclass(frozen=True)
class FilterResult:
    initial_positions: Tuple[int, ...]
    coverage_positions: Tuple[int, ...]
    final_positions: Tuple[int, ...]
    coverage_removed: frozenset
    recombination_removed: frozenset
    recombination_regions: Tuple[Tuple[int, int], ...]
    window_mean: float
    window_sd: float

# --- original module: ref_manager.py ---
#!/usr/bin/env python3
"""
Reference Genome Manager for bactmut pipeline.
Provides fast, memory-efficient access to GTDB reference genomes.
"""

import csv
import hashlib
import json
import os
import re
import tempfile
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

CACHE_DIR = Path.home() / ".bactmut"
CACHE_DIR.mkdir(parents=True, exist_ok=True)
CACHE_VERSION = 3
CONTIG_GAP_SIZE = 20

Record = Tuple[str, int]
SpeciesCache = Dict[str, Dict[str, List[Record]]]
RepresentativeIndex = Dict[str, Set[str]]
_REQUIRED_METADATA_FIELDS = (
    "accession",
    "ncbi_genbank_assembly_accession",
    "gtdb_taxonomy",
    "gtdb_representative",
)
_REQUIRED_TAXID_METADATA_FIELDS = ("ncbi_taxid", "ncbi_species_taxid")
_ASSEMBLY_ACCESSION_RE = re.compile(r"^(?:(?:RS|GB)_)?(GC[AF]_\d+)(?:\.\d+)?$")


class ReferenceManager:
    """Manage GTDB reference genomes with on-the-fly extraction."""

    def __init__(
        self, db_path: Optional[str] = None, metadata_path: Optional[str] = None
    ):
        if db_path is None:
            db_path = os.environ.get("GTDB_DB_PATH")
            if not db_path:
                raise ValueError(
                    "请设置环境变量 GTDB_DB_PATH\n"
                    "  export GTDB_DB_PATH=/path/to/representative.fa"
                )
        self.db_path = Path(db_path)
        if not self.db_path.exists():
            raise FileNotFoundError(f"数据库不存在: {self.db_path}")

        configured_metadata = metadata_path or os.environ.get("GTDB_METADATA_PATH")
        self.metadata_path = Path(configured_metadata) if configured_metadata else None
        self._species_cache: SpeciesCache = {}
        self._representative_index: Optional[RepresentativeIndex] = None
        self._taxid_index: Optional[RepresentativeIndex] = None
        self._species_taxid_index: Optional[RepresentativeIndex] = None
        self._cache_loaded = False

        # 缓存文件路径（基于数据库路径的哈希值，避免不同数据库混用）
        db_hash = hashlib.md5(str(self.db_path).encode()).hexdigest()[:8]
        self.cache_file = CACHE_DIR / f"gtdb_index_{db_hash}.json"

    @staticmethod
    def _file_identity(path: Path) -> Dict[str, int]:
        stat = path.stat()
        return {"size": stat.st_size, "mtime_ns": stat.st_mtime_ns}

    @staticmethod
    def _normalize_assembly_id(value: object) -> Optional[str]:
        """Normalize a GTDB/NCBI assembly accession to its GCF/GCA identifier."""
        if not isinstance(value, str):
            return None
        match = _ASSEMBLY_ACCESSION_RE.fullmatch(value.strip())
        return match.group(1) if match else None

    @staticmethod
    def _gtdb_species(taxonomy: object) -> Optional[str]:
        """Extract the exact GTDB species name from a taxonomy string."""
        if not isinstance(taxonomy, str):
            return None
        for field in taxonomy.split(";"):
            field = field.strip()
            if field.startswith("s__"):
                species = field[3:].strip().lower()
                return species or None
        return None

    def _load_cache(self) -> bool:
        """Load the FASTA index and any valid representative index from disk."""
        if not self.cache_file.exists():
            return False
        try:
            with open(self.cache_file, "r") as f:
                data = json.load(f)
        except (json.JSONDecodeError, OSError, TypeError):
            self.cache_file.unlink(missing_ok=True)
            return False

        if not self._is_valid_fasta_cache(data):
            return False

        self._species_cache = {
            species: {
                assembly_id: [tuple(record) for record in records]
                for assembly_id, records in assemblies.items()
            }
            for species, assemblies in data["index"].items()
        }
        self._cache_loaded = True

        if self.metadata_path and self._is_valid_metadata_cache(data):
            self._representative_index = {
                species: set(assemblies)
                for species, assemblies in data["representatives"].items()
            }
            self._taxid_index = {
                taxid: set(assemblies)
                for taxid, assemblies in data["taxid_index"].items()
            }
            self._species_taxid_index = {
                taxid: set(assemblies)
                for taxid, assemblies in data["species_taxid_index"].items()
            }
        return True

    def _is_valid_fasta_cache(self, data: object) -> bool:
        """Return whether a disk cache has a valid FASTA index for this database."""
        if not isinstance(data, dict) or data.get("cache_version") != CACHE_VERSION:
            return False
        if data.get("db_path") != str(self.db_path):
            return False
        identity = self._file_identity(self.db_path)
        if data.get("db_size") != identity["size"]:
            return False
        if data.get("db_mtime_ns") != identity["mtime_ns"]:
            return False
        return self._is_valid_cache_index(data.get("index"))

    def _is_valid_metadata_cache(self, data: object) -> bool:
        """Return whether cached representatives match the configured metadata file."""
        if not isinstance(data, dict) or self.metadata_path is None:
            return False
        if not self.metadata_path.exists():
            return False
        identity = self._file_identity(self.metadata_path)
        if data.get("metadata_path") != str(self.metadata_path):
            return False
        if data.get("metadata_size") != identity["size"]:
            return False
        if data.get("metadata_mtime_ns") != identity["mtime_ns"]:
            return False
        return (
            self._is_valid_representative_index(data.get("representatives"))
            and self._is_valid_representative_index(data.get("taxid_index"))
            and self._is_valid_representative_index(data.get("species_taxid_index"))
        )

    @staticmethod
    def _is_valid_cache_index(index: object) -> bool:
        """Return whether a disk cache has the expected nested FASTA structure."""
        if not isinstance(index, dict):
            return False
        for species, assemblies in index.items():
            if not isinstance(species, str) or not isinstance(assemblies, dict):
                return False
            for assembly_id, records in assemblies.items():
                if not isinstance(assembly_id, str) or not isinstance(records, list):
                    return False
                for record in records:
                    if (
                        not isinstance(record, list)
                        or len(record) != 2
                        or not isinstance(record[0], str)
                        or not isinstance(record[1], int)
                    ):
                        return False
        return True

    @staticmethod
    def _is_valid_representative_index(index: object) -> bool:
        """Return whether cached representatives have the expected JSON structure."""
        if not isinstance(index, dict):
            return False
        for species, assemblies in index.items():
            if not isinstance(species, str) or not isinstance(assemblies, list):
                return False
            if not all(isinstance(assembly_id, str) for assembly_id in assemblies):
                return False
        return True

    def _save_cache(self) -> None:
        """Save the FASTA index and any loaded representative indexes to disk."""
        db_identity = self._file_identity(self.db_path)
        data = {
            "cache_version": CACHE_VERSION,
            "db_path": str(self.db_path),
            "db_size": db_identity["size"],
            "db_mtime_ns": db_identity["mtime_ns"],
            "index": self._species_cache,
        }
        if (
            self._representative_index is not None
            and self._taxid_index is not None
            and self._species_taxid_index is not None
            and self.metadata_path is not None
        ):
            metadata_identity = self._file_identity(self.metadata_path)
            data.update(
                {
                    "metadata_path": str(self.metadata_path),
                    "metadata_size": metadata_identity["size"],
                    "metadata_mtime_ns": metadata_identity["mtime_ns"],
                    "representatives": {
                        species: sorted(assemblies)
                        for species, assemblies in self._representative_index.items()
                    },
                    "taxid_index": {
                        taxid: sorted(assemblies)
                        for taxid, assemblies in self._taxid_index.items()
                    },
                    "species_taxid_index": {
                        taxid: sorted(assemblies)
                        for taxid, assemblies in self._species_taxid_index.items()
                    },
                }
            )
        with open(self.cache_file, "w") as f:
            json.dump(data, f)

    def _build_cache(self) -> None:
        """Scan FASTA headers to build species→assembly→record mappings."""
        if self._cache_loaded:
            return

        if self._load_cache():
            print(f"✅ 从缓存加载索引成功，共 {len(self._species_cache)} 个物种")
            return

        print("⏳ 正在构建参考基因组索引（首次使用，约需30秒）...")
        with open(self.db_path, "r") as f:
            pos = 0
            line = f.readline()
            while line:
                if line.startswith(">"):
                    parts = line[1:].strip().split(" ", 1)
                    seq_id = parts[0]
                    description = parts[1] if len(parts) > 1 else ""

                    species_match = re.match(r"^([A-Za-z]+ [a-z]+)", description)
                    if species_match:
                        species_name = species_match.group(1).lower()
                    else:
                        species_name = description.split(" strain ")[0].lower()

                    accession_match = re.search(r"(?:^|\s)acc_label=([^\s]+)", description)
                    assembly_id = accession_match.group(1) if accession_match else seq_id
                    assemblies = self._species_cache.setdefault(species_name, {})
                    assemblies.setdefault(assembly_id, []).append((seq_id, pos))

                pos = f.tell()
                line = f.readline()

        self._cache_loaded = True
        self._save_cache()
        print(f"索引构建完成，共 {len(self._species_cache)} 个物种")

    def _build_representative_index(self, require_taxid_fields: bool = False) -> None:
        """Stream GTDB metadata into compact representative and taxid indexes."""
        if self._representative_index is not None and (
            not require_taxid_fields
            or (
                self._taxid_index is not None
                and self._species_taxid_index is not None
            )
        ):
            return
        if self.metadata_path is None:
            raise ValueError("未配置 GTDB_METADATA_PATH")
        if not self.metadata_path.exists():
            raise FileNotFoundError(f"GTDB metadata 不存在: {self.metadata_path}")

        representatives: RepresentativeIndex = {}
        taxid_index: RepresentativeIndex = {}
        species_taxid_index: RepresentativeIndex = {}
        with open(self.metadata_path, "r", newline="") as handle:
            reader = csv.DictReader(handle, delimiter="\t")
            fieldnames = set(reader.fieldnames or [])
            missing = [field for field in _REQUIRED_METADATA_FIELDS if field not in fieldnames]
            if missing:
                raise ValueError(f"GTDB metadata 缺少必要字段: {', '.join(missing)}")
            missing_taxid = [
                field for field in _REQUIRED_TAXID_METADATA_FIELDS if field not in fieldnames
            ]
            if require_taxid_fields and missing_taxid:
                raise ValueError(f"GTDB metadata 缺少必要字段: {', '.join(missing_taxid)}")
            has_taxid_fields = not missing_taxid

            for row in reader:
                if row["gtdb_representative"] != "t":
                    continue
                species = self._gtdb_species(row.get("gtdb_taxonomy"))
                assembly_id = self._normalize_assembly_id(row.get("accession"))
                if assembly_id is None:
                    assembly_id = self._normalize_assembly_id(
                        row.get("ncbi_genbank_assembly_accession")
                    )
                if not species or not assembly_id:
                    continue

                representatives.setdefault(species, set()).add(assembly_id)
                if has_taxid_fields:
                    taxid = (row.get("ncbi_taxid") or "").strip()
                    species_taxid = (row.get("ncbi_species_taxid") or "").strip()
                    if taxid:
                        taxid_index.setdefault(taxid, set()).add(assembly_id)
                    if species_taxid:
                        species_taxid_index.setdefault(species_taxid, set()).add(assembly_id)

        self._representative_index = representatives
        if has_taxid_fields:
            self._taxid_index = taxid_index
            self._species_taxid_index = species_taxid_index
        else:
            self._taxid_index = None
            self._species_taxid_index = None
        self._save_cache()

    def _find_records_by_assembly_id(self, assembly_id: str) -> Optional[List[Record]]:
        """Find FASTA records for an assembly in the loaded species cache."""
        for assemblies in self._species_cache.values():
            records = assemblies.get(assembly_id)
            if records is not None:
                return records
        return None

    @staticmethod
    def _display_gtdb_species_name(species: str) -> str:
        """Format a normalized GTDB species key for user-facing errors."""
        parts = species.split(" ", 1)
        if len(parts) == 1:
            return parts[0].capitalize()
        epithet = parts[1]
        if "_" in epithet:
            base, *suffixes = epithet.split("_")
            epithet = "_".join(
                [base]
                + [suffix.upper() if len(suffix) == 1 else suffix for suffix in suffixes]
            )
        return f"{parts[0].capitalize()} {epithet}"

    def _taxid_candidate_text(self, assembly_ids: Set[str]) -> str:
        """Render taxid candidate assemblies with their GTDB species names."""
        representatives = self._representative_index or {}
        chunks = []
        for assembly_id in sorted(assembly_ids):
            species_names = sorted(
                self._display_gtdb_species_name(species)
                for species, assemblies in representatives.items()
                if assembly_id in assemblies
            )
            if species_names:
                chunks.append(f"{assembly_id} ({', '.join(species_names)})")
            else:
                chunks.append(assembly_id)
        return ", ".join(chunks)

    def _all_fasta_assembly_ids(self) -> List[str]:
        """Return all assembly identifiers present in the loaded FASTA cache."""
        return sorted(
            assembly_id
            for assemblies in self._species_cache.values()
            for assembly_id in assemblies
        )

    def _select_representative_assembly(
        self, species_name: str, matched_species: str, assemblies: Dict[str, List[Record]]
    ) -> List[Record]:
        """Resolve a multi-assembly species through GTDB representative metadata."""
        candidates = sorted(assemblies)
        candidate_text = ", ".join(candidates)
        if self.metadata_path is None:
            raise ValueError(
                f"物种名 '{species_name}' 对应多个 FASTA assembly: {candidate_text}; "
                "请设置 GTDB_METADATA_PATH"
            )

        self._build_representative_index()
        assert self._representative_index is not None
        representatives = self._representative_index.get(matched_species, set())
        if not representatives:
            raise ValueError(
                f"未找到物种名 '{species_name}' 的 GTDB representative; "
                f"FASTA 候选 assembly: {candidate_text}"
            )
        if len(representatives) > 1:
            representative_text = ", ".join(sorted(representatives))
            raise ValueError(
                f"物种名 '{species_name}' 对应多个 GTDB representative: "
                f"{representative_text}"
            )

        representative = next(iter(representatives))
        if representative not in assemblies:
            raise ValueError(
                f"物种名 '{species_name}' 的 GTDB representative '{representative}' "
                f"不在 FASTA 候选 assembly 中: {candidate_text}"
            )
        return assemblies[representative]

    def get_reference(self, species_name: str) -> str:
        """Retrieve a reference genome for a given species name."""
        self._build_cache()

        query = species_name.strip().lower()
        if query in self._species_cache:
            matched_species = query
        else:
            matches = [key for key in self._species_cache if query in key]
            if not matches:
                raise ValueError(f"未找到物种 '{species_name}' 在参考数据库中")
            if len(matches) > 1:
                raise ValueError(
                    f"物种名 '{species_name}' 不唯一，匹配项: {', '.join(matches[:5])}"
                )
            matched_species = matches[0]

        assemblies = self._species_cache[matched_species]
        if len(assemblies) == 1:
            records = next(iter(assemblies.values()))
        else:
            records = self._select_representative_assembly(
                species_name, matched_species, assemblies
            )
        return self._extract_sequence(records)

    def get_reference_by_taxonid(self, taxid: str) -> str:
        """Retrieve a GTDB representative reference selected by NCBI Taxon ID."""
        if self.metadata_path is None:
            raise ValueError(
                f"Taxon ID '{taxid}' 查询需要配置 GTDB_METADATA_PATH"
            )

        if not self._cache_loaded and not self._load_cache():
            self._build_cache()
        self._build_representative_index(require_taxid_fields=True)
        assert self._taxid_index is not None
        assert self._species_taxid_index is not None

        assemblies = self._taxid_index.get(taxid, set())
        if not assemblies:
            assemblies = self._species_taxid_index.get(taxid, set())
        if not assemblies:
            raise ValueError(f"未找到 taxid '{taxid}' 对应的 GTDB representative")

        if len(assemblies) > 1:
            raise ValueError(
                f"taxid '{taxid}' 对应多个 GTDB representative: "
                f"{self._taxid_candidate_text(assemblies)}; "
                "请使用更具体的菌株级 Taxon ID 或改用 --species"
            )

        assembly_id = next(iter(assemblies))
        records = self._find_records_by_assembly_id(assembly_id)
        if records is None:
            candidate_text = ", ".join(self._all_fasta_assembly_ids())
            raise ValueError(
                f"taxid '{taxid}' 的 GTDB representative '{assembly_id}' "
                f"不在 FASTA 候选 assembly 中: {candidate_text}"
            )
        return self._extract_sequence(records)

    def _extract_sequence(self, records: List[Record]) -> str:
        """Create one pseudo-reference and a sidecar contig-coordinate map."""
        tmp_fd, tmp_path = tempfile.mkstemp(suffix=".fa", prefix="ref_")
        os.close(tmp_fd)
        map_path = Path(tmp_path).with_suffix(".contig_map.tsv")
        extracted: List[Tuple[str, str]] = []
        with open(self.db_path, "r") as f_in:
            for seq_id, offset in records:
                f_in.seek(offset)
                line = f_in.readline()
                if not line.startswith(">"):
                    raise ValueError(f"在偏移量 {offset} 处未找到序列头部")
                chunks = []
                while True:
                    line = f_in.readline()
                    if not line or line.startswith(">"):
                        break
                    chunks.append(line.strip())
                extracted.append((seq_id, "".join(chunks)))

        if not extracted:
            Path(tmp_path).unlink(missing_ok=True)
            raise ValueError("所选 assembly 不包含 FASTA 序列")

        pseudo_name = (
            extracted[0][0] if len(extracted) == 1 else f"{extracted[0][0]}_pseudo"
        )
        with open(tmp_path, "w") as f_out, open(map_path, "w") as map_out:
            f_out.write(f">{pseudo_name}\n")
            map_out.write(
                "pseudo_start\tpseudo_end\tcontig_id\tcontig_start\tcontig_end\n"
            )
            pseudo_position = 1
            for index, (seq_id, sequence) in enumerate(extracted):
                if index:
                    f_out.write("N" * CONTIG_GAP_SIZE)
                    pseudo_position += CONTIG_GAP_SIZE
                start = pseudo_position
                end = start + len(sequence) - 1
                f_out.write(sequence)
                map_out.write(f"{start}\t{end}\t{seq_id}\t1\t{len(sequence)}\n")
                pseudo_position = end + 1
            f_out.write("\n")

        return tmp_path

    def clear_cache(self) -> None:
        """Clear in-memory cache to free memory."""
        self._species_cache.clear()
        self._representative_index = None
        self._taxid_index = None
        self._species_taxid_index = None
        self._cache_loaded = False


_global_manager: Optional[ReferenceManager] = None


def get_reference_manager(db_path: Optional[str] = None) -> ReferenceManager:
    """Get the global ReferenceManager instance (singleton)."""
    global _global_manager
    if _global_manager is None:
        _global_manager = ReferenceManager(db_path)
    return _global_manager

# --- original module: tree.py ---
"""IQ-TREE integration."""

import logging
import shutil
import subprocess
from pathlib import Path
from typing import Optional, Tuple


LOGGER = logging.getLogger(__name__)


def build_tree(
    matrix_path: Path, output_dir: Path, snp_count: int, threads: int = 1
) -> Tuple[str, Optional[Path]]:
    if type(threads) is not int or threads < 1:
        raise ValueError("IQ-TREE threads must be an integer >= 1")
    thread_count = threads
    if snp_count == 0:
        message = "skipped: no SNPs remained after filtering"
        LOGGER.warning(message)
        return message, None
    executable = shutil.which("iqtree2") or shutil.which("iqtree")
    if executable is None:
        message = "not built: IQ-TREE (iqtree2 or iqtree) was not found on PATH"
        LOGGER.warning("%s; the SNP matrix can be used to build the tree manually", message)
        return message, None
    prefix = output_dir / "iqtree_run"
    command = [
        executable,
        "-s",
        str(matrix_path),
        "-m",
        "MFP",
        "-bb",
        "1000",
        "-nt",
        str(thread_count),
        "-pre",
        str(prefix),
        "-redo",
    ]
    LOGGER.info("Running IQ-TREE")
    completed = subprocess.run(command, capture_output=True, text=True, check=False)
    if completed.returncode != 0:
        detail = (completed.stderr or completed.stdout).strip().replace("\n", " ")
        message = f"failed: IQ-TREE exited with code {completed.returncode}: {detail}"
        LOGGER.error(message)
        return message, None
    treefile = Path(f"{prefix}.treefile")
    if not treefile.is_file():
        message = "failed: IQ-TREE returned success but did not create a .treefile"
        LOGGER.error(message)
        return message, None
    final_tree = output_dir / "final_tree.nwk"
    shutil.copyfile(treefile, final_tree)
    return "completed", final_tree


# --- original module: __init__.py ---
"""Bacterial genome SNP detection and filtering pipeline."""


__version__ = "1.0.0"
__all__ = ["ReferenceManager", "get_reference_manager"]
# --- original module: align.py ---
"""Genome alignment backends and SNP extraction."""

import logging
import re
import shutil
import subprocess
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple



LOGGER = logging.getLogger(__name__)
CIGAR_RE = re.compile(r"(\d+)([MIDNSHP=X])")
CANONICAL = frozenset("ACGT")


def load_reference(path: Path) -> ReferenceGenome:
    records_list = load_fasta(path)
    records: Dict[str, str] = {}
    offsets: Dict[str, int] = {}
    offset = 0
    for name, sequence in records_list:
        if name in records:
            raise ValueError(f"Duplicate reference record name: {name}")
        records[name] = sequence
        offsets[name] = offset
        offset += len(sequence)
    return ReferenceGenome(path=path, records=records, offsets=offsets, length=offset)


def choose_alignment_backend(requested: str) -> str:
    if requested == "minimap2":
        if not shutil.which("minimap2"):
            raise RuntimeError("--aligner minimap2 was requested, but minimap2 is not on PATH")
        return "minimap2"
    if requested == "internal":
        return "internal"
    return "minimap2" if shutil.which("minimap2") else "internal"


def align_sample(
    reference: ReferenceGenome,
    query_path: Path,
    sample_name: str,
    backend: str,
    threads: int,
) -> SampleCalls:
    if backend == "minimap2":
        return _align_minimap2(reference, query_path, sample_name, threads)
    return _align_internal(reference, query_path, sample_name)


def _record_call(calls: SampleCalls, position: int, ref_base: str, query_base: str) -> None:
    query_base = query_base.upper()
    if query_base in CANONICAL:
        if query_base != ref_base:
            existing = calls.variants.get(position)
            calls.variants[position] = query_base if existing in (None, query_base) else "N"
    elif query_base != ref_base:
        existing = calls.ambiguous.get(position)
        calls.ambiguous[position] = query_base if existing in (None, query_base) else "N"


def _align_internal(
    reference: ReferenceGenome, query_path: Path, sample_name: str
) -> SampleCalls:
    query_records = load_fasta(query_path)
    calls = SampleCalls(name=sample_name, path=query_path)
    if len(reference.records) != len(query_records):
        raise RuntimeError(
            f"Internal aligner only supports equally structured, full-length genomes; "
            f"{query_path.name} has {len(query_records)} record(s), reference has "
            f"{len(reference.records)}. Install minimap2 for contig assemblies."
        )
    for (ref_name, ref_sequence), (query_name, query_sequence) in zip(
        reference.records.items(), query_records
    ):
        if len(ref_sequence) != len(query_sequence):
            raise RuntimeError(
                f"Internal aligner requires equal sequence lengths ({query_path.name}: "
                f"{len(query_sequence)}, reference record {ref_name}: {len(ref_sequence)}). "
                "Install minimap2 for assemblies with indels or contigs."
            )
        offset = reference.offsets[ref_name]
        calls.intervals.append((offset, offset + len(ref_sequence)))
        for local_position, (ref_base, query_base) in enumerate(
            zip(ref_sequence, query_sequence)
        ):
            _record_call(calls, offset + local_position, ref_base, query_base)
    calls.finalize_intervals()
    return calls


def _align_minimap2(
    reference: ReferenceGenome,
    query_path: Path,
    sample_name: str,
    threads: int,
) -> SampleCalls:
    command = [
        "minimap2",
        "-a",
        "--eqx",
        "-x",
        "asm5",
        "-t",
        str(max(1, threads)),
        str(reference.path),
        str(query_path),
    ]
    LOGGER.debug("Running: %s", " ".join(command))
    process = subprocess.Popen(
        command,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        encoding="ascii",
        errors="replace",
    )
    assert process.stdout is not None
    calls = SampleCalls(name=sample_name, path=query_path)
    try:
        for line in process.stdout:
            if line.startswith("@"):
                continue
            _parse_sam_alignment(line, reference, calls)
        stderr = process.stderr.read() if process.stderr else ""
        return_code = process.wait()
    except Exception:
        process.kill()
        process.wait()
        raise
    if return_code != 0:
        raise RuntimeError(
            f"minimap2 failed for {query_path.name} (exit {return_code}): {stderr.strip()}"
        )
    calls.finalize_intervals()
    return calls


def _parse_sam_alignment(
    line: str, reference: ReferenceGenome, calls: SampleCalls
) -> None:
    fields = line.rstrip("\n").split("\t")
    if len(fields) < 11:
        raise RuntimeError("Malformed SAM output from minimap2")
    flag = int(fields[1])
    if flag & (0x4 | 0x100):  # unmapped or secondary; supplementary mappings are useful
        return
    reference_name = fields[2]
    if reference_name not in reference.records:
        raise RuntimeError(f"SAM refers to unknown reference record: {reference_name}")
    reference_sequence = reference.records[reference_name]
    reference_position = int(fields[3]) - 1
    query_position = 0
    query_sequence = fields[9].upper()
    global_offset = reference.offsets[reference_name]
    for length_text, operation in CIGAR_RE.findall(fields[5]):
        length = int(length_text)
        if operation in ("M", "=", "X"):
            start = reference_position
            end = reference_position + length
            if end > len(reference_sequence) or query_position + length > len(query_sequence):
                raise RuntimeError("CIGAR extends beyond sequence bounds")
            calls.intervals.append((global_offset + start, global_offset + end))
            ref_chunk = reference_sequence[start:end]
            query_chunk = query_sequence[query_position : query_position + length]
            if operation != "=" or any(base not in CANONICAL for base in query_chunk):
                for index, (ref_base, query_base) in enumerate(zip(ref_chunk, query_chunk)):
                    if ref_base != query_base:
                        _record_call(
                            calls, global_offset + start + index, ref_base, query_base
                        )
            reference_position = end
            query_position += length
        elif operation in ("I", "S"):
            query_position += length
        elif operation in ("D", "N"):
            reference_position += length
        elif operation in ("H", "P"):
            continue
        else:
            raise RuntimeError(f"Unsupported CIGAR operation: {operation}")


# --- original module: filtering.py ---
"""Coverage and sliding-window recombination filters."""

import math
from bisect import bisect_left, bisect_right
from statistics import fmean, pstdev
from typing import Iterable, List, Sequence, Set, Tuple



def filter_snps(
    samples: Sequence[SampleCalls],
    reference_length: int,
    min_coverage_fraction: float = 0.9,
    window_size: int = 50,
    step_size: int = 10,
    sd_threshold: float = 3.0,
) -> FilterResult:
    initial = sorted({position for sample in samples for position, base in sample.variants.items() if base != "N"})
    required_samples = math.ceil(min_coverage_fraction * len(samples))
    coverage_positions = [
        position
        for position in initial
        if sum(sample.is_covered(position) for sample in samples) >= required_samples
    ]
    coverage_removed = frozenset(set(initial) - set(coverage_positions))
    regions, mean_density, density_sd = find_recombination_regions(
        coverage_positions, reference_length, window_size, step_size, sd_threshold
    )
    recombination_removed: Set[int] = set()
    for start, end in regions:
        left = bisect_left(coverage_positions, start)
        right = bisect_left(coverage_positions, end)
        recombination_removed.update(coverage_positions[left:right])
    final = [position for position in coverage_positions if position not in recombination_removed]
    return FilterResult(
        initial_positions=tuple(initial),
        coverage_positions=tuple(coverage_positions),
        final_positions=tuple(final),
        coverage_removed=coverage_removed,
        recombination_removed=frozenset(recombination_removed),
        recombination_regions=tuple(regions),
        window_mean=mean_density,
        window_sd=density_sd,
    )


def find_recombination_regions(
    positions: Sequence[int],
    reference_length: int,
    window_size: int,
    step_size: int,
    sd_threshold: float,
) -> Tuple[List[Tuple[int, int]], float, float]:
    if reference_length <= 0:
        return [], 0.0, 0.0
    starts = list(range(0, max(1, reference_length - window_size + 1), step_size))
    final_start = max(0, reference_length - window_size)
    if not starts or starts[-1] != final_start:
        starts.append(final_start)
    densities = [
        (bisect_left(positions, min(reference_length, start + window_size)) - bisect_left(positions, start))
        / min(window_size, reference_length - start)
        for start in starts
    ]
    mean_density = fmean(densities) if densities else 0.0
    density_sd = pstdev(densities) if len(densities) > 1 else 0.0
    threshold = mean_density + sd_threshold * density_sd
    candidates = [
        (start, min(reference_length, start + window_size))
        for start, density in zip(starts, densities)
        if density > threshold
    ]
    merged: List[Tuple[int, int]] = []
    for start, end in candidates:
        if merged and start <= merged[-1][1]:
            merged[-1] = (merged[-1][0], max(end, merged[-1][1]))
        else:
            merged.append((start, end))
    return merged, mean_density, density_sd

# --- original module: reporting.py ---
"""Pipeline output writers."""

import csv
import json
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Mapping, Optional, Sequence, Set



GENETIC_CODE = {
    "TTT": "F",
    "TTC": "F",
    "TTA": "L",
    "TTG": "L",
    "TCT": "S",
    "TCC": "S",
    "TCA": "S",
    "TCG": "S",
    "TAT": "Y",
    "TAC": "Y",
    "TAA": "*",
    "TAG": "*",
    "TGT": "C",
    "TGC": "C",
    "TGA": "*",
    "TGG": "W",
    "CTT": "L",
    "CTC": "L",
    "CTA": "L",
    "CTG": "L",
    "CCT": "P",
    "CCC": "P",
    "CCA": "P",
    "CCG": "P",
    "CAT": "H",
    "CAC": "H",
    "CAA": "Q",
    "CAG": "Q",
    "CGT": "R",
    "CGC": "R",
    "CGA": "R",
    "CGG": "R",
    "ATT": "I",
    "ATC": "I",
    "ATA": "I",
    "ATG": "M",
    "ACT": "T",
    "ACC": "T",
    "ACA": "T",
    "ACG": "T",
    "AAT": "N",
    "AAC": "N",
    "AAA": "K",
    "AAG": "K",
    "AGT": "S",
    "AGC": "S",
    "AGA": "R",
    "AGG": "R",
    "GTT": "V",
    "GTC": "V",
    "GTA": "V",
    "GTG": "V",
    "GCT": "A",
    "GCC": "A",
    "GCA": "A",
    "GCG": "A",
    "GAT": "D",
    "GAC": "D",
    "GAA": "E",
    "GAG": "E",
    "GGT": "G",
    "GGC": "G",
    "GGA": "G",
    "GGG": "G",
}


@dataclass(frozen=True)
class VariantEvent:
    pos: int
    ref: str
    alt: str
    variant_type: str
    region: str


def write_initial_snp_list(
    path: Path,
    reference: ReferenceGenome,
    samples: Sequence[SampleCalls],
    positions: Sequence[int],
) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        header = ["reference_position", "reference_base", "covered_samples"]
        for sample in samples:
            header.extend([sample.name, f"{sample.name}_covered"])
        writer.writerow(header)
        for position in positions:
            reference_base = reference.base(position)
            row = [
                position + 1,
                reference_base,
                sum(sample.is_covered(position) for sample in samples),
            ]
            for sample in samples:
                row.extend(
                    [
                        sample.base_at(position, reference_base),
                        "yes" if sample.is_covered(position) else "no",
                    ]
                )
            writer.writerow(row)


def write_snp_matrix(
    path: Path,
    reference: ReferenceGenome,
    samples: Sequence[SampleCalls],
    positions: Sequence[int],
) -> None:
    records = []
    for sample in samples:
        sequence = "".join(
            sample.base_at(position, reference.base(position)) for position in positions
        )
        records.append((sample.name, sequence))
    write_fasta(records, path)


def write_mutation_report(
    path: Path,
    reference: ReferenceGenome,
    samples: Sequence[SampleCalls],
    result: FilterResult,
) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(
            [
                "reference_position",
                "reference_base",
                "alternate_base",
                "strain_count",
                "filtered",
                "filter_reason",
            ]
        )
        for position in result.initial_positions:
            reference_base = reference.base(position)
            alternate_bases = sorted(
                {
                    sample.variants[position]
                    for sample in samples
                    if position in sample.variants and sample.variants[position] != "N"
                }
            )
            if position in result.coverage_removed:
                filtered, reason = "yes", "insufficient_coverage"
            elif position in result.recombination_removed:
                filtered, reason = "yes", "recombination_region"
            else:
                filtered, reason = "no", ""
            for alternate in alternate_bases:
                writer.writerow(
                    [
                        position + 1,
                        reference_base,
                        alternate,
                        sum(sample.variants.get(position) == alternate for sample in samples),
                        filtered,
                        reason,
                    ]
                )


def write_variants_table(
    variants_path,
    reference,
    samples,
    result,
    summary_path,
) -> None:
    sample_events: Dict[str, Dict[int, VariantEvent]] = {}
    for sample in samples:
        events = (
            _events_from_paf(sample.paf_path, reference)
            if sample.paf_path is not None
            else []
        )
        sample_events[sample.name] = {}
        for event in events:
            sample_events[sample.name].setdefault(event.pos, event)

    variants_path = Path(variants_path)
    variants_path.parent.mkdir(parents=True, exist_ok=True)
    effects: Counter[str] = Counter()
    with variants_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle, delimiter="\t", lineterminator="\n")
        writer.writerow(
            [
                "REGION",
                "POS",
                "REF",
                *[sample.name for sample in samples],
                "VARIANT_TYPE",
                "REF_CODON",
                "REF_AA",
                "ALT_CODON",
                "ALT_AA",
                "EFFECT",
            ]
        )
        for position in sorted(result.final_positions):
            region, _, _ = _contig_for_position(reference, position)
            reference_base = reference.base(position)
            event = _event_for_position(position, samples, sample_events)
            if event is None:
                event = VariantEvent(position, reference_base, "NA", "UNKNOWN", region)
            ref_codon, ref_aa, alt_codon, alt_aa, effect = _annotate_event(
                event,
                reference,
            )
            effects[effect] += 1
            writer.writerow(
                [
                    region,
                    position + 1,
                    event.ref,
                    *[
                        sample.base_at(position, reference_base)
                        for sample in samples
                    ],
                    event.variant_type,
                    ref_codon,
                    ref_aa,
                    alt_codon,
                    alt_aa,
                    effect,
                ]
            )

    summary_path = Path(summary_path)
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    with summary_path.open("w", encoding="utf-8") as handle:
        handle.write(f"unique_variant_positions\t{len(result.final_positions)}\n")
        for effect in sorted(effects):
            handle.write(f"{effect}\t{effects[effect]}\n")


def _event_for_position(
    position: int,
    samples: Sequence[SampleCalls],
    sample_events: Mapping[str, Mapping[int, VariantEvent]],
) -> Optional[VariantEvent]:
    for sample in samples:
        event = sample_events.get(sample.name, {}).get(position)
        if event is not None:
            return event
    return None


def _events_from_paf(
    paf: Path,
    reference: ReferenceGenome,
) -> Sequence[VariantEvent]:
    if not paf.is_file():
        return []

    events = []
    with paf.open(encoding="utf-8") as paf_file:
        for line in paf_file:
            if not line.strip():
                continue
            fields = line.rstrip("\n").split("\t")
            if len(fields) < 12:
                continue
            region = fields[5]
            if region not in reference.records:
                raise ValueError(f"PAF refers to unknown reference record: {region}")
            cs_tag = next(
                (field[5:] for field in fields[12:] if field.startswith("cs:Z:")),
                None,
            )
            if cs_tag is not None:
                events.extend(
                    _events_from_cs(
                        cs_tag,
                        int(fields[7]),
                        reference.records[region],
                        reference.offsets[region],
                        region,
                    )
                )
    return events


def _events_from_cs(
    cs: str,
    ref_start: int,
    reference_seq: str,
    global_offset: int,
    region: str,
) -> Sequence[VariantEvent]:
    events = []
    i = 0
    ref_pos = ref_start
    while i < len(cs):
        op = cs[i]
        if op == ":":
            i += 1
            start = i
            while i < len(cs) and cs[i].isdigit():
                i += 1
            ref_pos += int(cs[start:i])
        elif op == "*":
            if i + 2 >= len(cs):
                break
            alt_base = cs[i + 2].upper()
            events.append(
                VariantEvent(
                    global_offset + ref_pos,
                    reference_seq[ref_pos].upper(),
                    alt_base,
                    "SNP",
                    region,
                )
            )
            ref_pos += 1
            i += 3
        elif op in {"+", "-"}:
            sequence, i = _read_cs_indel_sequence(cs, i + 1, reference_seq, ref_pos, op)
            if not sequence:
                continue
            if op == "+":
                events.append(
                    VariantEvent(
                        global_offset + max(ref_pos - 1, 0),
                        "-",
                        sequence,
                        "INSERTION",
                        region,
                    )
                )
            else:
                deleted = reference_seq[ref_pos : ref_pos + len(sequence)].upper()
                events.append(
                    VariantEvent(
                        global_offset + ref_pos,
                        deleted,
                        "-",
                        "DELETION",
                        region,
                    )
                )
                ref_pos += len(sequence)
        elif op == "=":
            i += 1
            start = i
            while i < len(cs) and cs[i].isalpha():
                i += 1
            ref_pos += i - start
        else:
            i += 1
    return events


def _read_cs_indel_sequence(
    cs: str,
    index: int,
    reference_seq: str,
    ref_pos: int,
    op: str,
) -> tuple[str, int]:
    length_start = index
    while index < len(cs) and cs[index].isdigit():
        index += 1
    length = int(cs[length_start:index]) if index > length_start else None
    sequence_start = index
    while index < len(cs) and cs[index].isalpha():
        index += 1
    sequence = cs[sequence_start:index].upper()
    if not sequence and length is not None and op == "-":
        sequence = reference_seq[ref_pos : ref_pos + length].upper()
    return sequence, index


def _annotate_event(
    event: VariantEvent,
    reference: ReferenceGenome,
) -> tuple[str, str, str, str, str]:
    if event.variant_type == "UNKNOWN":
        return "NA", "NA", "NA", "NA", "NA"
    if event.variant_type == "INSERTION":
        effect = "inframe_insertion" if len(event.alt) % 3 == 0 else "frameshift"
        return "NA", "NA", "NA", "NA", effect
    if event.variant_type == "DELETION":
        effect = "inframe_deletion" if len(event.ref) % 3 == 0 else "frameshift"
        return "NA", "NA", "NA", "NA", effect
    if event.variant_type != "SNP":
        return "NA", "NA", "NA", "NA", "frameshift"

    reference_seq = reference.records[event.region]
    contig_offset = reference.offsets[event.region]
    local_position = event.pos - contig_offset
    codon_start = (local_position // 3) * 3
    ref_codon = reference_seq[codon_start : codon_start + 3].upper()
    if len(ref_codon) != 3:
        return "NA", "NA", "NA", "NA", "NA"
    offset = local_position % 3
    alt_codon = ref_codon[:offset] + event.alt + ref_codon[offset + 1 :]
    ref_aa = _translate(ref_codon)
    alt_aa = _translate(alt_codon)
    if ref_aa == alt_aa:
        effect = "synonymous"
    elif ref_aa != "*" and alt_aa == "*":
        effect = "stop_gained"
    elif ref_aa == "*" and alt_aa != "*":
        effect = "stop_lost"
    else:
        effect = "nonsynonymous"
    return ref_codon, ref_aa, alt_codon, alt_aa, effect


def _translate(codon: str) -> str:
    return GENETIC_CODE.get(codon.upper(), "X")


def _contig_for_position(
    reference: ReferenceGenome,
    global_position: int,
) -> tuple[str, int, str]:
    for name, offset in reference.offsets.items():
        sequence = reference.records[name]
        if offset <= global_position < offset + len(sequence):
            return name, offset, sequence
    raise IndexError(global_position)


def _ratio(removed: int, starting: int) -> str:
    return f"{(100.0 * removed / starting):.2f}%" if starting else "0.00%"


def write_summary(
    path: Path,
    sample_count: int,
    result: FilterResult,
    timings: Mapping[str, float],
    arguments: Mapping[str, object],
    aligner: str,
    tree_status: str,
    validation: Optional[Mapping[str, float]] = None,
) -> None:
    initial = len(result.initial_positions)
    after_coverage = len(result.coverage_positions)
    final = len(result.final_positions)
    lines = [
        "Bacterial genome comparison and mutation detection summary",
        "=" * 58,
        f"Input strain count: {sample_count}",
        f"Alignment backend: {aligner}",
        f"Initial unique SNP positions: {initial}",
        (
            f"After coverage filter (>= {float(arguments['min_coverage']) * 100:g}% strains): "
            f"{after_coverage}; removed {initial - after_coverage} "
            f"({_ratio(initial - after_coverage, initial)})"
        ),
        (
            f"After recombination sliding-window filter: {final}; removed "
            f"{after_coverage - final} ({_ratio(after_coverage - final, after_coverage)})"
        ),
        f"Final SNPs used for tree building: {final}",
        f"Recombination candidate regions: {len(result.recombination_regions)}",
        f"Window density mean: {result.window_mean:.8f}",
        f"Window density standard deviation: {result.window_sd:.8f}",
        f"Tree building: {tree_status}",
        "",
        "Runtime by step (seconds)",
        "-" * 25,
    ]
    for name, seconds in timings.items():
        lines.append(f"{name}: {seconds:.3f}")
    lines.extend(["", "Command-line arguments", "-" * 22])
    for key, value in arguments.items():
        lines.append(f"--{key.replace('_', '-')}: {value}")
    if validation is not None:
        lines.extend(
            [
                "",
                "Simulation validation",
                "-" * 21,
                f"True unique SNPs: {int(validation['true_snps'])}",
                f"Detected unique SNPs: {int(validation['detected_snps'])}",
                f"True-positive SNPs: {int(validation['true_positives'])}",
                f"Recovery Rate: {validation['recovery_rate']:.6f}",
                f"Precision: {validation['precision']:.6f}",
            ]
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")

# --- original module: simulation.py ---
"""Generate synthetic bacterial genomes with known SNP truth."""

import csv
import random
from pathlib import Path
from typing import Dict, List, Sequence, Set, Tuple



CANONICAL = "ACGT"


def generate_simulated_samples(
    reference: ReferenceGenome,
    output_dir: Path,
    snp_rate: float,
    sample_count: int = 5,
    seed: int = 42,
) -> Tuple[List[Path], Set[int]]:
    output_dir.mkdir(parents=True, exist_ok=True)
    eligible = [
        reference.offsets[name] + local_position
        for name, sequence in reference.records.items()
        for local_position, base in enumerate(sequence)
        if base in CANONICAL
    ]
    mutation_count = min(len(eligible), max(1, round(len(eligible) * snp_rate)))
    rng = random.Random(seed)
    paths: List[Path] = []
    truth_union: Set[int] = set()
    truth_rows: List[Tuple[str, int, str, str]] = []
    for sample_index in range(1, sample_count + 1):
        sample_name = f"simulated_{sample_index:03d}"
        selected = rng.sample(eligible, mutation_count)
        mutations: Dict[int, str] = {}
        for position in selected:
            reference_base = reference.base(position)
            alternate = rng.choice([base for base in CANONICAL if base != reference_base])
            mutations[position] = alternate
            truth_union.add(position)
            truth_rows.append((sample_name, position + 1, reference_base, alternate))
        records = []
        for record_name, sequence in reference.records.items():
            offset = reference.offsets[record_name]
            mutable = list(sequence)
            for global_position, alternate in mutations.items():
                local_position = global_position - offset
                if 0 <= local_position < len(mutable):
                    mutable[local_position] = alternate
            records.append((record_name, "".join(mutable)))
        path = output_dir / f"{sample_name}.fasta"
        write_fasta(records, path)
        paths.append(path)
    with (output_dir / "simulation_truth.csv").open(
        "w", encoding="utf-8", newline=""
    ) as handle:
        writer = csv.writer(handle)
        writer.writerow(["sample", "reference_position", "reference_base", "alternate_base"])
        writer.writerows(truth_rows)
    return paths, truth_union


# --- original module: pipeline.py ---
"""End-to-end bacterial SNP pipeline orchestration."""

import logging
import math
import shutil
import subprocess
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Dict, List, Mapping, Optional, Sequence, Set, Tuple



LOGGER = logging.getLogger(__name__)
FASTA_SUFFIXES = frozenset({".fa", ".fasta", ".fna", ".fas"})


def discover_queries(input_path: Path) -> List[Path]:
    """Accept either one query FASTA file or a directory of query FASTAs."""
    if input_path.is_file():
        if input_path.suffix.lower() not in FASTA_SUFFIXES:
            raise ValueError(f"Query input is not a FASTA file: {input_path}")
        return [input_path]
    if not input_path.is_dir():
        raise ValueError(f"Query input does not exist: {input_path}")
    paths = sorted(
        path for path in input_path.iterdir()
        if path.is_file() and path.suffix.lower() in FASTA_SUFFIXES
    )
    if not paths:
        raise ValueError(f"No query FASTA files found in directory: {input_path}")
    return paths


def _unique_sample_names(paths: Sequence[Path]) -> List[str]:
    names: List[str] = []
    used = set()
    for path in paths:
        base = path.stem.replace(" ", "_")
        name = base
        suffix = 2
        while name in used:
            name = f"{base}_{suffix}"
            suffix += 1
        used.add(name)
        names.append(name)
    return names


def _write_paf(
    reference,
    query_path: Path,
    sample_name: str,
    threads: int,
    paf_dir: Path,
) -> Path:
    paf_dir.mkdir(parents=True, exist_ok=True)
    paf_path = paf_dir / f"{sample_name}.paf"
    command = [
        "minimap2",
        "-c",
        "--cs",
        "-x",
        "asm5",
        "-t",
        str(max(1, threads)),
        str(reference.path),
        str(query_path),
    ]
    LOGGER.debug("Running: %s", " ".join(command))
    with paf_path.open("w", encoding="ascii") as output:
        process = subprocess.run(
            command,
            stdout=output,
            stderr=subprocess.PIPE,
            text=True,
            encoding="ascii",
            errors="replace",
        )
    if process.returncode != 0:
        raise RuntimeError(
            f"minimap2 PAF generation failed for {query_path.name} "
            f"(exit {process.returncode}): {process.stderr.strip()}"
        )
    return paf_path


def _align_one(
    reference,
    path: Path,
    name: str,
    backend: str,
    threads: int,
    paf_dir: Optional[Path],
) -> SampleCalls:
    calls = align_sample(reference, path, name, backend, threads)
    if backend == "minimap2" and paf_dir is not None:
        calls.paf_path = _write_paf(reference, path, name, threads, paf_dir)
    return calls


def _align_all(
    reference,
    paths: Sequence[Path],
    backend: str,
    total_threads: int,
    paf_dir: Optional[Path] = None,
) -> List[SampleCalls]:
    names = _unique_sample_names(paths)
    worker_count = min(len(paths), max(1, total_threads))
    threads_per_worker = max(1, total_threads // worker_count)
    results: List[Optional[SampleCalls]] = [None] * len(paths)
    with ThreadPoolExecutor(max_workers=worker_count) as executor:
        futures = {
            executor.submit(
                _align_one,
                reference,
                path,
                name,
                backend,
                threads_per_worker,
                paf_dir,
            ): index
            for index, (path, name) in enumerate(zip(paths, names))
        }
        for completed_count, future in enumerate(as_completed(futures), 1):
            index = futures[future]
            results[index] = future.result()
            LOGGER.info("Aligned %d/%d: %s", completed_count, len(paths), names[index])
    return [result for result in results if result is not None]


def run_pipeline(arguments: Mapping[str, object]) -> int:
    overall_start = time.perf_counter()
    out_dir = Path(str(arguments["out_dir"])).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    # ----- 解析参考基因组来源 -----
    reference_path = None
    temp_ref_path = None  # 用于清理临时文件

    if arguments.get("taxonid"):
        # 通过 NCBI Taxon ID 获取参考基因组
        manager = get_reference_manager()
        temp_ref_path = manager.get_reference_by_taxonid(str(arguments["taxonid"]))
        reference_path = Path(temp_ref_path)
        LOGGER.info("已为 Taxon ID '%s' 提取参考基因组", arguments["taxonid"])
    elif arguments.get("species"):
        # 通过物种名获取参考基因组
        manager = get_reference_manager()
        temp_ref_path = manager.get_reference(str(arguments["species"]))
        reference_path = Path(temp_ref_path)
        LOGGER.info("已为物种 '%s' 提取参考基因组", arguments["species"])
    elif arguments.get("reference"):
        reference_path = Path(str(arguments["reference"])).resolve()
    else:
        raise ValueError("必须提供 --reference、--species 或 --taxonid")

    if not reference_path or not reference_path.is_file():
        raise ValueError(f"参考基因组文件不存在: {reference_path}")
    temp_map_path = (
        reference_path.with_suffix(".contig_map.tsv") if temp_ref_path else None
    )
    if temp_map_path and temp_map_path.is_file():
        shutil.copyfile(temp_map_path, out_dir / "reference_contig_map.tsv")
    # ----- 解析结束 -----

    timings: Dict[str, float] = {}

    # 用 try-finally 包裹核心逻辑，确保临时文件被清理
    try:
        step_start = time.perf_counter()
        reference = load_reference(reference_path)
        truth: Optional[Set[int]] = None
        if bool(arguments["simulate"]):
            LOGGER.info("Generating simulated genomes")
            query_paths, truth = generate_simulated_samples(
                reference,
                out_dir / "simulated_queries",
                float(arguments["simulate_snp_rate"]),
                int(arguments["simulate_samples"]),
                int(arguments["seed"]),
            )
        else:
            query_input = arguments.get("query_dir")
            if not query_input:
                raise ValueError("A query FASTA file or directory is required unless --simulate is enabled")
            query_paths = discover_queries(Path(str(query_input)).resolve())
        timings["input_and_simulation"] = time.perf_counter() - step_start

        backend = choose_alignment_backend(str(arguments["aligner"]))
        if backend == "internal" and str(arguments["aligner"]) == "auto":
            LOGGER.warning(
                "minimap2 was not found; using the internal equal-length-genome aligner. "
                "Install minimap2 to process contigs or indels."
            )
        step_start = time.perf_counter()
        samples = _align_all(
            reference,
            query_paths,
            backend,
            int(arguments["threads"]),
            out_dir / "alignments",
        )
        timings["alignment_and_snp_detection"] = time.perf_counter() - step_start

        step_start = time.perf_counter()
        result = filter_snps(
            samples,
            reference.length,
            float(arguments["min_coverage"]),
            int(arguments["window_size"]),
            int(arguments["step_size"]),
            float(arguments["sd_threshold"]),
        )
        timings["coverage_and_recombination_filtering"] = time.perf_counter() - step_start

        step_start = time.perf_counter()
        write_initial_snp_list(
            out_dir / "initial_snp_list.csv", reference, samples, result.initial_positions
        )
        matrix_path = out_dir / "filtered_snp_matrix.fasta"
        write_snp_matrix(matrix_path, reference, samples, result.final_positions)
        write_mutation_report(out_dir / "mutation_report.csv", reference, samples, result)
        write_variants_table(
            out_dir / "variants.tsv",
            reference,
            samples,
            result,
            out_dir / "variants_summary.txt",
        )
        timings["output_writing"] = time.perf_counter() - step_start

        step_start = time.perf_counter()
        tree_status, _ = build_tree(
            matrix_path, out_dir, len(result.final_positions), arguments["threads"]
        )
        timings["tree_building"] = time.perf_counter() - step_start

        validation = None
        if truth is not None:
            detected = set(result.initial_positions)
            true_positives = len(truth & detected)
            validation = {
                "true_snps": float(len(truth)),
                "detected_snps": float(len(detected)),
                "true_positives": float(true_positives),
                "recovery_rate": true_positives / len(truth) if truth else 1.0,
                "precision": true_positives / len(detected) if detected else (1.0 if not truth else 0.0),
            }
        timings["total"] = time.perf_counter() - overall_start
        write_summary(
            out_dir / "summary.txt",
            len(samples),
            result,
            timings,
            arguments,
            backend,
            tree_status,
            validation,
        )
        LOGGER.info(
            "Completed: %d initial SNPs, %d final SNPs", len(result.initial_positions), len(result.final_positions)
        )
        return 0

    finally:
        # 清理临时参考基因组文件
        if temp_ref_path and Path(temp_ref_path).exists():
            try:
                Path(temp_ref_path).unlink()
                if temp_map_path:
                    temp_map_path.unlink(missing_ok=True)
                LOGGER.debug("已清理临时参考基因组文件: %s", temp_ref_path)
            except OSError as e:
                LOGGER.warning("无法清理临时文件 %s: %s", temp_ref_path, e)

# --- original module: cli.py ---
"""Command-line interface for bactmut-fasta."""

import argparse
import logging
import os
import sys
from pathlib import Path
from typing import Optional, Sequence



def positive_int(value: str) -> int:
    parsed = int(value)
    if parsed <= 0:
        raise argparse.ArgumentTypeError("must be a positive integer")
    return parsed


def positive_int_string(value: str) -> str:
    try:
        parsed = int(value)
    except ValueError as error:
        raise argparse.ArgumentTypeError("must be a positive integer") from error
    if parsed <= 0:
        raise argparse.ArgumentTypeError("must be a positive integer")
    return value


def fraction(value: str) -> float:
    parsed = float(value)
    if not 0 < parsed <= 1:
        raise argparse.ArgumentTypeError("must be greater than 0 and at most 1")
    return parsed


def nonnegative_float(value: str) -> float:
    parsed = float(value)
    if parsed < 0:
        raise argparse.ArgumentTypeError("must be non-negative")
    return parsed


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="bactmut-fasta",
        description=(
            "Compare bacterial genomes to a FASTA reference, detect and filter SNPs, "
            "write an SNP alignment, and optionally build an IQ-TREE phylogeny."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    reference_group = parser.add_mutually_exclusive_group()
    reference_group.add_argument(
        "--reference",
        help="reference genome FASTA path",
    )
    reference_group.add_argument(
        "--species",
        help="species name (e.g., 'Escherichia coli') to automatically fetch reference genome",
    )
    reference_group.add_argument(
        "--taxonid",
        type=positive_int_string,
        help=(
            "NCBI Taxonomy ID (strain-level ncbi_taxid or species-level "
            "ncbi_species_taxid) to select GTDB representative reference"
        ),
    )
    parser.add_argument(
        "--query_dir",
        help="one query genome FASTA file or a directory of FASTA files; required unless --simulate is used",
    )
    parser.add_argument("--out_dir", required=True, help="directory for all pipeline outputs")
    parser.add_argument(
        "--window_size", type=positive_int, default=50, help="recombination scan window size in bp"
    )
    parser.add_argument(
        "--step_size", type=positive_int, default=10, help="recombination scan step size in bp"
    )
    parser.add_argument(
        "--sd_threshold",
        type=nonnegative_float,
        default=3.0,
        help="number of standard deviations above mean SNP density used to flag windows",
    )
    parser.add_argument(
        "--min_coverage",
        type=fraction,
        default=0.9,
        help="minimum fraction of strains that must cover an SNP position",
    )
    parser.add_argument(
        "--aligner",
        choices=("auto", "minimap2", "internal"),
        default="auto",
        help="alignment backend; internal supports equal-length full genomes only",
    )
    parser.add_argument(
        "--threads",
        type=positive_int,
        default=max(1, min(8, os.cpu_count() or 1)),
        help="total alignment worker/thread budget",
    )
    parser.add_argument(
        "--simulate",
        action="store_true",
        help=(
            "generate query genomes with known SNPs and validate recovery; "
            "requires --reference, --species, or --taxonid"
        ),
    )
    parser.add_argument(
        "--simulate_snp_rate",
        type=fraction,
        default=0.001,
        help="per-genome SNP fraction in simulation mode",
    )
    parser.add_argument(
        "--simulate_samples",
        type=positive_int,
        default=5,
        help="number of genomes generated in simulation mode (minimum 5)",
    )
    parser.add_argument("--seed", type=int, default=42, help="simulation random seed")
    parser.add_argument("--verbose", action="store_true", help="enable detailed progress logging")
    return parser


def configure_logging(out_dir: Path, verbose: bool) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    level = logging.DEBUG if verbose else logging.INFO
    formatter = logging.Formatter("%(asctime)s [%(levelname)s] %(message)s")
    console = logging.StreamHandler()
    console.setFormatter(formatter)
    file_handler = logging.FileHandler(out_dir / "pipeline.log", encoding="utf-8")
    file_handler.setFormatter(formatter)
    logging.basicConfig(level=level, handlers=[console, file_handler], force=True)


def main(argv: Optional[Sequence[str]] = None) -> None:
    parser = build_parser()
    args = parser.parse_args(argv)
    if not (args.reference or args.species or args.taxonid):
        parser.error("--reference, --species, or --taxonid is required, including with --simulate")
    if not args.simulate and not args.query_dir:
        parser.error("--query_dir is required unless --simulate is enabled")
    if args.simulate_samples < 5:
        parser.error("--simulate_samples must be at least 5")
    out_dir = Path(args.out_dir).resolve()
    configure_logging(out_dir, args.verbose)
    try:
        exit_code = run_pipeline(vars(args))
    except (OSError, ValueError, RuntimeError) as error:
        logging.getLogger(__name__).error("Pipeline failed: %s", error)
        raise SystemExit(2) from error
    raise SystemExit(exit_code)

# --- original module: config_runner.py ---
"""BioAgent YAML configuration entry point for bactmut-fasta."""


import json
import math
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence

import yaml


class ConfigError(ValueError):
    """Raised when a BioAgent runtime configuration is invalid."""


_OUTPUT_DEFAULTS = {
    "matrix_path": "filtered_snp_matrix.fasta",
    "variants_path": "variants.tsv",
    "variants_summary_path": "variants_summary.txt",
    "pipeline_summary_path": "summary.txt",
    "initial_snps_path": "initial_snp_list.csv",
    "mutation_report_path": "mutation_report.csv",
    "final_tree_path": "final_tree.nwk",
    "treefile_path": "iqtree_run.treefile",
    "iqtree_report_path": "iqtree_run.iqtree",
    "iqtree_log_path": "iqtree_run.log",
    "pipeline_log_path": "pipeline.log",
}
_REQUIRED_OUTPUT_KEYS = (
    "report_path",
    "metrics_path",
    "matrix_path",
    "variants_path",
    "variants_summary_path",
    "pipeline_summary_path",
)


@dataclass(frozen=True)
class PipelineConfig:
    label: str
    input_path: Path
    reference_path: Path | None
    output_dir: Path
    output_paths: Mapping[str, Path]
    reference_mode: str
    species: str | None
    taxonid: str | None
    threads: int
    aligner: str
    min_coverage: float
    window_size: int
    step_size: int
    sd_threshold: float
    simulate: bool
    simulate_snp_rate: float
    simulate_samples: int
    seed: int
    verbose: bool

    def pipeline_arguments(self) -> dict[str, object]:
        return {
            "reference": str(self.reference_path) if self.reference_mode == "local" else None,
            "species": self.species if self.reference_mode == "species" else None,
            "taxonid": self.taxonid if self.reference_mode == "taxonid" else None,
            "query_dir": None if self.simulate else str(self.input_path),
            "out_dir": str(self.output_dir),
            "window_size": self.window_size,
            "step_size": self.step_size,
            "sd_threshold": self.sd_threshold,
            "min_coverage": self.min_coverage,
            "aligner": self.aligner,
            "threads": self.threads,
            "simulate": self.simulate,
            "simulate_snp_rate": self.simulate_snp_rate,
            "simulate_samples": self.simulate_samples,
            "seed": self.seed,
            "verbose": self.verbose,
        }


def load_config(config_path: str | Path) -> PipelineConfig:
    path = Path(config_path).expanduser()
    if not path.is_file():
        raise ConfigError(f"configuration file not found: {path}")
    try:
        with path.open(encoding="utf-8") as stream:
            raw = yaml.safe_load(stream)
    except yaml.YAMLError as error:
        raise ConfigError(f"invalid YAML in {path}: {error}") from error
    if not isinstance(raw, Mapping):
        raise ConfigError("configuration root must be a YAML mapping")
    return parse_config(raw, base_dir=path.resolve().parent)


def parse_config(raw: Mapping[str, Any], *, base_dir: Path) -> PipelineConfig:
    base_dir = Path(base_dir).resolve()
    params = raw.get("params")
    if not isinstance(params, Mapping):
        params = {}

    def param(key: str, default: Any = None) -> Any:
        return raw.get(key, params.get(key, default))

    label = _nonempty_string(raw.get("label"), "label")
    input_path = _resolve_path(raw.get("input_path"), "input_path", base_dir)
    output_dir = _resolve_path(raw.get("output_dir"), "output_dir", base_dir)
    reference_path = _optional_path(raw.get("reference_path"), "reference_path", base_dir)

    reference_mode = _choice(
        param("reference_mode", "local"),
        "params.reference_mode",
        {"local", "species", "taxonid"},
    )
    species = _optional_string(param("species"))
    taxonid = _optional_taxonid(param("taxonid"))
    if reference_mode == "local" and reference_path is None:
        raise ConfigError("reference_mode 'local' requires reference_path")
    if reference_mode == "species" and species is None:
        raise ConfigError("reference_mode 'species' requires non-empty params.species")
    if reference_mode == "taxonid" and taxonid is None:
        raise ConfigError("reference_mode 'taxonid' requires positive params.taxonid")

    output_paths: dict[str, Path] = {
        "report_path": _resolve_path(raw.get("report_path"), "report_path", base_dir),
        "metrics_path": _resolve_path(raw.get("metrics_path"), "metrics_path", base_dir),
    }
    for key, filename in _OUTPUT_DEFAULTS.items():
        value = raw.get(key)
        output_paths[key] = (
            _resolve_path(value, key, base_dir)
            if value not in (None, "")
            else output_dir / filename
        )

    simulate_samples = _positive_integer(
        param("simulate_samples", 5), "params.simulate_samples"
    )
    if simulate_samples < 5:
        raise ConfigError("params.simulate_samples must be at least 5")

    return PipelineConfig(
        label=label,
        input_path=input_path,
        reference_path=reference_path,
        output_dir=output_dir,
        output_paths=output_paths,
        reference_mode=reference_mode,
        species=species,
        taxonid=taxonid,
        threads=_positive_integer(param("threads", 1), "params.threads"),
        aligner=_choice(
            param("aligner", "auto"),
            "params.aligner",
            {"auto", "minimap2", "internal"},
        ),
        min_coverage=_fraction(param("min_coverage", 0.9), "params.min_coverage"),
        window_size=_positive_integer(param("window_size", 50), "params.window_size"),
        step_size=_positive_integer(param("step_size", 10), "params.step_size"),
        sd_threshold=_nonnegative_float(
            param("sd_threshold", 3.0), "params.sd_threshold"
        ),
        simulate=_boolean(param("simulate", False), "params.simulate"),
        simulate_snp_rate=_fraction(
            param("simulate_snp_rate", 0.001), "params.simulate_snp_rate"
        ),
        simulate_samples=simulate_samples,
        seed=_integer(param("seed", 42), "params.seed"),
        verbose=_boolean(param("verbose", False), "params.verbose"),
    )


def run_config(config: PipelineConfig) -> int:
    if not config.simulate and not config.input_path.exists():
        raise ConfigError(f"input_path does not exist: {config.input_path}")
    if config.reference_mode == "local":
        assert config.reference_path is not None
        if not config.reference_path.is_file():
            raise ConfigError(f"reference_path is not a file: {config.reference_path}")

    config.output_dir.mkdir(parents=True, exist_ok=True)

    configure_logging(config.output_dir, config.verbose)
    result = run_pipeline(config.pipeline_arguments())
    if int(result or 0) != 0:
        raise RuntimeError(f"bactmut-fasta exited with status {result}")

    _publish_outputs(config)
    metrics = _build_metrics(config)
    _write_metrics(config.output_paths["metrics_path"], metrics)
    _write_report(config, metrics)
    _assert_required_outputs(config)
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    if len(args) != 1:
        print(
            "Usage: python3 -m bactmut_fasta.config_runner CONFIG.yaml",
            file=sys.stderr,
        )
        return 2
    try:
        return run_config(load_config(args[0]))
    except (
        ConfigError,
        OSError,
        RuntimeError,
        ValueError,
        subprocess.SubprocessError,
    ) as error:
        print(f"bactmut_fasta pipeline error: {error}", file=sys.stderr)
        return 1


def _publish_outputs(config: PipelineConfig) -> None:
    for key, filename in _OUTPUT_DEFAULTS.items():
        source = config.output_dir / filename
        destination = config.output_paths[key]
        if not source.is_file() or source.resolve() == destination.resolve():
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)


def _build_metrics(config: PipelineConfig) -> dict[str, object]:
    summary_path = config.output_dir / "summary.txt"
    summary = summary_path.read_text(encoding="utf-8") if summary_path.is_file() else ""

    def integer(pattern: str) -> int | None:
        match = re.search(pattern, summary, flags=re.MULTILINE)
        return int(match.group(1)) if match else None

    tree_match = re.search(r"^Tree building:\s*(.+)$", summary, flags=re.MULTILINE)
    return {
        "pipeline": "bactmut_fasta",
        "label": config.label,
        "status": "completed",
        "reference_mode": config.reference_mode,
        "sample_count": integer(r"^Input strain count:\s*(\d+)"),
        "initial_snp_positions": integer(r"^Initial unique SNP positions:\s*(\d+)"),
        "after_coverage_filter": integer(r"^After coverage filter .*?:\s*(\d+)"),
        "final_snp_positions": integer(r"^Final SNPs used for tree building:\s*(\d+)"),
        "recombination_regions": integer(r"^Recombination candidate regions:\s*(\d+)"),
        "tree_status": tree_match.group(1).strip() if tree_match else "unknown",
    }


def _write_metrics(path: Path, metrics: Mapping[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(metrics, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def _write_report(config: PipelineConfig, metrics: Mapping[str, object]) -> None:
    summary_path = config.output_dir / "summary.txt"
    summary = (
        summary_path.read_text(encoding="utf-8").strip()
        if summary_path.is_file()
        else "Pipeline summary was not available."
    )
    lines = [
        f"# {config.label}",
        "",
        "BactMut FASTA completed successfully.",
        "",
        "## Key metrics",
        "",
        f"- Samples: {metrics.get('sample_count')}",
        f"- Initial SNP positions: {metrics.get('initial_snp_positions')}",
        f"- Final SNP positions: {metrics.get('final_snp_positions')}",
        f"- Tree: {metrics.get('tree_status')}",
        "",
        "## Pipeline summary",
        "",
        "```text",
        summary,
        "```",
        "",
        "The filtered alignment, variant table, detailed reports, and optional "
        "IQ-TREE files are published as separate BioAgent outputs.",
        "",
    ]
    path = config.output_paths["report_path"]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def _assert_required_outputs(config: PipelineConfig) -> None:
    missing = [
        str(config.output_paths[key])
        for key in _REQUIRED_OUTPUT_KEYS
        if not config.output_paths[key].is_file()
    ]
    if missing:
        raise RuntimeError("pipeline did not generate required output(s): " + ", ".join(missing))


def _resolve_path(value: Any, field: str, base_dir: Path) -> Path:
    text = _nonempty_string(value, field)
    path = Path(text).expanduser()
    return path.resolve() if path.is_absolute() else (base_dir / path).resolve()


def _optional_path(value: Any, field: str, base_dir: Path) -> Path | None:
    if value in (None, ""):
        return None
    return _resolve_path(value, field, base_dir)


def _nonempty_string(value: Any, field: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ConfigError(f"{field} must be a non-empty string")
    return value.strip()


def _optional_string(value: Any) -> str | None:
    if value in (None, ""):
        return None
    if not isinstance(value, str):
        raise ConfigError("optional text parameters must be strings")
    return value.strip() or None


def _choice(value: Any, field: str, choices: set[str]) -> str:
    text = _nonempty_string(value, field).lower()
    if text not in choices:
        raise ConfigError(f"{field} must be one of: {', '.join(sorted(choices))}")
    return text


def _integer(value: Any, field: str) -> int:
    if isinstance(value, bool):
        raise ConfigError(f"{field} must be an integer")
    if isinstance(value, int):
        return value
    if isinstance(value, str):
        try:
            return int(value.strip())
        except ValueError as error:
            raise ConfigError(f"{field} must be an integer") from error
    raise ConfigError(f"{field} must be an integer")


def _positive_integer(value: Any, field: str) -> int:
    integer = _integer(value, field)
    if integer < 1:
        raise ConfigError(f"{field} must be a positive integer")
    return integer


def _float(value: Any, field: str) -> float:
    if isinstance(value, bool):
        raise ConfigError(f"{field} must be numeric")
    try:
        number = float(value)
    except (TypeError, ValueError) as error:
        raise ConfigError(f"{field} must be numeric") from error
    if not math.isfinite(number):
        raise ConfigError(f"{field} must be finite")
    return number


def _fraction(value: Any, field: str) -> float:
    number = _float(value, field)
    if not 0 < number <= 1:
        raise ConfigError(f"{field} must be greater than 0 and at most 1")
    return number


def _nonnegative_float(value: Any, field: str) -> float:
    number = _float(value, field)
    if number < 0:
        raise ConfigError(f"{field} must be non-negative")
    return number


def _boolean(value: Any, field: str) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, str) and value.strip().lower() in {"true", "false"}:
        return value.strip().lower() == "true"
    raise ConfigError(f"{field} must be true or false")


def _optional_taxonid(value: Any) -> str | None:
    if value in (None, ""):
        return None
    return str(_positive_integer(value, "params.taxonid"))


if __name__ == "__main__":
    raise SystemExit(main())
